### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tstenner** [sccn/labstreaminglayer#1]
Track the documentation progress:

- [x] Migrate the [wiki pages](https://github.com/labstreaminglayer/labstreaminglayer/wiki) to README files in the respective folders
- [ ] Remove outdated documentation
- [x] Replace links to the old repository / Google Code
- [ ] Create a "Getting Started"-page for developers
- [x] Create a "Getting Started"-page for users

**Comment by cboulay** [comment]
I merge most of the Wiki pages into README files in their respective submodules. I couldn't figure out where OVAS or BAlert go. Do we have apps for these?

**Comment by tstenner** [comment]
For some reason the BAlert folder was missing but present as a submodule. I've re-added it and transferred the Wiki page, but I can't find the OVAS folder in both the new and old repositories.

**Comment by cboulay** [comment]
Docs diverged from this issue quite a bit. Now hosted on https://labstreaminglayer.readthedocs.io/index.html
