### ISSUE TITLE
CMake MSVC Generator error - `Evaluation file to be written multiple times with different content.`

### ISSUE THREAD

**Issue by tnguyen1992** [sccn/labstreaminglayer#10]
Dear all, 
I am currently building LSL to synchronize an BrainVision Recorder ECG stream, a NIRStar stream and a video stream. When building the Brain Amp App I encountered an error in Cmake. So these were the steps I took until I encountered an error:

1. firstly, I cloned the repository in my LSL folder with git clone --recursive https://github.com/sccn/labstreaminglayer.git 
2. I created a "build" folder and moved into that directory
3.  I typed in "cmake-gui .." (Cmake 3.12.3)
4. the I configured the whole thing with Brain Amp and LabRecorder, which resulted in this

> Git version information: HEAD/1.13.0-b3-20-g2a9dbeaa
Included LSL CMake helpers, rev. 9
Found target lsl in current build tree
Included LSL CMake helpers, rev. 9
Found target lsl in current build tree
CMake Warning at Apps/CMakeLists.txt:28 (message):
  LSLAPPS_BrainAmp was enabled, but its folder is either nonexistent or not
  checked out

> Little endian: 1
IEC559: TRUE
MENU appended: LabRecorder
MENU appended: BrainAmpSeries
Boost version: 1.65.1
Found the following Boost libraries:
  system
  thread
  chrono
  date_time
  atomic
MENU appended: BrainVisionRDA
MENU: LabRecorder/LabRecorder.exe;LabRecorder;BrainAmpSeries/BrainAmpSeries.exe;BrainAmpSeries;BrainVisionRDA/BrainVisionRDA.exe;BrainVisionRDA
Setting packages name for BRAINAMPSERIES
File name: BrainAmpSeries-1.12.0-Win32
Setting packages name for BRAINVISIONRDA
File name: BrainVisionRDA-1.12.0-Win32
Setting packages name for LABRECORDER
File name: LabRecorder-1.12.0-Win32
Setting packages name for LIBLSL
File name: liblsl-1.12.0-Win32
Installing Components: BrainAmpSeries;BrainVisionRDA;LabRecorder;liblsl
Configuring done

so when I clicked on generate I got this error

```CMake Error in Apps/LabRecorder/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/LabRecorder/LabRecorder_path


CMake Error in Apps/BrainAmpSeries/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainAmpSeries/BrainAmpSeries_path


CMake Error in Apps/BrainAmpSeries/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainAmpSeries/BrainAmpSeries_path


CMake Error in Apps/BrainProducts/BrainVisionRDA/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainProducts/BrainVisionRDA/BrainVisionRDA_path


CMake Error in Apps/BrainProducts/BrainVisionRDA/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainProducts/BrainVisionRDA/BrainVisionRDA_path


Generating done```

Can I do something different to resolve this issue?

Thanks so much in advance!

**Comment by cboulay** [comment]
I'm getting this too using command-line cmake, and I'm getting it for LabRecorder too.
I'm in the operating room today so I won't be able to fix it right away. Hopefully @tstenner can.

**Comment by tstenner** [comment]
I'm currently on vacation without my laptop, but here's what I think:

The MSVC generator supports multiple configurations (debug/release) and in debug builds, we add an extra flag to the windepoyqt options
The offending party starts in lslcmake.cmake (liblsl repo) with if (CMAKE_INSTALL_CONFIG_NAME STREQUAL \"Debug\")

**Comment by tnguyen1992** [comment]
Did I understand you correctly when replacing the file name like this:
`set(QT_DEPLOYQT_FLAGS --no-translations --no-system-d3d-compiler --no-opengl-sw --no-compiler-runtime)
				file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/$target_$install_config_name_path"
					CONTENT "$<TARGET_FILE:${target}>"
				)
				get_filename_component(appdir ${appbin} DIRECTORY CACHE)
				install (CODE "
					file(READ \"${CMAKE_CURRENT_BINARY_DIR}/${target}_$install_config_name_path\" _file)
					message (STATUS \"Running Qt Deploy Tool for \${_file}\")
					if (CMAKE_INSTALL_CONFIG_NAME STREQUAL \"Debug\")
						set(QT_DEPLOYQT_FLAGS \"\${QT_DEPLOYQT_FLAGS} --debug\")
					else ()
						set(QT_DEPLOYQT_FLAGS \"\${QT_DEPLOYQT_FLAGS} --release\")
					endif ()`

If yes, I still get a similar error:

```
CMake Error in Apps/LabRecorder/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/LabRecorder/$target_$install_config_name_path


CMake Error in Apps/LabRecorder/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/LabRecorder/$target_$install_config_name_path


CMake Error in Apps/BrainAmpSeries/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainAmpSeries/$target_$install_config_name_path


CMake Error in Apps/BrainAmpSeries/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainAmpSeries/$target_$install_config_name_path


CMake Error in Apps/BrainProducts/BrainVisionRDA/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainProducts/BrainVisionRDA/$target_$install_config_name_path


CMake Error in Apps/BrainProducts/BrainVisionRDA/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainProducts/BrainVisionRDA/$target_$install_config_name_path
```

**Comment by tstenner** [comment]
My bad, I didn't type it out because it's a bit hard to do on a smartphone keyboard. The correct filename should be `${CMAKE_CURRENT_BINARY_DIR}/${target}_${CMAKE_INSTALL_CONFIG_NAME}_path`

**Comment by tnguyen1992** [comment]
Oh ok, I also tried that and other variations with the same error as a result:
```
CMake Error in Apps/LabRecorder/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/LabRecorder/LabRecorder__path


CMake Error in Apps/LabRecorder/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/LabRecorder/LabRecorder__path


CMake Error in Apps/BrainAmpSeries/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainAmpSeries/BrainAmpSeries__path


CMake Error in Apps/BrainAmpSeries/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainAmpSeries/BrainAmpSeries__path


CMake Error in Apps/BrainProducts/BrainVisionRDA/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainProducts/BrainVisionRDA/BrainVisionRDA__path


CMake Error in Apps/BrainProducts/BrainVisionRDA/CMakeLists.txt:
  Evaluation file to be written multiple times with different content.  This
  is generally caused by the content evaluating the configuration type,
  language, or location of object files:

   C:/Users/User/Documents/labstreaminglayer/build/Apps/BrainProducts/BrainVisionRDA/BrainVisionRDA__path


Generating done
```

**Comment by cboulay** [comment]
The fix didn't work because at the time `installLSLAppSingleFolder` is run, `${CMAKE_INSTALL_CONFIG_NAME}` resolves to '', and is thus still the same for both configs. The `install` code block, where `CMAKE_INSTALL_CONFIG_NAME` is used to change the qt deploy flags, is run later.

I'll keep looking.

**Comment by cboulay** [comment]
I replaced `${CMAKE_INSTALL_CONFIG_NAME}` with `${CMAKE_BUILD_TYPE}`, which does correctly resolve to `Release` or `Debug`, but the problem persists. In fact, even if I use `-DCMAKE_BUILD_TYPE=Debug` (or `Release`), the problem is still there. i.e., it happens for single configurations.

Also worth noting that the error happens well after configure, during generation. So it's likely a problem in the generator expressions.

BTW, @tnguyen1992 , until we fix this, you can use MSVC 2017 integrated cmake support. In file explorer, right click somewhere in the labstreaminglayer folder and choose "Open in Visual Studio". There are more instructions in docs/BUILD.md

**Comment by cboulay** [comment]
OK it's been fixed. If you do a `git fetch && git pull && git submodule update` then everything should be in place.

**Comment by tnguyen1992** [comment]
Thanks so much, Chadwick!

Von: Chadwick Boulay <notifications@github.com>
Gesendet: Mittwoch, 19. Dezember 2018 18:07
An: sccn/labstreaminglayer <labstreaminglayer@noreply.github.com>
Cc: Quynh Trinh Nguyen <trinh.nguyen@univie.ac.at>; Mention <mention@noreply.github.com>
Betreff: Re: [sccn/labstreaminglayer] CMake MSVC Generator error - `Evaluation file to be written multiple times with different content.` (#10)


OK it's been fixed. If you do a git fetch && git pull && git submodule update then everything should be in place.
