### ISSUE TITLE
Screen Capture as an LSL Inlet

### ISSUE THREAD

**Issue by vahid-sb** [sccn/labstreaminglayer#107]
Hi all
This is not an issue, rather an enquiery about a possible feature. Has anybody used a screen capture software as a inlet for LSL? Or has anybody got any suggestions on that? To clarify: I want to allow the participants in my experiment to interact with visual stimuli, as an example, to scroll through a website or a document. I want to record the session using a screen capture software and then synchronise the time-stamps of the resulting video with signals from my other recording modalities, such as eye-tracking and EEG. 
Any help on that would be much appreciated. 
Regards,
Vahid

**Comment by cboulay** [comment]
You can make an OBS Plugin that regularly sends the frame counter value over LSL.

**Comment by cboulay** [comment]
I just did a search for `GitHub OBS LSL` and found this:
https://github.com/JasonJKi/obs-studio-labstreaminglayer

**Comment by vahid-sb** [comment]
@cboulay thanks a lot for bringing this to my attention. Much appreciated. I will test the repo and report the outcome in this thread for others who might also be interested.

**Comment by cboulay** [comment]
Closing as the question was answered and there's nothing more to be done by LSL. I'm sure any more info on an LSL enabled screen-capturer would be welcome but it's not within the scope of this repo.
