### ISSUE TITLE
LSL and Simulink

### ISSUE THREAD

**Issue by 7henry767** [sccn/labstreaminglayer#11]
Hey,

do you know a way to use LSL in a Simulink Model / do you have ideas how to do this?

I only found a thing called SimBSI but its unstable and crashes all the time.

**Comment by cboulay** [comment]
I haven't used Simulink in a long time, but I think you would have to create a custom block and inside the code for that block you would call LSL using the Matlab interface.

**Comment by cboulay** [comment]
Please reopen if you have further questions on this topic.

**Comment by aojeda** [comment]
Only now I learned about this question. For completeness, I will post a link to an LSL/SImulink example. Then feel free to close this issue.

https://bitbucket.org/neatlabs/simbsi/wiki/LSL%20signal%20acquisition%20example
