### ISSUE TITLE
BAlert unable to load

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#110]
Compiling BAlert is fine, but on startup it throws:
![balert_error](https://cloud.githubusercontent.com/assets/3613166/14442881/f6172d4c-fff0-11e5-870d-74cb958769ad.png)

I tried to track down the missing library, although not very hard. I am assuming it is a proprietary library that the vendor supplies which isn't on my computer?

**Comment by chkothe** [comment]
Probably BAlert.dll or SiUSBXp.dll -- used to be in the old repo.

Christian

**Comment by dmedine** [comment]
SiUSBXp.dll was the culprit.
