### ISSUE TITLE
Support for QUIC?

### ISSUE THREAD

**Issue by yasithdev** [sccn/labstreaminglayer#111]
Hi All,

Wondering if there's any plans to support QUIC in LabStreamingLayer. I can see numerous benefits of doing so, like reading data from modern web browsers.

**Comment by cboulay** [comment]
liblsl uses `asio` and doesn't handle networking directly. If `asio` supports QUIC then liblsl can support QUIC.

I'm closing this issue because there's nothing to be done at this time. If the situation with asio changes then we can revisit.
