### ISSUE TITLE
BrainVisionRDA compile errors

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#111]
It seems that it isn't legal to declare 
`lsls::xml_element channels`
in line 144 of mainwindow.cpp and then construct the variable elsewhere (line 205):
`channels = lsl_info->desc().append_child("channels");`

This may be remedied by a -std=c++0x flag, (or something similar) but maybe the code should be rewritten.

**Comment by chkothe** [comment]
That part shouldn't be a problem, since xml_element is just a pointer.
Should also be unrelated to c++0x (in fact, that should be needed only in
the rarest of cases like with that one boost lib that got upgraded
deliberately to c++0x and then no longer compiled with an old compiler.

Christian

**Comment by dmedine** [comment]
So should I just revise the code to declare channels as a pointer and handle allocation/reallocation/deallocation by hand?

**Comment by chkothe** [comment]
So I just tried to build it over here, and I'm getting an error that
xml_element doesn't have a default constructor. Let's just define one,
changing the constructor of xml_element to:

    class xml_element {
    public:
        /// Constructor.
        xml_element(lsl_xml_ptr obj=0) : obj(obj) {}

**Comment by dmedine** [comment]
Oh right! C++. Will do.

**Comment by dmedine** [comment]
Yes this now works. I will push the changes to the PR.
