### ISSUE TITLE
compile errors for SMIEyetracker NG and X

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#113]
Both these environments are missing (proprietary?) headers.
NG:
`Cannot open include file: 'iViewNG-Core.h': No such file or directory`

X:
`fatal error C1083: Cannot open include file: 'iViewXAPI.h': No such file or directory`

**Comment by chkothe** [comment]
Yes, they asked us to not include the SDK -- I think the instructions
should explain what's necessary to get it to run (get the sdk, copy all
files in there, then build).

Christian

**Comment by dmedine** [comment]
Thanks for clarifying this. It was as I suspected then. Closing.
