### ISSUE TITLE
compile error in StaticInfo

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#114]
This seems to be a C++/pugixml version kind of issue:
`1>.\mainwindow.cpp(142) : error C2664: 'lsl::xml_element::append_copy' : cannot convert parameter 1 from 'pugi::xml_node' to 'const lsl::xml_element &'
1>        Reason: cannot convert from 'pugi::xml_node' to 'const lsl::xml_element'`

The offending line (142) reads:
`info.desc().append_copy(doc.document_element());`

where `doc` is of type `pugi::xml_document`

**Comment by chkothe** [comment]
This needs an explicit cast to pugi::xml_node, apparently that was
permitted before -- is this already using VS2013?

**Comment by dmedine** [comment]
Nope. 2008.

**Comment by chkothe** [comment]
Could it be that the type of the pugi::xml_node has changed in the pugi
update that was recently rolled in? Used to be a class that wrapped a
pointer to some implementation struct. Maybe that no longer has an
assignment operator or something like that.

**Comment by dmedine** [comment]
I don't recall actually changing the version of pugi that we use here. I remember talking about it but I don't remember actually taking any action. Obviously something has changed  or else this wouldn't be a problem.

**Comment by cboulay** [comment]
I did in #84

**Comment by dmedine** [comment]
Right, but clearly we did update pugixml, because it is version 1.7, which is the newest. I perused their changelogs and I didn't see anything about an adjustment to the xml_node class (which is a wrapper to an xml_node_struct). I suppose we need to add an operator to do the conversion.

**Comment by chkothe** [comment]
We might check why it did work earlier, and then replicate what we need in
1.7.

**Comment by dmedine** [comment]
could be that the change from 
`typedef xml_node_struct* xml_node::*unspecified_bool_type;`
in 1.0  to 
`typedef void (*unspecified_bool_type)(xml_node***);`
in 1.7 has something to do with this. I confess that this particular instance c++-ese is beyond my knowledge.

The append_copy method is also a bit different in the newer version but both versions return a variable with the type `xml_node`

**Comment by tstenner** [comment]
Since both VS2008 and VS2017 compile fine at the moment, I'm closing this.
