### ISSUE TITLE
lsl::inlet cannot convert std::vector>

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#115]

**Comment by chkothe** [comment]
What's the sample code that reproduces it?

**Comment by dmedine** [comment]
Don't know why I'm getting this error. The info that I use to build the inlet is of cft_doubl64. I don't see why I can't pull into a vector of doubles. lsl_cpp.h line 782:
`double pull_sample(std::vector<float> &sample, double timeout=FOREVER) { sample.resize(channel_count); return pull_sample(&sample[0],(int)sample.size(),timeout); }`

**Comment by dmedine** [comment]
inlet creation:
`lsl::stream_inlet inlet(rcv_info, timeout, LSL_NO_PREFERENCE, 1);`
call to pull:
`inlet.pull_sample(dbl_data, rcv_info.channel_count(), LSL_FOREVER);`

**Comment by chkothe** [comment]
Ok, and what error message are you getting? (could it be that the vector is
const or something / does that also happen when you manually call it
with &dbl_data[0],
dbl_data.size(), or when you go directly down to lsl_pull_sample_d?

**Comment by dmedine** [comment]
Here is the error:

` error C2664: 'double lsl::stream_inlet::pull_sample(float *,int,double)' : cannot convert parameter 1 from 'std::vector<_Ty>' to 'float *'`

It is the same if use dbl_data and &dbl_data[0]

I'm working on using the plain C API, I'm getting some undeclared identifier lsl_inlet errors for some reason...

**Comment by dmedine** [comment]
Ahh, the C API is in the lsl namespace, so you have to use the lsl:: prefix. Got it.

Ok, so going down to lsl_pull_sample_d does work with a reference to the first item in a std::vector<double>

I somehow doubt this is a bug in the API itself. Doing this works fine with the pull_chunk template because that's exactly what labrecorder does. A quick glance tells me this is done exactly the same way with the pull template.

**Comment by dmedine** [comment]
Aha. The problem is that the definitions of pull_sample that take a vector as the first argument do not take a second argument to indicate the size of the vector (since the vector object contains that information already...). So when I supplied this argument, the compiler must have defualted to the first definition of pull_sample, which takes a float *. 

A small gotcha.

**Comment by chkothe** [comment]
Ah yes, totally overlooked that myself.
