### ISSUE TITLE
LSL byprop error in BCI2000

### ISSUE THREAD

**Issue by Nigama-oss** [sccn/labstreaminglayer#115]
I'm using an Emotive EPOC+ 14-channel EEG system to establish a connection using the LSLSource batch file within the BCI2000 framework, but it throws an `lsl_resolve_byprop: error 1`. I have contacted the BCI2000 forum to resolve this issue, but wasn't successful so far, since they weren't familiar with LSL. 

One of the reasons they mentioned was: In the LSL protocol, data streams are registered with a "type". The EPoC documentation about LSL should tell you which type the EPoC uses when registering its data stream. The difference could be as trivial as "eeg" instead of "EEG". In BCI2000, a type of "EEG" is hard coded, so these two need to match in order for the batch file to run without any error. 

I have cross-checked the source code and the EPOC documentation for this and both of these have the same stream 'type'. So the issue lies elsewhere. Could there be any other reason for this error?

It's worth noting that the BCI2000 installation has no problems.

![bci2000Error2](https://github.com/sccn/labstreaminglayer/assets/56264990/a7b33e29-37f2-4c06-a000-e21084c268f9)

**Comment by cboulay** [comment]
I suspect it is too late for you @Nigama-oss , but my advice is as follows:

1. Check if LabRecorder can resolve the stream.
2a. If LabRecorder can indeed resolve the stream, then there's no good reason BCI2000 can't other than there's an implementation or configuration error within BCI2000 that is somehow incompatible with the Emotiv stream, and there is nothing I can help you with.
2b. If LabRecorder cannot resolve the stream then the BCI2000 error is just a symptom of a different problem and I would ask you to open a new issue in the GH repo where you downloaded the Emotiv app from.
