### ISSUE TITLE
Matlab pullsample, crash

### ISSUE THREAD

**Issue by atom2626** [sccn/labstreaminglayer#122]
Hi,

I'm running the sample code provided. I run two Matlab instance, one is SendingStringMarkers, the other is ReceivingStringMarkers. The latter process crashes on the inlet.pullsample() call.

Attached is the Matlab crash report.
[matlab_crash_dump.txt](https://github.com/sccn/labstreaminglayer/files/324082/matlab_crash_dump.txt)

There is a recent issue regarding a memory leak in pullsample, in C++. Both might have the same cause.

**Comment by chkothe** [comment]
Hi Fred, this is interesting (the error seems to happen in the MATLAB
wrapper mex file), but seems related to memory reclamation. Let's determine
what version of liblsl is being used in that MATLAB interface. Is this an
LSL release downloaded from the FTP mirror (and if so, what version), or is
this a clone from github (and if so, which commit id)?

**Comment by dmedine** [comment]
For what it's worth, running two instances of matlab 2014a on my machine 
(windows 7) and running SendStringMarkers and ReceiveStringMarkers with 
the latest version of LSL works just fine for me. This must be an 
environment/version problem.

**Comment by atom2626** [comment]
Hi,

I downloaded it from:
ftp://sccn.ucsd.edu/pub/software/LSL/SDK/

And picked version 1.11, compiled with MinGW64 Compiler (C), I believe.I'm currently testing on my other computer. I'll let you know.

**Comment by chkothe** [comment]
Thanks!

**Comment by atom2626** [comment]
I have the exact same issue. I'll try to add in some details.

Both are compiled for 64bits, although I use two different compilers (MinGW64 and Microsoft Visual C++ 2015).

In both cases, Matlab 2015b, one of the two setups has a legit Academic version.

I'll attach the crash report of my other computer in a few seconds.

**Comment by atom2626** [comment]
I tried on a third computer, using the same source code. This time with Matlab 2014b and I get the same result.

**Comment by tstenner** [comment]
Could you see if it still happens with the binaries in https://bintray.com/labstreaminglayer/LSL/download_file?file_path=liblsl-matlab-win64.7z ?
