### ISSUE TITLE
Very specific LSL sync issues

### ISSUE THREAD

**Issue by bdyetton** [sccn/labstreaminglayer#13]
Hi LSL team,
I have a specific issue that i'd like help with, and not really a bug, so apologies for raising an issue here.

I recorded 20 subjects worth of EEG data while they watched videos.
There were two LSL streams, one for video start _markers_, and one for EEG as recorded with a _muse_ headset, and the help of bluemuse to create the lsl stream.
The issue is that bluemuse (and the _muse_ stream) were started on one computer, and the _marker_ stream were started on another. Usually, this would not be an issue, and lsl would automatically sync these, but bluemuse writes timestamps as time since epoch, and not as time since local computer startup. This means that the xdf file which stores both streams (recorded with "lab recorder" from the Neuropype software suite), cannot be adjusted on load, because all the internal lsl syncing information is is based on time since local machine startup, and does not correspond with the actual timestamps (in time since epoch). 
I've tried to dig into the interals of the lsl stream object and see if firsttimestamp, lasttimestamp and  created_at could help, but unfortunately, I cannot see a way to sync. 
Can you help me sync these two streams?
If there is a timestamp written when an lsl stream starts to be written to file, then this would help sync things.

**Comment by bdyetton** [comment]
I noticed that there is a clock_offsets array in the lsl object, this seems to be sampled ever 5.25 seconds. Is this sample time relative to anything? For example, could I assume that the first clock offset time occurs when the first EEG timestamp is written?

**Comment by cboulay** [comment]
Can you hop onto Slack? I have many questions and the back and forth via GitHub issues will take a long time.

**Comment by cboulay** [comment]
@tstenner and @mgrivich , can you comment?

The timestamps for one stream were manually set using a different time base than lsl_local_clock uses on that platform. I guess clock offsets are then useless. Is there anything else in the xdf that can help him synchronize his streams?

Attached is an xdf file with this problem.
[Uploading ID004.zip…]()

**Comment by mgrivich** [comment]
For new data, there are various ways this could be fixed.

For old data, The timestamps are wrong by a constant offset (the difference between epoch time and start time is fixed each time the computer is started). You could get to within a 100 ms or so by just assuming that the first sample from each stream is at the same time. Finer tuning that that would require some sort of independent fiduciary marks in the data (such as a voltage trigger channel).

I don't see anything in the XDF format that would record epoch time.

**Comment by tstenner** [comment]
> The timestamps are wrong by a constant offset

This is true in general, but in specific circumstances (e.g. some clock sources are monotonic, i.e. timestamps increase no matter what, while other clocks might jump in case of NTP time sync).

Contrary to the title, this isn't a specific sync issue but a general issue on how to specify device timestamps. In my TobiiPro connector I can cheat because both use the same libc `gettime` function, but we have no general way to record device timestamps alongside lsl timestamps.

**Comment by mgrivich** [comment]
> Contrary to the title, this isn't a specific sync issue but a general issue on how to specify device timestamps. In my TobiiPro connector I can cheat because both use the same libc gettime function, but we have no general way to record device timestamps alongside lsl timestamps.

No, this is a very specific question: If it is possible to salvage some data that was improperly acquired. Anything I say here is not going to be generally applicable.

**Comment by mgrivich** [comment]
> For the EEG stream (the one with the bad timestamps), will LabRecorder fetch the first clock_offset as soon as the inlet is opened, when the first sample is retrieved, or something else?

I'm not sure without doing a code dive, but the answer isn't that important. Let's put it this way: allowing XDF to run normally, in this specific case, should get timestamps that are correct except for a constant offset between the two streams.

> The video stream is intermittent and only provides timestamps when a videoclip is played.

This makes it trickier. It would be necessary then to go through the xdf file manually (or writing a custom script), inspecting chunk ordering. Chunks that are close together are close in time. However, this does mean that there are multiple (rough) measurements of the offset between turn-on time and epoch time in each data set.

At some point it does become a question of whether it is cheaper to take new data or work to salvage this data.

**Comment by mgrivich** [comment]
By the way, XDFBrowser (at ftp://sccn.ucsd.edu/pub/software/LSL/Apps/XDFBrowser-1.10.zip) can help with understand the XDF file structure, and can be used to inspect chunks in individual files (except the binary chunks are not parsed).  See also the specification. https://github.com/sccn/xdf/wiki/Specifications

**Comment by bdyetton** [comment]
xdf browser seems to have much the same information as pyxdf's return object. 
If the first_timestamp or last timestamp were in local-clock time then that would sort the issue, unfortunatly these are in time since epoch also :(

**Comment by mgrivich** [comment]
> Is this what you are getting at with the chuck ordering @mgrivich? I'm not exactly sure what you mean by chuck, but i'll download that xdf browser and see if that sheds some light.

Chunks are pieces of data in the file. As data comes in, the xdf reader saves it to disk in chunks. Each chunk comes from one stream, and they are saved in the rough order of when the data was acquired.

The every 5.25 second offset samples are used to determine the offset between the two streams (in time-since-startup) and is not the limiting factor here. 

The limit on determining epoch time is how frequently eeg data is saved and the difference in latency between eeg data being saved and video data being saved.

**Comment by mgrivich** [comment]
Yes. Also, you can do it multiple times, for each video marker/eeg chunk pair to get multiple measurements.

You can calculate average +/- standard deviation/sqrt(N) to get an estimate of how accurate your hack is. 100 ms was an educated guess, so don't take it too seriously. 

Then load the data with load_xdf the normal way, and subtract/add this measured value to put the two streams in approximately the same time base.

**Comment by bdyetton** [comment]
Excellent! Thanks!! 
If you don't mind, I'll keep this issue open until I try that this weekend.

**Comment by tstenner** [comment]
> Find the previous (or next?) EEG chunk, and assume that these occur almost simultaneously (this 100ms error you mentioned?).

LabRecorder pulls samples every 500ms, so in an ideal world you'd have 500ms chunks of EEG data with some video markers inbetween. The start and end times of these chunks next to the marker chunks will give you an estimate of how precise your video markers are.

**Comment by bdyetton** [comment]
Hey guys,
This method worked. Thanks a bunch!!!

**Comment by rschmaelzle** [comment]
Hello, 
i just realized while browsing that this might actually explain the [issue](https://github.com/xdf-modules/xdf-EEGLAB/issues/1#issue-452703339) I ran into today - also trying to show a video (onsets/offset marked via Presentation's LSL triggers before and after) and using 2 Muse systems that were connected using BlueMuseApp. Is there any information to this? First thing I will do tomorrow is trying to see if Bluemuse contains settings for how time is communicated over the LsLLayer. if anyone has immediate tips, they will be appreciated since I have only a general understanding about how this all works, but lack details.
Best, ralf.

**Comment by bdyetton** [comment]
Hi Raff,
Your best bet is to not use epochtime as your timing marker in bluemuse.
There is an arg for that. I'll double check when I get back to my computer.

**Comment by bdyetton** [comment]
Yep, change the bluemuse "primary timestamp" settings to LSL native and give it a test.

**Comment by rschmaelzle** [comment]
Hi @bdyetton , thank you very much - awesome help! That did it! I am closing this and will  reference it over at the xdf-repository. All the best, Ralf
