### ISSUE TITLE
ReceiveVideo app

### ISSUE THREAD

**Issue by syedahmar** [sccn/labstreaminglayer#135]
Hi there, I have searched around but was not able to find any example or solution to this issue. I am trying to capture webcam stream (have a logitech webcam connected to USB). I am running the "receivevideo" application which just says "Now waiting for a stream with type='VideoRaw'... 
How do I redirect my webcam to start sending streaming? Do we need another application in parallel ? Of course no stream is showing up in Lab Recorder. 
Any pointers please?

**Comment by dmedine** [comment]
Receive Video is a data receiving program, not a data sending one. I 
think what you need is VideoStream, which you will find in 
Apps/EmbarcaderoXE/bin

**Comment by syedahmar** [comment]
Thanks a lot, this works!
