### ISSUE TITLE
problem with inlet.pull_sample();

### ISSUE THREAD

**Issue by roberto9110** [sccn/labstreaminglayer#14]
When I call the sample through Matlab, Matlab remain busy and it is not possible to acquire the sample. I do not why.

**Comment by agricolab** [comment]
A common cause for that issue is that the outlet is created yet, but has not yet send any data. Can you verify whether the outlet is actually sending data? One option is to test this with the examples.

**Comment by roberto9110** [comment]
I verified. I connected the amplifier (BP ACTICHAMP) to its own official software and it works without problem.

In Matlab, with LSL I have this issue (not everytime). I open the connection, but it does not acquire any sample without an apparent reason

**Comment by agricolab** [comment]
Please specify what official software you mean. BrainVision Recorder does not natively stream the data in LSL format. It can be set to stream in RDA, which can be republished as LSL stream. Alternatively there are  low-levels app to directly stream the data from the amplifier as LSL. It is unclear, what you are using to stream.

You can test the ability to detect and receive streams on your machine, using the examples, e.g. https://github.com/labstreaminglayer/liblsl-Matlab/blob/4fd9b7dcc3966d047aa36c6b600286516ff03b89/examples/SendData.m. and https://github.com/labstreaminglayer/liblsl-Matlab/blob/4fd9b7dcc3966d047aa36c6b600286516ff03b89/examples/ReceiveData.m

**Comment by kcsaba12** [comment]
I would like to underline the problem.

I just received a brand new actichamp from BrainProducts. I wanted to get the signals real time with the pylsl protocol. I downloaded the ActiChamp.exe from ftp://sccn.ucsd.edu/pub/software/LSL/Apps/ and clicked on the run button.

For signal receiving I used the following code:
`from pylsl import StreamInlet, resolve_stream

# first resolve an EEG stream on the lab network
print("looking for an EEG stream...")
streams = resolve_stream('type', 'EEG')

# create a new inlet to read from the stream
inlet = StreamInlet(streams[0])
info = inlet.info()
print(info.as_xml())

while True:
    # get a new sample (you can also omit the timestamp part if you're not
    # interested in it)
    sample, timestamp = inlet.pull_sample()
    print(timestamp, sample)`

I got the following result:
`looking for an EEG stream...
<?xml version="1.0"?>
<info>
	<name>ActiChamp-0</name>
	<type>EEG</type>
	<channel_count>75</channel_count>
	<nominal_srate>500</nominal_srate>
	<channel_format>float32</channel_format>
	<source_id>ActiChamp_0</source_id>
	<version>1.1000000000000001</version>
	<created_at>1796.635882414</created_at>
	<uid>44429e30-2a68-4bb6-9b45-9f0151026907</uid>
	<session_id>default</session_id>
	<hostname>LAPTOP-TDB9DF2S</hostname>
	<v4address />
	<v4data_port>16572</v4data_port>
	<v4service_port>16572</v4service_port>
	<v6address />
	<v6data_port>16572</v6data_port>
	<v6service_port>16572</v6service_port>
	<desc>
		<channels>
			<channel>
				<label>Fp1</label>
				<type>EEG</type>
				<unit>microvolts</unit>
			</channel>

			# many more channels..... removed to make this shorter

		</channels>
		<acquisition>
			<manufacturer>Brain Products</manufacturer>
			<dll_version>420544513</dll_version>
			<driver_version>50594194</driver_version>
			<cypress_version>1746011673</cypress_version>
			<FPGA_version>0</FPGA_version>
			<msp430_version>1762853403</msp430_version>
		</acquisition>
	</desc>
</info>`

Which means for me, that from the StreamInlet the information can be read out and the program stuck right in the `inlet.pull_sample()`

I would like to access the data real-time. Do you have any clue how can it be done? 
I even tried to rebuild the ActiChamp.exe from source but after 4 hours I couldn't make it. I stucked somewhere at the Qt installation and configuration.

**Comment by cboulay** [comment]
Stuff on the FTP is quite old and not under our control. We do not recommend using it if there are alternatives.

Without BrainProducts hardware, I can't test the apps for their devices. @agricolab is right that it sounds like the app has created the stream but has yet to push data to the stream. Is there something else you need to do in the App (maybe a giant Go-LSL! button) to get it to start streaming?

I don't know BrainProducts software well. Does anything on the release page help?
https://github.com/labstreaminglayer/App-BrainProducts/releases

@dmedine Can you comment?

**Comment by kcsaba12** [comment]
Thanks! With the BrainVisionRDA-1.12-msvc2015 I could access the data realtime! 
I couldn't find this link through the web first.

**Comment by dmedine** [comment]
Yeah, the interface is a little buggy. I will try to clean it up when I get some extra time.

**Comment by dmedine** [comment]
I will also be releasing a new tool for interfacing actiCHamp with LSL in the next few weeks. This will allow you to access the data in realtime very easily.

**Comment by cboulay** [comment]
@dmedine 
I'm doing a little issue cleanup. Please reopen this issue if you think it isn't solved.

**Comment by kcsaba12** [comment]
@dmedine
Have you created te new tool for interfacing actiCHamp with LSL? I could not find it.
