### ISSUE TITLE
android successfully add liblslAndroid.so  but after run it show error

### ISSUE THREAD

**Issue by c51413day** [sccn/labstreaminglayer#141]
![image](https://cloud.githubusercontent.com/assets/22654682/19144166/a8513f28-8bda-11e6-8f03-f7d6aaed3539.png)

what can I do and let it success?
thx

**Comment by mgrivich** [comment]
What development environment are you using? What procedure are you using to build the app?

**Comment by c51413day** [comment]
development environment is android studio 2.2

I use liblsl-android-1.11 what this provides information

Step1 begin new project and step same path (edu/ucsd/scan/)

Step2 add main code sendstringmarkers (edu/ucsd/scan/SendStringMarkers/SendStringMarkers.java)

Step3 add library lsl
(edu/ucsd/scan/lsl/*)

Step4 add liblslAndroid.so library
The method is .so to make .jar ( the jar content is /lib/armeabi/liblslAndroid.so) and to add in project (where /libs/armeabi.jar)

Step5 run app

**Comment by c51413day** [comment]
I think whether it is that my path sets up wrong

Result in doesn't find the C  code

but the path (edu/ucsd/sccn/) is wrong?

Isn't in c code JNICALL Java_edu_ucsd_sccn_lsl_lslAndroidJNI_new_vectorstr__SWIG_1?

**Comment by mgrivich** [comment]
I suspect you are using the wrong liblslAndroid.so.  You can either build it yourself from the instructions at  https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Android or you can try one I just built for you at ftp://sccn.ucsd.edu/pub/mgrivich/liblslAndroid.so

**Comment by c51413day** [comment]
thank you so much , but the liblslAndroid.so is from ftp://sccn.ucsd.edu/pub/software/LSL/SDK/liblsl-Android-1.11.zip  ..Orz

OK!This problem has already been solved 

Now I have new  problem ↓

![image](https://cloud.githubusercontent.com/assets/22654682/19205040/95efe22e-8d12-11e6-80d4-ab0debc1baec.png)

SendStringMarkers.java code is from  ftp://sccn.ucsd.edu/pub/software/LSL/SDK/liblsl-Android-1.11 

I have not done any change 

what is mean and How to solve ?

**Comment by mgrivich** [comment]
This one is less obvious. Usually errors like this occur when a native function mishandles memory or has some other critical error. Try commenting out lines of java code to discover exactly which line causes the crash.

**Comment by c51413day** [comment]
OK! thx
i discover this line "outlet.push_sample(sample);" causes the crash.

**Comment by c51413day** [comment]
i discover this line "lslAndroidJNI.stream_outlet_push_sample__SWIG_5(swigCPtr, this, vectorf.getCPtr(data), data);" causes the crash. this function is to do call c , so what can i do that solve this problem?

please help me and Thank you for  help

**Comment by mgrivich** [comment]
Please check that your manifest has internet permissions enabled:
`<uses-permission android:name="android.permission.INTERNET" />`
as shown by https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Android/SendStringMarkers/AndroidManifest.xml

**Comment by c51413day** [comment]
I am very stupid to unexpectedly forget to set up the network .. Thank you
Now；
I connect computer and mobile phone to the same regional network (I confirm that computer and phone can  Ping each other )
open app
Then 
Open openvibe (openvibe-acquisition-server.cmd)
it can't find data out from the mobile phone 

(In fact ,I have tried this (openvibe-acquisition-server.cmd) and is used in other devices (e.g. other computer ). .I allow the fire wall So .It is successful)

![image](https://cloud.githubusercontent.com/assets/22654682/19312654/fa66deea-90c5-11e6-93dc-95a05487d20e.png)
can't find "Signal stream"
`stream_info info = new stream_info("BioSemi","EEG", 1, 100 , channel_format_t.cf_float32 , "myuid324457");`
this my stream_info

Other methods test whether to send out 
or
What have not I set up

**Comment by c51413day** [comment]
Um..The problem was not solved 

than i check network package
use Wireshark→filter address (my phone ip)→open app than check network package→Have not received anything 
(double check ：use phone to PING computer that  Wireshark has received network package)
So The mobile phone (my app) has not sent data 
What have not I set up to lead to that data has not sent
But code doesn't have error and app can run normally
(`outlet.push_sample(sample);` is in my code )

**Comment by mgrivich** [comment]
What happened when you looked for the streams in StreamViewer.exe?

Please verify that your phone and your computer are attached to the same local network. In the IP address the first few blocks of digits should be the same. In your wireless settings on your phone, you should be connected through a wireless network, not LTE or 4G. Instead of ping, try tracert. The number of steps should be very small.

**Comment by c51413day** [comment]
can't find Streams  The option is empty 
![image](https://cloud.githubusercontent.com/assets/22654682/19374514/c4338622-91fe-11e6-8d87-aef481a1c6eb.png)
So I suspect the mobile phone (my app) has not sent data
My phone and computer are the same local network that I have confirmed

**Comment by mgrivich** [comment]
Try turning off the firewall on the receiving computer.

**Comment by c51413day** [comment]
I discovery that if computer use Wireless network, StreamViewer can't find Streams
But computer use Wired network ,it can find Streams
Wired network and Wireless network both are attached to the same local network.
Thank you for your help ~
