### ISSUE TITLE
LabRecorder on MAC

### ISSUE THREAD

**Issue by roberto9110** [sccn/labstreaminglayer#145]
Hi,
I need the App LabRecorder on Mac.
Anyone can compile it? 
I do not have the skills to do it 🤓 
Thanks!!!

Roberto

**Comment by cboulay** [comment]
Which is preferred, cmake or qmake?

**Comment by roberto9110** [comment]
cmake

**Comment by roberto9110** [comment]
cmake
THANKS!!!!


________________________________
Da: Chadwick Boulay <notifications@github.com>
Inviato: venerdì 28 ottobre 2016 15.41
A: sccn/labstreaminglayer
Cc: roberto9110; Author
Oggetto: Re: [sccn/labstreaminglayer] LabRecorder on MAC (#145)


Which is preferred, cmake or qmake?

-

**Comment by cboulay** [comment]
See #147

**Comment by cboulay** [comment]
Closing with merger of #147
