### ISSUE TITLE
Include msgpack as dependency

### ISSUE THREAD

**Issue by papr** [sccn/labstreaminglayer#148]
Dear LSL community,
I am currently working on updating the _Pupil Pro_ app.

The newest version of Pupil Labs Capture uses [`msgpack`](http://msgpack.org/) to serialize its data. This means I would need to add `msgpack` as a dependency. I saw that you provide a ftp server for third-party dependencies. What is the procedure to add new dependencies to this ftp server?

I would also need help with integrating this dependency into the `deps_worker.py` file.

Thank you very much for your help!

Warm regards,
Pablo

**Comment by dmedine** [comment]
I guess we also need to update the PupilPro app to conform to Pupil-labs 
updates. I heard somewhere that they are going to start putting LSL into 
their server software natively, so in the future, this shouldn't matter.

As far as adding dependencies to the ftp, that requires that someone 
with access privileges to the server that it is hosted on (e.g. me) to 
make the upload. Then, the get_deps.py script needs to be updated to 
reflect the new dependency.

I am swamped with other things at the moment, but later this week I will 
try to take a look at this and see what is the best way to go about it. 
I will also reach out to pupil labs and see what the status is for them 
to incorporate LSL directly.

**Comment by papr** [comment]
I am working for Pupil Labs. There are currently no plans to integrate LSL natively into Capture. But you are right. It makes way more sense to write a small python script that relays the server data using the LSL python bindings instead of changing the Pupil Pro QT app.

This should make it easy to integrate into other software.

**Comment by dmedine** [comment]
Awesome! Good to know you, Pablo.

Let me know if there is anything I can do  to help. Actually, my 
original idea was to simply add LSL to the Pupil Labs code (since it is 
open source) but I decided against this for some reason (it was 2 years 
ago).

I seem to remember that a researcher recently contacted me and told me 
that Pupil Labs was already doing this. I guess I am mis-remembering or 
else was misinformed.

**Comment by papr** [comment]
We decided to go with your original idea to integrate LSL natively. We created a plugin that only needs the LSL Python bindings to be installed as dependency. See  #149.
