### ISSUE TITLE
Unhelpful error message when building without checked out submodules

### ISSUE THREAD

**Issue by riftguardian** [sccn/labstreaminglayer#15]
Hello, I have two questions.

I tried building LSL according to BUILD.md, and ran into the following error when attempting to configure using
cd build
cmake-gui

led to the following in CMake:
>Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
The CXX compiler identification is MSVC 19.16.27025.1
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done

>CMake Error at CMakeLists.txt:7 (add_subdirectory):
  The source directory
  >  C:/Users/RiftKun/Repos/labstreaminglayer-master/LSL/liblsl
  does not contain a CMakeLists.txt file.

>CMake Error at CMakeLists.txt:15 (include):
  include could not find load file:
>    LSLCMake

>CMake Error at CMakeLists.txt:22 (LSLGenerateCPackConfig):
  Unknown CMake command "LSLGenerateCPackConfig".
>Configuring incomplete, errors occurred!
See also "C:/Users/RiftKun/Repos/labstreaminglayer-master/build/CMakeFiles/CMakeOutput.log".

I also tried MSVC 2017 with CMake and received the following error:
>1> Command line: c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\RiftKun\CMakeBuilds\f2af7fce-6c7b-963a-85da-4f3686ef0529\install\x64-Debug (default)"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "C:\Users\RiftKun\Repos\labstreaminglayer-master"
1> Working directory: C:\Users\RiftKun\CMakeBuilds\f2af7fce-6c7b-963a-85da-4f3686ef0529\build\x64-Debug (default)
1> -- Configuring incomplete, errors occurred!
1> See also "C:/Users/RiftKun/CMakeBuilds/f2af7fce-6c7b-963a-85da-4f3686ef0529/build/x64-Debug (default)/CMakeFiles/CMakeOutput.log".
1> CMake Error at C:\Users\RiftKun\Repos\labstreaminglayer-master\CMakeLists.txt:7 (add_subdirectory):
1>   The source directory
1> 
1>     C:/Users/RiftKun/Repos/labstreaminglayer-master/LSL/liblsl
1> 
1>   does not contain a CMakeLists.txt file.
1> 
1> 
1> CMake Error at C:\Users\RiftKun\Repos\labstreaminglayer-master\CMakeLists.txt:15 (include):
1>   include could not find load file:
1> 
1>     LSLCMake
1> 
1> 
1> CMake Error at C:\Users\RiftKun\Repos\labstreaminglayer-master\CMakeLists.txt:22 (LSLGenerateCPackConfig):
1>   Unknown CMake command "LSLGenerateCPackConfig".
1> 
1> 
1> c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\RiftKun\CMakeBuilds\f2af7fce-6c7b-963a-85da-4f3686ef0529\install\x64-Debug (default)"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "C:\Users\RiftKun\Repos\labstreaminglayer-master" returned with exit code: 1
CMake Error at CMakeLists.txt:7 (add_subdirectory):
  The source directory
    C:/Users/RiftKun/Repos/labstreaminglayer-master/LSL/liblsl
  does not contain a CMakeLists.txt file.
CMake Error at CMakeLists.txt:15 (include):
  include could not find load file:
    LSLCMake
CMake Error at CMakeLists.txt:22 (LSLGenerateCPackConfig):
  Unknown CMake command "LSLGenerateCPackConfig".

I have both Qt5.12.2 and boost 1.70.0 installed with paths added as "Qt5_DIR" and "DBOOST_ROOT" respectively. Am I missing a step after cloning the LSL repo and creating the build folder, causing the missing CMakeLists.txt error?

Background:
My main purpose with LSL is for recording synchronized eye movements and EEG. Following the tutorials was fine except using vis_stream demonstrated that the MATLAB Viewer from the ftp was out-of-date. I tried using the prebuilt App-MATLABViewer from Git but was missing the liblsl64.dll from liblsl-MATLAB - hence why I tried building LSL.

**Comment by cboulay** [comment]
The repository uses submodules. When you clone it you have to use --recursive, or you'll have to `git submodule init && git submodule update`

**Comment by riftguardian** [comment]
I'm really sorry if that was the likely cause, I'm not used to using
Git/Github. Thank you, I will see if this solves my problems.

**Comment by riftguardian** [comment]
I built the liblsl64.dll file thanks to your help. However, after placing it in liblsl-Matlab/bin I now receive the following error upon running vis_stream() from MATLABViewer:

>Undefined function or variable 'lsl_loadlib_'.
>
>Error in lsl_loadlib (line 65)
    hlib = lsl_loadlib_(dllpath);
>
>Error in vis_stream (line 73)
    lib = lsl_loadlib();

On line 71 of vis_stream() I notice the following:
>try
>    lib = lsl_loadlib(env_translatepath('dependencies:/liblsl-Matlab/bin'));
>catch
>    lib = lsl_loadlib();
>end

Which produces:
>Undefined function or variable 'env_translatepath'.

What am I missing? Further help is greatly appreciated.

**Comment by tstenner** [comment]
For some reason the mex files have to be rebuilt for some configurations. In the liblsl-Matlab folder there's a script called `build_mex.m` that takes care of it. Could you run it and see if it helps?

**Comment by riftguardian** [comment]
I tried running build_mex and received a similar error message:
![Screenshot (227)](https://user-images.githubusercontent.com/48695308/54655137-171ffc00-4a97-11e9-9d7b-006759aa989c.png)

**Comment by cboulay** [comment]
Try changing your working directory (the folder in the long white bar above your editor) to liblsl-Matlab.

**Comment by riftguardian** [comment]
Switching to the liblsl directory in MATLAB worked for using build_mex(), and now I can use vis_stream(). 

Thank you!
