### ISSUE TITLE
How do I fIlter in Real Time (Matlab)?

### ISSUE THREAD

**Issue by roberto9110** [sccn/labstreaminglayer#150]
Hello!
I need to filter signals acquired in real time with LabRecorder. 
Anyone is able to create a script to do this in Matlab in real time?
Thanks
ROberto

**Comment by cboulay** [comment]
Hi Roberto,

What do you mean by 'real time'?

Do you want to filter the signals as they are acquired from the hardware? Then this has nothing to do with LabRecorder.

Or do you want to play-back files that were previously recorded with LabRecorder and filter those?

**Comment by roberto9110** [comment]
I want to send the data in a buffer and i want to filt it (with a latency of 50 ms)

**Comment by cboulay** [comment]
Sorry, but you didn't answer my question. Are you processing data coming from hardware, or are you processing data coming from file playback?

**Comment by roberto9110** [comment]
sorry. from hardware

________________________________
Da: Chadwick Boulay <notifications@github.com>
Inviato: mercoledì 9 novembre 2016 17.47.40
A: sccn/labstreaminglayer
Cc: roberto9110; Author
Oggetto: Re: [sccn/labstreaminglayer] FIltering in Real Time in LabRecorder opened in Matlab (#150)


Sorry, but you didn't answer my question. Are you processing data coming from hardware, or are you processing data coming from file playback?

-

**Comment by cboulay** [comment]
OK so this really has nothing to do with Matlab. You just need to do real-time signal processing on labstreaminglayer streams. I hope you don't mind but I'm going to change the title of the issue to reflect that.

For Matlab, look at the `ReceiveDataInChunks.m` example [here](https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Matlab/examples).
I think BCILAB, a Matlab toolbox, has built-in support for signal processing LSL streams. I've never used that feature, but I think it comes with some pre-made scripts to do some simple things for you.

There is also a Python wrapper and some Python examples.
There is commercial signal processing software (free Community Version) currently in closed beta that uses Python and has native LSL support. See [NeuroPype](http://neuropype.io/). This is what I use.

If this answers your question then please close the issue.

**Comment by dmedine** [comment]
Yes. BCILAB or NeuroPype is what you want.

Otherwise you can roll your own: receive data via LSL with either Matlab 
or Python and then run one of Matlab or Python's many signal processing 
functions on it. You can then push the filtered data back out via LSL. 
You can do this in less than 10 lines of code.

The latency is going to depend on the type filter you use and whether 
you implement the filter as a convolution (computationally efficient but 
higher latency) or using a direct form (low latency, but higher 
computational load).
