### ISSUE TITLE
.exe files

### ISSUE THREAD

**Issue by juanvic5185** [sccn/labstreaminglayer#158]
Hello. I am trying to run the .exe files but they seem missing. I just installed the latest version today. I have tried moving the dll. for the Emotiv and the QtGui4.dll which are the ones I have and the .exe file is present. But when I run them it says that the .dll file is not in my computer. What am I doing wrong?

Juan

**Comment by cboulay** [comment]
You need liblsl.dll and a couple different Qt dlls on your path, or in the
same folder as your exe. These should all be on the ftp if you don't have
them already. Sorry for not supplying more info; on my phone.

**Comment by cboulay** [comment]
Juan, I assume this issue is resolved so I'm closing the issue on GitHub. Feel free to re-open if you're still having trouble.
