### ISSUE TITLE
Empty folders?

### ISSUE THREAD

**Issue by minseee** [sccn/labstreaminglayer#17]
For some reason, all the folders are showing up empty. 
labstreaminglayer-master---->LSL------>liblsl 
and the liblsl folder has nothing in it. I turned off Windows firewall for private networks and still nothing?

Any clue as to what's going on?

**Comment by sheinke** [comment]
You probably only cloned the super-repository (github.com/sccn/labstreaminglayer). In order to actually get the liblsl code, you need to insert the contents of github.com/sccn/liblsl/tree/master into the subfolder labstreaminglayer-master/LSL/liblsl.

**Comment by agricolab** [comment]
https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by tstenner** [comment]
Also: https://github.com/sccn/labstreaminglayer/blob/master/doc/Working-with-the-repository.md#git-cookbook ("Check out a single submodule")

**Comment by cboulay** [comment]
Closing because I'm almost certain this issue is solved by one of the above answers. Thanks for all your help everyone!
