### ISSUE TITLE
RecorderLib64.dll file missing

### ISSUE THREAD

**Issue by bmh2127** [sccn/labstreaminglayer#174]
Trying to open lab recorder in windows but receiving an error that the library file doesn't exist.

**Comment by bmh2127** [comment]
Can anyone provide the file?

Thanks!

**Comment by dmedine** [comment]
Which version of labrecorder are you using? Did you download binaries from the ftp server, or are you building it from source?

**Comment by bmh2127** [comment]
Irrespective of the version that I tried, any attempt to launch the labrecorder.py script resulted in an error importing the recorder library along with a message like %1 Is Not a Valid Win32 Application. I attempted to load an old version which lead to the message of missing the dll file, which was missing from the directory. I am not very experienced with windows. Would you suggest I try to rebuild using the master code?

**Comment by cboulay** [comment]
@bmh2127 RecorderLib64.dll and labrecorder.py are only part of old LabRecorder. New LabRecorder does not require either of those things. So yes, rebuild from master.

Where did you find the LabRecorder you are currently attempting? Were there any instructions that led you to it that need to be updated?

**Comment by dmedine** [comment]
Also, if you are using python 3, everything will fail. You need to use python 2.7. 

I cannot verify that the older versions of LabRecorder (python based versions) are working properly (thanks to a Windows 10/pip bug which prevents me from installing Qt libraries for python: https://github.com/pypa/pip/issues/2748), but they should be. Also, if you want to run a completely rock solid version of LabRecorder on Windows, please get the latest release from the SCCN ftp:
ftp://sccn.ucsd.edu/pub/software/LSL/Apps/LabRecorder-1.12c.zip

**Comment by bmh2127** [comment]
Thank you! I will try your suggestion.
