### ISSUE TITLE
How to put in specific local IP address?

### ISSUE THREAD

**Issue by yryun** [sccn/labstreaminglayer#18]
I'm working on python - python communication.

I successfully tested two python process communication with my local environment.

https://github.com/sccn/labstreaminglayer/wiki/Tutorial-6:-Network-mode

I checked ping test successfully with two machine but I can't reach through pylsl.

Is it possible to put in specific local IP to match process through pylsl?

**Comment by cll008** [comment]
Have you checked this page?
https://github.com/sccn/labstreaminglayer/wiki/NetworkConnectivity#defining-the-local-laboratory

**Comment by cboulay** [comment]
Hi @yryun . I am going to assume that you followed the advice in the Wiki and you have solved your problem. If not then please feel free to reopen this issue.
