### ISSUE TITLE
How to get or compile Matlab binary

### ISSUE THREAD

**Issue by Jianbin-IBM** [sccn/labstreaminglayer#180]
Hi,

I didn't find any binary file in /LSL/liblsl-Matlab/bin/
May I know how to compile or download binary file for Matlab? Sorry if it is too basic...
Thank you!

**Comment by cboulay** [comment]
From the root labstreaminglayer directory run `python get_deps.py`. This will download binaries from the ftp into different locations in the repository.

**Comment by tstenner** [comment]
Could you try https://bintray.com/labstreaminglayer/LSL/download_file?file_path=liblsl-matlab-win64.7z ?
