### ISSUE TITLE
Return value of local_clock()

### ISSUE THREAD

**Issue by sandymacpherson** [sccn/labstreaminglayer#184]
I'm trying to get an absolute timestamp for the LSL samples but the value returned is strange, I'm not sure exactly what it represents. I have a python script that simply prints out the result of `local_clock()` and this prints `656411.840731`. Running a few times, this value increments in what look like seconds. If it's seconds, then the number above is about 8 days which doesn't correspond to my system uptime (27 days, Macbook Pro laptop).

I looked at the C source and I see this:

`LIBLSL_C_API double lsl_local_clock() { 
	return boost::chrono::nanoseconds(boost::chrono::high_resolution_clock::now().time_since_epoch()).count()/1000000000.0; 
}`

According to [this](http://www.cplusplus.com/reference/chrono/duration/count/), `count()` returns the number of periods, not seconds, and this is perhaps accounting for my confusion here.

Could you clarify what the local_clock() is returning and perhaps suggest how I can go about getting it in absolute timestamp form (as in a simple unix timestamp)? I have a workaround that stores the unix timestamp when my program starts and just makes everything relative to that, but that introduces an unknown but constant offset in all the data.

Thanks!

**Comment by mgrivich** [comment]
lsl_local_clock typically shows system uptime in seconds. 
lsl_local_clock is a wrapper around a platform-dependent high resolution 
system clock. There is no magic here. You can test this by restarting 
your computer. I'm not sure why your Macbook is reported a different 
time for uptime (with the uptime shell command?). Perhaps something 
reset the lsl_clock, but not uptime, such as closing your Macbook but 
not restarting it.

**Comment by sandymacpherson** [comment]
Thanks for the info. I did use the shell command 'uptime' to get the value, but I'm unsure of complications such as laptop sleeping etc on the timing. The main thing I wanted to know was whether local_clock() dealt in relative or absolute time, and that is now clear.

Thanks!
