### ISSUE TITLE
Net Standard / Universal Windows Platform Store App support

### ISSUE THREAD

**Issue by vpenades** [sccn/labstreaminglayer#187]
Hi, we have a NET windows desktop application that uses LSL, and we're planning to make it cross platform.

Right now we're using the LSL Net wrapper that binds to the Win32 LSL binaries. But these can only be used on Windows desktop platform.

We would like to support Universal Windows Platform Store Apps too, for wich specifically built for UWP binaries would be required.

But the right approach would be to have a common Net.Standard wrapper for all platforms, and specific low level binaries for each platform.

NuGet package maybe?

thanks in advance

**Comment by cboulay** [comment]
>and specific low level binaries for each platform

Sorry, in the context of your post I can't figure out what you mean by "low level" here. Can you please provide more details or some links?

**Comment by vpenades** [comment]
Well, I understand that LSL is essentially a communication protocol, which, under the hood, uses sockets for data transmission, that's the low level code.

Since the current LSL port for .Net is a wrapper over the Win32 binaries (the low level), in order to support more Net platforms, you would need something like this:

Net Wrapper for windows desktop => LSL win32 binaries
Net Wrapper for android                => LSL Android binaries
Net Wrapper for UWP                    => LSL UWP binaries

But maybe, it could be possible to write a net wrapper, using Net.Standard framework, that could target all the binaries on all platforms.

Alternatively, I don't know how hard would be to write a pure managed LSL library using just Net.Standard, because that way it would be cross platform straight away.

**Comment by cboulay** [comment]
In its current form, does the Net wrapper code really need to be different for different platforms? That's unfortunate. I had been thinking about it sort of like the Python wrapper: write for Python, not a platform. (Full disclosure: there is some platform-specific code in the Python wrapper for getting the correct name of the dll/dylib/so file)

I would of course agree that writing a Net wrapper that works cross-platform is better than writing a Net wrapper for each platform.

>Alternatively, I don't know how hard would be to write a pure managed LSL library using just Net.Standard, because that way it would be cross platform straight away.

I've used pure cross platform .Net/Mono things in the past and, without exception, in each instance I would have preferred if there was a C-API. I think LSL's CAPI has to stay. If it stays, then I don't see it being a good idea to rewrite LSL in another language. Of course if someone wants to do that on their own then there is nothing stopping them, as long as they follow the terms of the license, but I don't see that happening in this repository. But if the CAPI is staying, and if it's the one that is most maintained, then I think the best Net library would be a wrapper around the CAPI.

**Comment by dmedine** [comment]
I don't see how LSL could be written in anything but C++ because pretty 
much every piece of it that is involved in data transmission is using 
boost::asio (which is a C++ library).

**Comment by vpenades** [comment]
@cboulay your code is fine, and can be reused across multiple platforms, as long as there's the counterpart C-API binaries available.

As of now, I think the only C-API binaries available that can be p/invoked by the net wrapper are the ones compiled for Win32 x86/x64, which are the ones we have used in the past.

@dmedine I agree it would be too much work to have a pure managed implementation, and it's best to keep with the CAPI.

But then, in order to be able to use the Net Wrapper on the new xamarin platforms, we need new CAPI binaries for:
UWP: x86, x64 and ARM
Android
iPhone

That is... even if UWP is "windows", it is a completely independent sandboxed environment, you cannot use the current win32 binaries, you need binaries compiled specifically for UWP, and that can also include ARM architecture (win32 doesn't support it)

**Comment by dmedine** [comment]
Can you not build these yourselves? It's been a long time since anyone 
paid much attention to the iPhone project, but Android is pretty 
actively maintained and the other 3 are just a couple of switches in 
Visual Studio.

I don't have any Mac anymore, so I'm unable to help with ios, but if you 
really need me to generate those Windows binaries, I can do it. I have 
no idea about android, tho... sorry.

Cheers,

David

**Comment by vpenades** [comment]
We're not in a hurry to port them now, we've just started porting our code to cross portable .Net code (AKA .Net.Standard) so we're doing a cautionary review of the third party libraries that might require extra work.

At some point we'll visit again LSL and depending on our constraints we might be able to expend some time to do what's needed to make it run on UWP... or just move on.

I am aware that UWP is not the most interesting platform to support LSL in terms of research labs, but as it happens, Microsoft is pushing agressively to support UWP, and there's some key present and future hardware devices that will only be available on UWP.

**Comment by cboulay** [comment]
If LSL doesn't build for UWP then I think that's something that we can help you with. As David said, it should already build for Android and it did at some point build for iOS.

If you discover something you need is missing or is broken with the .Net wrapper then we can help you with that too. I suspect it's missing the sync changes that came with LSL 1.12. There might be others.

**Comment by mgrivich** [comment]
The underlying library is C++, so it can be compiled on any system that 
has a C++ compiler and networking support. We have projects that support 
Windows, Mac, iOS, and Android. However, they are not part of .NET or 
UWP. If you want to do such a project, I can give you advice, but I 
doubt any of us would take the time to create for you a pre-packaged 
solution along these lines.

**Comment by cboulay** [comment]
So I just had a go at building for UWP. I installed the Windows SDK and the Windows Desktop SDK. LSL already has a cmake setup so it was trivial to make a project for UWP: `cmake .. -G "Visual Studio 14 2015" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0`. I opened the project and selected the liblsl target.

Unfortunately, it failed on 80 errors during compiling LSL-provided boost.

After a bit of reading, it seems like boost::asio was not supported at some point because it used banned Win32 APIs, but maybe now it works (this wasn't entirely clear). I think old boost code (like the boost that LSL provides and uses) probably will never work with UWP. Even though LSL's cmake system provides an option to use system boost instead of the provided boost, this doesn't actually work.

If anyone manages to remove LSL's dependency on its custom boost lib, and if LSL depends on any boost libs that are not header-only, and if all of the boost modules are supported by UWP, then someone wishing to build LSL for UWP will have to first build boost for UWP, and tell LSL to use that custom-built boost.

**Comment by dmedine** [comment]
There's an option to compile LSL against any boost version, but I forget 
exactly what the magic words are. Also, It is a chore, but there is a 
python script to 'lsl-erize' any boost. I don't know if anyone has tried 
this for a while, though. I think the boost that sits in with LSL is 
1.56 or 1.57. They are up to 1.63 now.

The other thing is that boost libraries slowly make their way into C++ 
standard libraries. I don't know if boost::asio will ever go there, but 
it should. It is super cool.

**Comment by vpenades** [comment]
Well, as I said, we don't require LSL support right now, but maybe in 6 months from now. So when the time arrives we will review again the state of things and what choices do we have.

At least I am happy to have let you be aware of the issue compiling LSL for UWP.

**Comment by tstenner** [comment]
With the current lslboost version in PR #237 LSL compiles without any (additional) warnings with the configuration flags mentioned by @cboulay.
You can find the [resulting build](https://dl.bintray.com/tstenner/labstreaminglayer/:LSL-x64-Release-UWP.7z) on Bintray, please let me know if it works for you.
