### ISSUE TITLE
Can not connect to FTP server

### ISSUE THREAD

**Issue by Manuelbn** [sccn/labstreaminglayer#190]
Hello,

I somehow can't connect to the FTP site. Neither the link in the .md file (ftp://sccn.ucsd.edu/pub/software/LSL/) works for me (i just get a connection error),
nor the get_deps.py scripte.
I just over and over again get:

File not copied. IOError: <urlopen error ftp error: TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)>

Does anyone have an idea why this could happen? Has the link for the FTP server maybe been changed?

I am using Windows 10 and accessing the FTP from Europe.

Thanks in advance.

**Comment by cboulay** [comment]
I just tried and the ftp is working (slowly) for me from Ottawa, Canada. I think this is just a temporary issue that will probably resolve itself.

**Comment by Manuelbn** [comment]
Thank you for the fast answer.
I have been having this problem for about 2 weeks.

**Comment by Manuelbn** [comment]
Found the problem. It worked from a different pc so i guess the firewall was blocking something
