### ISSUE TITLE
LSL leaks memory!!!!

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#191]
Truly it is so.

This was first noticed by folks over at SRI who are running ActiChamp at very high sampling rates. It must be that the leak is slow enough that nobody had ever realized it before, but when leaking a few bytes per slice at 50kHz, you can run out of memory pretty fast. 

Basically, what happens is that when you connect an inlet to an outlet, the outlet itself starts to leak memory.

At first I thought that this must be a problem with how the memory is being managed in the connector app. I went through it very carefully and with as much power as the CRT library provides, but could not find the reason. I also stepped through push_sample very carefully and I don't see anything wrong there as well.

So, I a simple cpp program to convince myself whether or not the bug was in the application code, or the library code (see below). It must be somewhere in the library, because this code is air tight, memory wise.

The question now becomes, which library? Is the bug in the implementation of LSL, or the implementation of boost? I have seen a couple of posts about how one can cause continual memory growth (not actually a leak) with boost::asio ([here](http://stackoverflow.com/questions/32258890/c-boost-asio-async-send-to-memory-leak), for example). I would imagine that boost::asio does not have any bugs of this nature. Then again, I would also imagine that LSL doesn't. Nevertheless, here it is.

Here is the code I wrote. If you run this program, open up a task manager, and go to the 'Details' tab, you will see that as soon as you connect to the stream with streamviewer, the memory will start to climb. 

```
#include "../../labstreaminglayer/LSL/liblsl/include/lsl_cpp.h"
#include <stdlib.h>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <vector>
#include <stdlib.h>

int main(void){


	lsl::stream_info info("Simulator", "eeg", 256, 1000, lsl::cf_float32, "saulassig1234");
	lsl::stream_outlet outlet(info);
	
	int chunk_size = 50;

	//std::vector<float> output(256);
	float *output;
	output = (float *)malloc(256*sizeof(float));

	for(int k=0; k<256; k++)
		output[k] = .1;

	while(1){

		outlet.push_sample(output);
		boost::this_thread::sleep(boost::posix_time::milliseconds(1));
	}
	
	//std::vector<std::vector<float>> output(chunk_size,std::vector<float>(256));

	//for(int i=0; i<chunk_size; i++)
	//	for(int k=0; k<256; k++)
	//		output[i][k] = .1;

	//while(1){

	//	outlet.push_chunk(output);
	//	boost::this_thread::sleep(boost::posix_time::milliseconds(50));
	//}


	return 0;

}
```

**Comment by dmedine** [comment]
I should add that before we start to panic, no one has had a problem with this until the SRI folks started running 64 channel outlets at 50kHz for hours at a time. For years now people have had enough memory to accomodate this little bug.

**Comment by mgrivich** [comment]
I expect the issue is with the core LSL library, not boost. We found and 
fixed a similar problem with string data a while back.

**Comment by sanchezdanj** [comment]
Thanks for opening this issue, David. 

We're extremely motivated to get real-time data out of our actiChamp, so we're happy to collaborate in any way possible to help get this fixed. Including poking at libraries if necessary.

**Comment by dmedine** [comment]
Please, have at it. I would go nuts on this if I had the time. As I say, 
I think there might be a dangling asio process somewhere in the mix, but 
who knows. Things like this are super hard to track down.
