### ISSUE TITLE
unable to link BrainAmpSeries 

### ISSUE THREAD

**Issue by minseee** [sccn/labstreaminglayer#20]
I'm assuming the issue is with the drivers because the device is turned on and plugged in. How do I make sure that the driver is installed correctly? 

But this is the error message I get when I try to link after opening the BrainAmpSeries Connector: 
XXXCould not initialize BrainAmpSeries interface: Could not open USB device. Please make sure that the device is plugged in, turned on, and that the driver is installed correctly. (driver message: could not retrieve error message because the device is closed)XXX

**Comment by cboulay** [comment]
Can you please post your issue in the [BrainAmpSeries repo](https://github.com/labstreaminglayer/App-BrainAmpSeries)?
