### ISSUE TITLE
Precompiled LabRecorder for Ubuntu or Windows? 

### ISSUE THREAD

**Issue by roshkins** [sccn/labstreaminglayer#202]
I tried building it myself and its not working. I'll keep trying, but I figured maybe someone else has done it. I will add it to the repository so no one else has to ask.

**Comment by dmedine** [comment]
Are you using the shell script to build? I'm sure there are some paths and environment variables that need to be correctly configured for all that to work. As far as Windows, if you follow the instructions here https://github.com/sccn/labstreaminglayer/blob/master/Apps/APP%20BUILD%20ENVIRONMENT.txt you should be good to go.

**Comment by cboulay** [comment]
Any objections to me merging #147 ? That should make it easier.

**Comment by roshkins** [comment]
I followed all the instructions for building on Windows, I got an error in
the Python script and visual studio 2008 express couldn't find the files in
the build log. I'll pull up the errors.

**Comment by cboulay** [comment]
I just merged. `git fetch && git pull` then follow the instructions [here](https://github.com/sccn/labstreaminglayer/blob/master/Apps/LabRecorder/readme.txt).

**Comment by roshkins** [comment]
Here's my buildlog, rename to BuildLog.htm to read in browser.
[BuildLog.htm.txt](https://github.com/sccn/labstreaminglayer/files/1099804/BuildLog.htm.txt)

And the python script output
[get_deps.txt](https://github.com/sccn/labstreaminglayer/files/1099820/get_deps.txt)

seems to have many errors

**Comment by roshkins** [comment]
ftp://sccn.ucsd.edu/pub/software/LSL/Apps/LabRecorder-1.12c.zip seems to be compiled for windows. Was hard to find. I'm going to add it to the wiki entry.

No objections on the merge @cboulay
