### ISSUE TITLE
FTP dont work

### ISSUE THREAD

**Issue by lskovboimotions** [sccn/labstreaminglayer#211]
The link to FTP on:
https://github.com/sccn/labstreaminglayer/wiki/Downloads.wiki
dont work:
ftp://sccn.ucsd.edu/pub/software/LSL/

**Comment by dmedine** [comment]
Sometimes the server goes down temporarily for repairs. The link is 
good. I just navigated there from the downloads wiki.

**Comment by cboulay** [comment]
Confirmed the link is working for me too.
