### ISSUE TITLE
Partial specialization error with GCC 6.3

### ISSUE THREAD

**Issue by tstenner** [sccn/labstreaminglayer#212]
On Ubuntu 17.04 with GCC 6.3 and Boost 1.62 compilation of liblsl fails:
<pre><code>/usr/bin/c++   -Dlsl_EXPORTS -ILSL/liblsl -O3 -DNDEBUG -fPIC -fvisibility=hidden -MD -MT LSL/liblsl/CMakeFiles/lsl.dir/src/legacy/legacy_abi.cpp.o -MF LSL/liblsl/CMakeFiles/lsl.dir/src/legacy/legacy_abi.cpp.o.d -o LSL/liblsl/CMakeFiles/lsl.dir/src/legacy/legacy_abi.cpp.o -c LSL/liblsl/src/legacy/legacy_abi.cpp
In file included from /usr/include/boost/container/detail/flat_tree.hpp:29:0,
                 from /usr/include/boost/container/flat_set.hpp:29,
                 from LSL/liblsl/src/legacy/../send_buffer.h:5,
                 from LSL/liblsl/src/legacy/../tcp_server.h:13,
                 from LSL/liblsl/src/legacy/../stream_outlet_impl.h:4,
                 from LSL/liblsl/src/legacy/legacy_abi.cpp:2:
/usr/include/boost/container/detail/pair.hpp:433:8: error: partial specialization of ‘struct boost::is_enum<std::pair<_T1, _T2> >’ after instantiation of ‘struct boost::is_enum<std::pair<double, bool> >’ [-fpermissive]
 struct is_enum< ::std::pair<T, U> >
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
</code></pre>

Clang doesn't complain about it (yet?) and `-fpermissive` lets GCC accept it, so we could add that to the compilation flags until we find a permanent solution.

**Comment by dmedine** [comment]
It will be best to exclude legacy_abi from any non-Windows project since it only applies there and it tends to wreak all kinds of havok with GCC and other compilers.

**Comment by tstenner** [comment]
I've excluded them from the pull request but the problem also appears in some other files. Including `flat_set.hpp` before using the specializations makes GCC happy, so I prepared a PR for this (#214).

**Comment by mgrivich** [comment]
Yes, -fpermissive is required for gcc compilation. This has been true for a while. Gcc is the most finicky compiler. The alternative solution is to edit the source to get gcc to compile with the flag off, but I hesitate to do that for working code.

**Comment by mgrivich** [comment]
I just read tstenner's last comment. Yes, that fix is fine if it removes the necessity for -fpermissive.

**Comment by cboulay** [comment]
@mgrivich , I take it that you're happy with the changes in #214? If so then you can go ahead and merge or just tell me and I will do it.
