### ISSUE TITLE
libsls32.dll not found in Unity3D C#

### ISSUE THREAD

**Issue by mariusrubo** [sccn/labstreaminglayer#215]
Hello, 

I am trying to receive a stream from LSL in Unity 3D. However, I keep getting the following error: 

> DllNotFoundException: liblsl32.dll
> LSL.liblsl.resolve_stream (System.String prop, System.String value, Int32 minimum, Double timeout) (at Assets/LSL.cs:459)

The liblsl32.dll file is in my project's Asset folder. I have tried this with both liblsl_1.10 and liblsl_1.11, and both with the liblsl32.dll and the liblsl64.dll (after adapting libname in LSL.cs), and always get this error message. 

Does anyone have an idea what the problem might be? Does this perhaps have something to do with Unity only supporting DLLs up to .NET2.0?

Best, 
Marius

**Comment by cboulay** [comment]
Hi Mario,

Have you had a look at [LSL4Unity](https://github.com/xfleckx/LSL4Unity)? It provides working dll's in the correct folder structure and it has some small changes to the C# wrapper to make it more Unity-friendly.

I actually tried to get LSL4Unity working with the latest liblsl (1.12) and it worked for me and the plugin's author but not everyone. We didn't isolate the problem, but it might have something to do with the build configuration of the dll's that came from the ftp were incompatible with the user's machine. That might also be the case for you but with this older dll. See the discussion [here](https://github.com/xfleckx/LSL4Unity/issues/15).

**Comment by mariusrubo** [comment]
Thank you for your quick response!
However, LSL4Unity did not resolve the problem for me. 

When using the liblsl32.dll, I get this error code: 

> Failed to load 'Assets/LSL4Unity/lib/liblsl32.dll', expected x64 architecture, but was x86 architecture. You must recompile your plugin for x64 architecture.

So it sounded reasonable to try the liblsl64.dll (and changing the name accordingly in lsl.cs). However, then I get this error: 

> Failed to load 'Assets/LSL4Unity/lib/liblsl64.dll' with error 'Das angegebene Modul wurde nicht gefunden.'.

Would you still recommend installing the 2008 Redistributables as suggested in the linked discussion, or is there maybe another approach that could be worth trying?

**Comment by cboulay** [comment]
I think your best bet is to start with a fresh Unity project, follow the instructions on the LSL4Unity readme/wiki, then report the error there on its issues page. Markus is more skilled at troubleshooting DLL problems than I am. (And I think he might be German so he'll understand your error messages better)

**Comment by mariusrubo** [comment]
Ok thanks, I'll do that!

**Comment by cboulay** [comment]
Closing here in favour of https://github.com/xfleckx/LSL4Unity/issues/15
