### ISSUE TITLE
CI builds

### ISSUE THREAD

**Issue by tstenner** [sccn/labstreaminglayer#219]
So far I've got [Travis CI](https://travis-ci.org/tstenner/labstreaminglayer) and [AppVeyor](https://ci.appveyor.com/project/tstenner/labstreaminglayer) running for my private fork, but it might be a good idea to have official CI builds. Both are free for open source projects and could also upload the generated packages anywhere.

The current configurations are:
- Win32 with VC14 and the included Boost version
- Ubuntu 14.04 with Clang 3.5 and system Boost
- Mac OS X with XCode 7.3 and system Boost

I'll try to see if / how they can build commits to the official repository, so new commits / PRs can automatically get built.

**Comment by tstenner** [comment]
Followup: to get CI builds for this repository, a project administrator (@dmedine?) has to set up an [AppVeyor organizational account](https://www.appveyor.com/docs/team-setup/#register-a-new-appveyor-account-with-emailpassword) and delegate the CI administration afterwards.

On Travis, a project administrator can log in with the GitHub account, add the repository and add team members.

I already committed the build configurations to the repository, so no manual build setup should be necessary any more.

**Comment by dmedine** [comment]
I'm on vacation right now. I'll check this out next week when I get back.

**Comment by tstenner** [comment]
Update: liblsl builds successfully with [Visual Studio 2008 on AppVeyor](https://ci.appveyor.com/project/tstenner/labstreaminglayer/build/1.40.66)

**Comment by tstenner** [comment]
liblsl and LabRecorder are built for each new commit and uploaded to [BinTray](https://dl.bintray.com/labstreaminglayer/LSL/) for all three platforms in the split repository, so I'll close this issue.
