### ISSUE TITLE
LSL Android library .so

### ISSUE THREAD

**Issue by mordrag88** [sccn/labstreaminglayer#222]
Hello Everyone,

I am working on an Android application which should stream data. 

Unfortunately I am having some troubles in importing the library in my project.

What I did is: 
Right click on the project, then "Link gradle with C++ project"
Then I used the ndk-build and pointed to the "Android.mk" file you provided in the archive.

However, when I build the project I get an error. (You can find the log attached)
[log.txt](https://github.com/sccn/labstreaminglayer/files/1306254/log.txt)

I hope you guys are able to help me since this project is basically my master thesis.

Thank you.

**Comment by mgrivich** [comment]
You're using a newer device (64 bit) and an old tool chain. I suggest that
you switch to the Android Studio tool chain at
https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Android/AndroidStudio
.

On Sep 15, 2017 4:57 AM, "mordrag88" <notifications@github.com> wrote:

Hello Everyone,

I am working on an Android application which should stream data.

Unfortunately I am having some troubles in importing the library in my
project.

What I did is:
Right click on the project, then "Link gradle with C++ project"
Then I used the ndk-build and pointed to the "Android.mk" file you provided
in the archive.

However, when I build the project I get an error. (You can find the log
attached)
log.txt <https://github.com/sccn/labstreaminglayer/files/1306254/log.txt>

I hope you guys are able to help me since this project is basically my
master thesis.

Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sccn/labstreaminglayer/issues/222>, or mute the thread

**Comment by mordrag88** [comment]
Hello mgrivich,

Thank for the reply, I tried to change my toolchain from the application.mk file. Is that what you meant? Otherwise could you please give me a small walkthrough? I am sorry but I am not very familiar with this.

I tried all the toolchain names reported here but none of them worked.
https://developer.android.com/ndk/guides/standalone_toolchain.html

Thank you again.

**Comment by mgrivich** [comment]
Stop using the Application.mk. Use the procedure at 
https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Android/AndroidStudio. 
The instructions are at the bottom. Android studio is at 
https://developer.android.com/studio/index.html.

**Comment by mordrag88** [comment]
Ok thanks,

This may sound very stupid to you, but after I build the folders structure how indicated in the instructions, what should I do next? Because I don't understand it

**Comment by mgrivich** [comment]
Spend a few days. Do some Android Studio tutorials. Beat your head 
against the wall trying to understand the build instructions and get 
back to me with where you are stuck. Software development in general is 
hard, and android development in particular is harder. There are few 
short cuts, and this is the only way to learn.

**Comment by mordrag88** [comment]
Hello,
so I think I moved forward, I followed the instructions and seems like I am compiling in the right way now.
However, when I try to build the project I am getting this issue:
[last log.txt](https://github.com/sccn/labstreaminglayer/files/1315182/last.log.txt)

Could you please help me troubleshooting this error?

Thanks in advance.

**Comment by mgrivich** [comment]
This looks like a new bug has appears on the latest version on github. I 
will fix it, but it may be a week or more till I'm back at my desk. For now:

Install git for windows from https://git-scm.com/download/win

Open a command prompt:

git clone https://github.com/sccn/labstreaminglayer.git

cd labstreaminglayer

git checkout 27628d014e


This will give you the code from the last time that I was sure that this 
was working.

**Comment by mordrag88** [comment]
Hello,

I followed your instructions, unfortunately, it seems like there are still some errors.
[n log.txt](https://github.com/sccn/labstreaminglayer/files/1316978/n.log.txt)

Thanks again for all the support, I really appreciate it.

**Comment by tstenner** [comment]
Just a quick note: you can also download specific commits as [https://github.com/sccn/labstreaminglayer/archive/**commit-id**.zip](https://github.com/sccn/labstreaminglayer/archive/27628d014e49c13c88f93c926601a556f242bfb9.zip) so you don't need to install Git.

I hope to have fixed the original issue [in a separate branch](https://github.com/tstenner/labstreaminglayer/archive/build_export_header.zip), could you try it and post the results?

**Comment by mordrag88** [comment]
Hello,

Yes I downloaded in both ways. I had git installed already so no problem.

However, I am still getting the same errors.
[Log x.txt](https://github.com/sccn/labstreaminglayer/files/1317423/Log.x.txt)

Thanks

**Comment by mordrag88** [comment]
Hello,

I've tried the branch you posted, but still getting the same error.
[Log x.txt](https://github.com/sccn/labstreaminglayer/files/1317428/Log.x.txt)

Thanks

**Comment by tstenner** [comment]
At least that's something. The only "real" error is
<pre><code>In file included from C:\Users\mordr\Desktop\LSLLib\altro\LSL\liblsl\external\src\filesystem\src\operations.cpp:50:
  C:/Users/mordr/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include\cstdio:107:11: error: no member named 'fgetpos' in the global namespace
    using ::fgetpos;
          ~~^
  C:/Users/mordr/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include\cstdio:117:11: error: no member named 'fsetpos' in the global namespace
    using ::fsetpos;
          ~~^
  2 errors generated.
  In file included from C:\Users\mordr\Desktop\LSLLib\altro\LSL\liblsl\src\lsl_outlet_c.cpp:3:
  In file included from C:\Users\mordr\Desktop\LSLLib\altro\LSL\liblsl\src/stream_outlet_impl.h:5:
  In file included from C:\Users\mordr\Desktop\LSLLib\altro\LSL\liblsl\src/tcp_server.h:6:
  In file included from C:\Users\mordr\Desktop\LSLLib\altro\LSL\liblsl\src/stream_info_impl.h:7:
  In file included from C:/Users/mordr/Desktop/LSLLib/altro/LSL/liblsl-Android/AndroidStudio/../../liblsl/external\boost/bimap.hpp:1:
  In file included from C:/Users/mordr/Desktop/LSLLib/altro/LSL/liblsl-Android/AndroidStudio/../../liblsl/external\lslboost/bimap.hpp:13:
  In file included from C:/Users/mordr/Desktop/LSLLib/altro/LSL/liblsl-Android/AndroidStudio/../../liblsl/external\lslboost/bimap/bimap.hpp:61:
  In file included from C:/Users/mordr/Desktop/LSLLib/altro/LSL/liblsl-Android/AndroidStudio/../../liblsl/external\lslboost/bimap/detail/bimap_core.hpp:38:
  In file included from C:/Users/mordr/Desktop/LSLLib/altro/LSL/liblsl-Android/AndroidStudio/../../liblsl/external\lslboost/bimap/relation/mutant_relation.hpp:36:</code></pre>

I suppose it's related to [this bug report](https://github.com/android-ndk/ndk/issues/452), but I'm not sure.

**Comment by mgrivich** [comment]
There seems to be an issue with some platforms in the latest version of 
Android Studio. I am investigating further. For now, try adding

productFlavors {
arm {
         ndk {
             abiFilters"armeabi-v7a","armeabi","arm64-v8a" }
     }
}

to build.grade (Module: SendStringMarkers and 
Module:ReceiveStringMarkers). This will block the broken platforms, 
which you do not need. Please continue with the old branch. Tristan, we 
will move forward to the new version after we fully understand why the 
old version is not working.

This block goes INSIDE of the android {} block. This should make it work 
for your device (which according to a previous message is arm64).

**Comment by mgrivich** [comment]
I traced the problem to the current default NDK with Android Studio. To 
fix download Revision 14b from 
https://developer.android.com/ndk/downloads/older_releases.html to a 
volume with a lot of space (it is 2.36 GB). In Android Studio, go to 
File -> Project Structure -> SDK Location -> Android NDK location and 
set the path to point at android-ndk-r14b.

It is no longer necessary to mess with the gradle files. This fix is 
preferred, because it fixes it on all platforms.

This fix works both with the older revision, and Tristan's new revision. 
I have updated the documentation in master (though I suspect that 
Tristan needs to do a merge before master will work).

**Comment by mordrag88** [comment]
Hello guys,

I am sorry I am replying only now but I did not have time to try the fix proposed.

Using ndk-14b works perfectly, I was able to compile with no errors.

Thank you very much for all the support,

I believe the issue can be closed now.

Thanks again!
