### ISSUE TITLE
BrainAmp stream synchronization issue

### ISSUE THREAD

**Issue by tstenner** [sccn/labstreaminglayer#224]
I'm not sure if this is a duplicate and I don't have a reduced example yet but I've encountered problems synchronizing two BrainAmp streams from the same computer. Both BrainAmps get triggers at the same time (±0.1ms) and the triggers are recorded alongside the EEG data (one channel) so the time difference should be constant.

The sample difference between markers (i.e. 0.2ms-steps) vs. the marker index looks like this:
![marker_sync](https://user-images.githubusercontent.com/920936/30597180-8bd2402a-9d56-11e7-9b50-1031882c210b.png)

I've uploaded the [recording](https://www.dropbox.com/s/e9eyymfr0erq8tv/2xBA.xdf.xz?dl=0), the code to load the streams is as follows:

<pre><code>import xdf
import numpy as np
import matplotlib.pyplot as plt

data = xdf.load_xdf('2xBA_Markers.xdf', verbose=False, handle_clock_resets=True)[0]
downsample_factor = 5
assert len(data) == 2

def get_markerchannels(data):
    for datastream in data:
        if not datastream['info']['source_id'][0].startswith('BrainAmpSeries'):
            continue
        marker_channel = np.array(datastream['time_series'][:,-1], dtype=np.uint8)
        marker_indices = np.nonzero((marker_channel!=0)&(marker_channel!=255))[0]
        yield {'ind': marker_indices,
               'marker': marker_channel[marker_indices]}
[p1,p2] = list(get_markerchannels(data))

min_index = p1['ind'][0]
assert p1['ind'].size == p2['ind'].size
p2offset = p2['ind'][0] - p1['ind'][0]
assert np.all(abs(p2['ind'][-1] - p1['ind'][-1] - p2offset) < 10)
</code></pre>

I'll prepare a better recording with more evenly spaced markers and see if I can reproduce it.

**Comment by clementlee2000** [comment]
So your trigger timings have differences on the order of 100ms instead of the expected 0.1ms randomly? What happened around index 825? Seems like 75 samples became your new baseline (instead of 0).

**Comment by tstenner** [comment]
[Second try](https://www.dropbox.com/s/dw2vvpww47oych7/2xBA_Markertest2.xdf.xz?dl=0) with evenly spaced markers (every 30 seconds). The sudden jump in the previous figure seemed to be because I sent some markers at the beginning and some at the end. Still, there's a drift of about 20ms/minute:

![markertest2](https://user-images.githubusercontent.com/920936/30633887-9e47ef60-9ded-11e7-857a-ab7f17e6c0bb.png)

**Comment by tstenner** [comment]
Short conclusion: both EEGs have tiny constant differences speed that get noticable over longer time periods, but it's not really a LSL-specific problem.
