### ISSUE TITLE
Live Amp App Problem (Link operation fails)

### ISSUE THREAD

**Issue by antonello87** [sccn/labstreaminglayer#225]
Hi,
I'm trying to run the Live Amp application but i keep getting an error when I press the "link" button.
Debugging the app it seems that the error depends on the line 320:

boost::algorithm::split(channelLabels,ui->channelLabels->toPlainText().toStdString(),boost::algorithm::is_any_of("\n"));

Here is a snapshot of the error when I build and compile in debug mode

![image](https://user-images.githubusercontent.com/32123994/30632610-0130e5be-9de9-11e7-819d-c903139f85ac.png)

Do you have any idea that can help me solve the problem??
Thanks,
Antonello

**Comment by dmedine** [comment]
Are you using the latest version of the LiveAmp connector (1.12) on the 
ftp? A number of buggy versions made their way there in the past. 
Everything should be fixed by now. I haven't seen it crash for a long 
time and I use it almost every day.

**Comment by antonello87** [comment]
Problem solved. 

It was related to the lack of the updated libraries in MVS 2010 build environment. In particular when building app in MSV 2010 you need to download:
- Boost for MSV 2010 (https://sourceforge.net/projects/boost/files/boost-binaries/1.59.0/boost_1_59_0-msvc-10.0-32.exe/download);
- Qt SDK for MSV 2010 (https://download.qt.io/archive/qt/4.8/4.8.6/qt-opensource-windows-x86-vs2010-4.8.6.exe).

Thanks for the prompt answer. 
Antonello
