### ISSUE TITLE
lsl_resolve_all doesnt resolve multiple streams via the matlab interface

### ISSUE THREAD

**Issue by maltesen** [sccn/labstreaminglayer#23]
I already created an issue in the matlab interface section but i am no longer sure its a matlab problem.: https://github.com/labstreaminglayer/liblsl-Matlab/issues/4

When triing to resolve multiple streams from matlab using

```
lib = lsl_loadlib();
streaminfos= lsl_resolve_all(lib,2)
```

streaminfos always just contains a single pointer to a stream, although there are multiple streams visible from lab recorder or my labview inlet implementation.

Digging deeper in the matlab interface and using

```
lib = lsl_loadlib();
tmp_results= lsl_resolve_all_(lib,2)
```

as well as modifying and recompiling (remexing) LSL/liblsl-Matlab/mex/lsl_loadlib_.c it seems to me that lsl_loadlib_.c is ok the way it is. Initially i thought the problem is related to the type of "buffer". i verified that only the first element of buffer is ever written, in that sense the value of 1 for return in lsl_loadlib_.c is correct. I messed around with the type of buffer without success.

I then tried to use lsl_resolve_byprop.m instead to work around the issue that "all" just returns a single element. The intention was that if the matlab interface just returns a single pointer to streaminfo i just ask for a single uniquely named one. However, if lsl_resolve_all.m would return i.e. "My_Outlet_5" out of 10 different names, lsl_resolve_byprop would not return anything, unless i ask specifically for "My_Outlet_5" - the only and single outlet being detected by lsl_resolve_all.m. This makes me believe, that the problem is actually being caused somewhere in LSL/liblsl/src/lsl_freefuncs_c.cpp or below. I didnt dig deeper. After ~10h im out of ideas, help would be appreciated.

**Comment by maltesen** [comment]
Hmm it seems tmp.size() = 1 in

```
LIBLSL_C_API int lsl_resolve_all(lsl_streaminfo *buffer, uint32_t buffer_elements, double wait_time) {
	try {
		// create a new resolver
		resolver_impl resolver;
		// invoke it (our only constraint is that the session id shall be the same as ours)
		string sess_id = api_config::get_instance()->session_id();
		std::vector<stream_info_impl> tmp = resolver.resolve_oneshot((string("session_id='") += sess_id) += "'",0,wait_time);
		// allocate new stream_info_impl's and assign to the buffer
		uint32_t result = buffer_elements<tmp.size() ? buffer_elements : (uint32_t)tmp.size();
		for (uint32_t k=0;k<result;k++)
			buffer[k] = (lsl_streaminfo)new stream_info_impl(tmp[k]);
		return result;
	} catch(std::exception &e) {
		std::cerr << "Error during resolve_all: " << e.what() << std::endl;
		return lsl_internal_error;
	}
}
```

inside the compiled library. I dont understand why this is the case if i call this library from the matlab wrapper but not if i call it from labview or the lab recorder app. its the same library after all and the same open outlets i try to resolve. tmp.size() doesnt even depend on the input parameters of lsl_resolve_all apart from maybe timeout, but thats working, so it doesnt depend on the interface matlab uses to call it, as long as it gets called tmp.size() should result in the same value accross languages.

**Comment by maltesen** [comment]
Matlab Code to reproduce.:

```
%% instantiate the library
lib = lsl_loadlib();

%% make a new stream outlets
info = lsl_streaminfo(lib,'BioSemi','EEG',8,100,'cf_float32','sdfwerr32432');
info2 = lsl_streaminfo(lib,'BioSemi2','EEG2',8,100,'cf_float32','gasdgfasdgsag');
outlet = lsl_outlet(info);
outlet2 = lsl_outlet(info2);

%% resolve that outlets
Result = lsl_resolve_all(lib,2)
```
Resulting Console out:
```
Result =

  1×1 cell array

    {1×1 lsl_streaminfo}
```
-> One instead of two outlets detected.

**Comment by cll008** [comment]
Not sure what's going on here, but I've copied your code and cannot reproduce the error (with a library built back in 2017...). 

My resulting console out:

`Result =

  1×2 cell array

    [1×1 lsl_streaminfo]    [1×1 lsl_streaminfo]


Result2 =

  cell

    [1×1 lsl_streaminfo]


Result3 =

  cell

    [1×1 lsl_streaminfo]`

**Comment by cboulay** [comment]
@cll008 Thank you very much for helping out. I don't use Matlab anymore so it's hard for me to do any testing.

**Comment by maltesen** [comment]
Thank you very much for your help!

@cboulay i also dont use matlab often, but the community and my coworkers do a lot. I intend to use liblsl as an interface to the various tastes of programming languages.

So this reminds me of the german lexicale problem in boost with decimal point/comma while parsing the xml i had earlier. It might be some system or matlab specific setting on my machine instead of the liblsl64.dll.

@cll008 It would be of great help for me if you could further rule out, that my liblsl64.dll or the sub-sequential mex file compilations are bad. I dropped them here.: https://www.dropbox.com/s/lb4tyksm6x982ln/lsl_liblsl-Matlab-bin.zip?dl=0 . Its the content of my LSL\liblsl-Matlab\bin folder used by the matlab code posted above. Does this work for you (fully intact?), and if not, does it work for you if you recompile the .mexw64 files (mex compilation bad but liblsl64.dll intact?) using the provided liblsl64.dll and your build_mex.m? I would like to rule out that either the dll or my mex files are bad. If those are intact i would focus on finding the incompatible settings in my system or matlab.

I would also be interested in a copy of your bin folder @cll008 in order to test that on my environment.

My System.:
- liblsl version https://github.com/sccn/labstreaminglayer/commit/75655a2613d88445e474a17e333e360d647c8a66
- Win10 x64 build 10.0.17134
- Matlab 2017b (9.3.0.713579) 64Bit (win64)
- >> mex -setup
MEX configured to use 'Microsoft Visual C++ 2017 (C)' for C language compilation.
- MSVS 2017 Ver 15.9.11

**Comment by maltesen** [comment]
No need to test the dlls or mex files. Its working on a different system in my lab (Matlba 2015a). So its system specific settings. I report once i was able to locate it.

**Comment by cll008** [comment]
Glad you have a working system on your end. Good luck!

**Comment by cboulay** [comment]
Hi @maltesen , has there been any change to this issue?

Lately there have been several users reporting that on some computers they could only detect one stream though there were several. In almost all cases, they were able to resolve their problem by modifying the `KnownPeers` parameter in the lsl_api.cfg file ([see here](https://github.com/sccn/labstreaminglayer/wiki/NetworkConnectivity#defining-the-local-laboratory)).

I hope you have solved your issue and if not that this will solve it for you. Please feel free to reopen this issue if it is not solved.
