### ISSUE TITLE
How to compile LSL

### ISSUE THREAD

**Issue by roberto9110** [sccn/labstreaminglayer#235]
Hello, 
is there a tutorial that explain to me how compile LSL?
I tried but without success at the moment
Thanks

**Comment by dmedine** [comment]
We currently revising the way we compile LSL (moving to a CMake 
approach), but if you are on Windows, you should be able to download 
visual studio 2008 for free from microsoft and simply compile the 
project here:
https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl/project/vs2008

Also, you can always grab the precompiled binaries from SCCN's ftp server:
ftp://sccn.ucsd.edu/pub/software/LSL/

**Comment by cboulay** [comment]
A VS2008 express download is really hard to find. That's probably not a good recommendation.

**Comment by cboulay** [comment]
Oops, it used to be really hard to download. I just checked again and it was easy to find an ISO. Maybe it was 2013 that was really hard to find. Sorry.

**Comment by roberto9110** [comment]
Which is a good way to compile it?



________________________________
Da: Chadwick Boulay <notifications@github.com>
Inviato: giovedì 5 ottobre 2017 15:16
A: sccn/labstreaminglayer
Cc: roberto9110; Author
Oggetto: Re: [sccn/labstreaminglayer] How to compile LSL (#235)


A VS2008 express download is really hard to find. That's probably not a good recommendation.

**Comment by cboulay** [comment]
@roberto9110 , try the [INSTALL](https://github.com/sccn/labstreaminglayer/blob/master/INSTALL.md) document and let us know if you run in to any trouble.

**Comment by tstenner** [comment]
This is documented in https://github.com/labstreaminglayer/labstreaminglayer/blob/master/doc/BUILD.md now, so I'm closing this.
