### ISSUE TITLE
liblsl-Matlab is missing

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#24]
So I, er, uh, seem to have caused this. 

I implemented set_postprocessing in the matlab API, then added, commited and pushed to origin within my local pull of the submodule. Then I backed up into labstreaminglayer and (following the instructions) did 
>> add -A
>> commit -m "message"
>> push origin master

Now there is exactly the problem described here:
https://stackoverflow.com/questions/41499714/how-to-fix-git-submodule-resulting-in-404-not-found

I am not quite sure how to fix this and I don't want to have to undo a push to the master repo, so I don't want to screw this up. Indeed the commit I made is not in the actual submodule (https://github.com/labstreaminglayer/liblsl-Matlab) but I don't know how to get it there. 

Any advice is much appreciated.

**Comment by cboulay** [comment]
I don't see your commit in the liblsl-Matlab repo. Are you sure you pushed it?

**Comment by cboulay** [comment]
I'm going to bed, but if you're sure you pushed it, check the liblsl-Matlab submodule's remote (`git remote -v`) to make sure it's github.com/labstreaminglayer/liblsl-Matlab.

**Comment by dmedine** [comment]
fixed it, all good. sorry if I spooked anyone.
