### ISSUE TITLE
qt5 boost collision

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#242]
So I just ran into this issue: https://stackoverflow.com/questions/15056834/qt5-migration-and-boost-if-hpp-macro-argument-mismatch-bug when compiling one of the apps using Qt5 on Windows (Visual Studio 2012).

The solution seems to be to remove the argument -D_MSC_VER=1500 from the custom build tool on mainwindow.h. This is the 3rd answer on the stackoverflow page. Apparently (on Windows at least) this will need to be done for every app project. Or, CMake will have to be employed (which should probably happen eventually anyway) for every app using C++.

**Comment by dmedine** [comment]
Also this: https://stackoverflow.com/questions/29939726/why-received-the-following-error-when-using-qt5

#define NOMINMAX above the #include <windows.h> in mainwindow.h did the trick.

**Comment by dmedine** [comment]
When I have the time, I will make sure that these changes don't cause a clash with qt4, then write a script to make the changes automatically and push the adjusted project files and headers. I am surprised that no on else has encountered this. I guess people aren't compiling the apps with qt5 on Windows. It could also be that newer versions of qt5 evade this problem. Qt does not have installers for more recent releases available and building it from scratch on Windows is a poorly documented nightmare.

**Comment by dmedine** [comment]
Also, also this: https://stackoverflow.com/questions/20495620/qt-5-1-1-application-failed-to-start-because-platform-plugin-windows-is-missi

With Qt5 on Windows, not only do you have to copy a whole bunch more dlls into the app folder, you also _must_ set an environment variable. Simply copying the files into the workind directory doesn't cut it, the variable must be defined (it can be the working directory). And, even though I installed Qt5 via the msi, this environment variable did not exist before I set it (which is actually good for me, because otherwise, a user would get the error and not me and I would've spent a lot of time figuring out why). 

All of which is to say, Qt5 is a pain in the neck on Windows given the current model for deploying the apps. For now, I am going to keep everything that we deploy in Qt4. Looking ahead, if we go down the cmake/appveyor (which I'm totally convinced we should) we need to bare this in mind.

**Comment by tstenner** [comment]
Is this also affecting the CMake builds? @cboulay did some amazing work integrating `windeployqt` in the `install` targets so all the required libraries (except for the VC++ runtime DLLs) are copied properly.

**Comment by dmedine** [comment]
I haven't tried this yet. I was building LiveAmp which doesn't yet have 
a CMakeLists.txt file. I did find a lot of weird things in the x64 
settings in the project file (e.g. the target name was set to 
ActiChamp64). It's hard to say where that stuff came from though, those 
files have never been particularly tidy.

**Comment by dmedine** [comment]
You kow what's amazing? When you RTFI! I found on this page (http://doc.qt.io/qt-5/windows-deployment.html --- scroll down to the 'QT Plugins' section) the solution to this last problem. All you have to do is copy the libs in <qt>\platforms into a local folder in the working directory of the application that is named 'platforms' and you are good to go.
