### ISSUE TITLE
lib = lsl_loadlib()?

### ISSUE THREAD

**Issue by TerashimaStudent** [sccn/labstreaminglayer#247]
Good evening, I have two questions and I came to ask.
Q1. Currently, when I use ReceiveData.m as it is, I tried to retrieve data from pupil data, but "lib = lsl_loadlib ();" in the third line can not go ahead with an error.
Please tell me what to put in ().

Q2.It is said that 'liblsl64.dll' can not be found when putting the value in () of lsl_loadlib, but inserting liblsl-Matlab's liblsl.dll in that place also got an error It was.
In that case, please tell me what to do if there are no errors.

**Comment by dmedine** [comment]
You need to put the path with liblsl-Matlab, and all it's subfolders on your matlab path.

**Comment by TerashimaStudent** [comment]
When referring to other problems, there is a possibility that there is a problem with Cmake build.
So referring to INSTALL.md, when I built it I got an error like the following.
CMake Error at CMakeLists.txt: 2 (project):
   Failed to run MSBuild command:
     MSBuild.exe
   to get the value of VCTargetsPath:

Configuring incomplete, errors occurred!
See also "C: /Users/tkano-kosumosu/Downloads/labstreaminglayer-master/LSL/liblsl/build/CMakeFiles/CMakeOutput.log".

Please tell me how to solve it.
spec
· Windows 8.1
· Cmake-gui 3.9.4
· Visual Studio 2017
· Boost 1.65.1
I am using it.
Please also tell me the detailed method.

**Comment by tstenner** [comment]
With Visual Studio 2017, I have installed the following components in the Visual Studio Installer in the Start Menu (translated from German, so they might be named slightly different):
- `Workloads` -> `Desktop development with C++`
- `Single Components` -> `Visual C++ Tools for CMake`, `MSBuild`

Could you make sure you've installed these components and see if the same error occurs?

**Comment by TerashimaStudent** [comment]
I added the specified one and reinstalled visual studio.
After that, I did Cmake and I did not get an error.
However, when I ran it in MATLAB, the following error occurred as in the first question.

>> pupil_rece_lsl
Loading the library ...
Function or variable 'lsl_loadlib_' is undefined.

Error: lsl_loadlib (line 65)
     hlib = lsl_loadlib_ (dllpath);

Error: pupil_rece_lsl (line 3)
lib = lsl_loadlib ();

Is it necessary to add the file created by the build to the bin in liblsl-Matlab?
What should I do?

**Comment by dmedine** [comment]
> Is it necessary to add the file created by the build to the bin in 
> liblsl-Matlab?
> What should I do?
>
Yes. Matlab needs to have the folder with liblsl32.dll (or liblsl64.dll) 
in the path.

Something else occurred to me, when building the library from scratch 
with CMake, the target is called lslxx.dll, not liblslxx.dll. This may 
also be an issue (which is why, by the way, I want to change this -- but 
that is a different issue). If the binary you built is called lslxx.dll, 
change the name to liblslxx.dll (where xx means 32 or 64 depending on 
your bit-depth).

**Comment by tstenner** [comment]
> Something else occurred to me, when building the library from scratch with CMake, the target is called lslxx.dll, not liblslxx.dll.

This is fixed on the `lslboost_update` branch

**Comment by dmedine** [comment]
Cool. I won't make a new PR about it then :-)

**Comment by TerashimaStudent** [comment]
I looked for the build file, but neither liblsl64.dll nor lsl64.dll was found.
Is this state still in the middle of build?
How can it be generated?

**Comment by tstenner** [comment]
Which build steps did you take already?
CMake has a default build step (if you don't specify anything) where it builds all the binaries and a second 'install' step where it copies the binaries to a folder (defaulting to `build/install` and changes some paths.
You can run the install step either by building the `INSTALL` target in the Visual Studio solution file or running `cmake --build path/to/the/build/folder --config Release --target install`.

**Comment by TerashimaStudent** [comment]
I built it with debug and release with reference to labstreaminglayer / LSL / liblsl / INSTALL.md.
  You can run the install step either by building the INSTALL target in the Visual Studio solution file or running cmake --build path / to / the / build / folder --config Release --target install.
However, when trying to execute the above command with the command prompt, it was an external command and could not be executed.
Please tell me how to do other than Command Printer.

**Comment by tstenner** [comment]
What do you mean with "it was an external command"?
If you have a build tree in the build directory, you could just run `build_windows.bat` again, it will show you your existing configuration and run the build afterwards.

**Comment by TerashimaStudent** [comment]
I built lsl32.dll with reference to build_windows.bat. I changed this name to liblsl32.dll and added it to liblsl-matlad / bin.
However, I got an error like the one below.
Apparently the file
"C: \ Users \ tkano-kosumosu \ Documents \ MATLAB \ liblsl-Matlab \ bin \ liblsl64.dll" is missing
on your computer. Can not load the lab streaming layer.
What should I do?

**Comment by tstenner** [comment]
In this case you need to build with a 64 bit compiler. The easiest way to do this is to delete everything in the build folder, run build_windows.bat again and select "Visual Studio XY ZZZZ **64**" as the generator after clicking on "Configure".

**Comment by dmedine** [comment]
Also, you can just download the lsl binaries and sdks. You don't have to 
build them yourself. This link ftp://sccn.ucsd.edu/pub/software/LSL/ 
appears in the 'Download Binary Releases' section of the README.md file. 
On the ftp you can download precompiled versions of all LSL sdks 
(including the Matlab sdk). Is there any reason you need to build your 
own copy?

**Comment by TerashimaStudent** [comment]
I tried both the method of changing to Visual Studio XY ZZZZ 64 and downloading from the link of ftp://sccn.ucsd.edu/pub/software/LSL/, but I got the same error as before But what should I do?
Error: lsl_loadlib (line 65)
  hlib = lsl_loadlib_ (dllpath);

Error: pupil_rece_lsl (line 3)
  lib = lsl_loadlib ();
Now I'm trying the way I'm trying to do this site (4) as I am worried about this site.
Is the matlab file here wrong?
https://groups.google.com/forum/#!topic/pupil-discuss/JvQMnRHSjWY

**Comment by walwyn11** [comment]
I am a huge newby, but had the same issues as the original poster.

I went to the website dmedin suggested above for the binary download ftp://sccn.ucsd.edu/pub/software/LSL/.  I downloaded the lsl-matlab folder and used it to replace the original lsl-matlab folder.  I also did this for the python library as well, but have not attempted to test this.

This seems to have fixed the issue.
