### ISSUE TITLE
please update path to LSLCMake.cmake in documentation

### ISSUE THREAD

**Issue by afkrause** [sccn/labstreaminglayer#25]
reporting just a minor problem: the build-documentation states that the path to the "LSLCMake.cmake" is:

build/install/LSL/cmake/

but it now seems to be

build/install/LSL/share/LSL/

if thats the new path, it would be helpful to have that consistent with the documentation.

cheers !

**Comment by tstenner** [comment]
Thanks for reporting this, I've changed it in af01ef850b4b0fa3523cfa364376ff6fa197e299
