### ISSUE TITLE
Check for working C compiler: ...  -- broken

### ISSUE THREAD

**Issue by 007cb** [sccn/labstreaminglayer#251]
Hello, I have some issues to compile the project: 'labstreaminglayer-master\LSL\liblsl-Android\AndroidStudio' with AndroidStudio 3.0.1 (on Windows). . Here is my error message:

Error:Could not delete path 'C:\...\labstreaminglayer-master\LSL\liblsl-Android\AndroidStudio\ReceiveStringMarkers\.externalNativeBuild\cmake\release\armeabi\CMakeFiles'. 

 and for the 'External Native Build Issues' I've got the following message (first part only):

-- Check for working C compiler: C:/.../Andoid_NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
-- Configuring incomplete, errors occurred!

I use the 'android-ndk-r14b' version as Android NDK.
Does anyone know the solution to my problem? 
Thanks in advance.

**Comment by mgrivich** [comment]
For the first error, restarting your computer may work. If it does not, 
check to make sure that you have write access to the folder in question 
(without administrator access or access control required).

Fro the second error, it looks like your ndk is broken. Delete 
C:/.../Andoid_NDK/android-ndk-r14b and get it again from

  https://developer.android.com/ndk/downloads/older_releases.html


Neither of these things should be located in c:\Program Files or 
C:\Program Files (x86). Those folders have special permissions requirements.

**Comment by 007cb** [comment]
Now, it works. Thank you very much!

**Comment by 007cb** [comment]
Maybe, you also know the solution to my other problem: https://github.com/sccn/labstreaminglayer/issues/253 
Thanks in advance.

**Comment by tanmay380** [comment]
i also have the same problem so after downloading ndk latest version where do we have to paste it

**Comment by mgrivich** [comment]
You don't want the latest version, you want the one linked, above. You can put it wherever you want, except for the Program Files directories (or any other directory with special permissions). I usually put it on a separate drive, because it is large. Set the location with File -> Project Structure -> SDK Location -> Android NDK location.
