### ISSUE TITLE
Error message: the program "C:\User\...\bin\liblsl64-debug.dll" can't be started.

### ISSUE THREAD

**Issue by 007cb** [sccn/labstreaminglayer#253]
Hello, 
I started the project 'vs2013.sln' (path: 'labstreaminglayer-master\LSL\liblsl\project\vs2013') with Visual Studio 2013 (on Windows). When I execute the project, I get after a while the message that the library "..\..\..\bin\liblsl64-debug.lib" and the object "..\..\..\bin\liblsl64-debug.exp" are crerated. 
Then, the next message is:

1>  liblsl.vcxproj -> C:\Users\AndroidStudioProjects\labstreaminglayer-master\LSL\liblsl\project\vs2013\liblsl\..\..\..\bin\liblsl64-debug.dll

After that, I directly get the error message that the program "C:\Users\AndroidStudioProjects\labstreaminglayer-master\LSL\liblsl\bin\liblsl64-debug.dll" can't be started.

Does anyone know the solution to my problem?

Thanks in advance.

**Comment by mgrivich** [comment]
It looks like you are clicking the play button when liblsl is set as the startup project. liblsl is a library, not an application. It can't be run directly. Right click SendStringMarkers (for example) "Set As StartUp Project." Then click the play button. To run both SendStringMarkers and ReceiveStringMarkers (a common test case), either run two versions of visual studio in parallel, or run the executables in LSL/liblsl/bin.

**Comment by 007cb** [comment]
Now, it works, thank you very much.
