### ISSUE TITLE
Use of QCoreApplication interferes with outlet creation

### ISSUE THREAD

**Issue by neurosamuel** [sccn/labstreaminglayer#26]
I create an LSL outlet with the following code:

``` C++
#include <QCoreApplication>
#include <lsl_cpp.h>
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    lsl::stream_info _EEGInfo("my-outlet", "EEG");
    lsl::stream_outlet _EEGOutlet(_EEGInfo);
    return a.exec();
}
```
While running that code, I scan the available LSL outlets with this python code:

``` python
from pylsl import StreamInlet, resolve_stream
streams = resolve_stream('type','EEG')
for stream in streams:
    print( ' - ', stream.name() )
```
And I get this output:

```
Listing available outlets:
 -  (invalid: bad lexical cast: source type value could not be interpreted as target)
 -  closeloop01-EEG
2 outlets found
```

where the first (_invalid_) outlet corresponds to the one I just created. If there are other outlets in my network I can see them properly listed here.

Interestingly, the following slightly modified code does produce a valid outlet:

``` C++
#include <QCoreApplication>
#include <lsl_cpp.h>
int main(int argc, char *argv[])
{
    lsl::stream_info _EEGInfo("my-outlet", "EEG");
    lsl::stream_outlet _EEGOutlet(_EEGInfo);
    QCoreApplication a(argc, argv);
    return a.exec();
}
```

```
Listing available outlets:
 -  my-outlet
 -  closeloop01-EEG
2 outlets found
```

Do you guys have any idea on what could explain this behavior? I can't understand why declaring the QCoreApplication _before_ creating the outlet makes it invalid.

In my real application, of course, I need to create the outlets _after_ the QCoreApplication has been declared. So, this is a stopper for me.

I have also tested using the C-API instead of the C++ one, and obtained the same behavior.

My environment:

``` bash
samuel@patient-X200CA:~/Documents$ uname -a
Linux patient-X200CA 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
samuel@patient-X200CA:~/Documents$ g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
samuel@patient-X200CA:~/dev/build-qt/out/bin$ ./qmake --version
QMake version 3.1
Using Qt version 5.9.2 in /home/samuel/dev/build-qt/out/lib
```

LSL was compiled from this version:

``` bash
samuel@patient-X200CA:~/dev/labstreaminglayer/build/install/LSL$ git log --pretty -n 1
commit af01ef850b4b0fa3523cfa364376ff6fa197e299 (HEAD -> master, origin/master, origin/HEAD)
Author: Tristan Stenner <ttstenner@gmail.com>
Date:   Wed Jun 19 09:29:44 2019 +0200

    Update LSLCMake path in documentation. Thanks to @afkrause!

```

and with CMake version 3.10.2 (and the same `g++` specified above).

Please, let me know if you need more information.

Any ideas are very welcome! :-)

**Comment by cboulay** [comment]
Is this 100% reproducible? If you try it 10 times with each, all 10 times the first will fail and all 10 times the second will succeed?
Can you try adding a 3-second sleep to the first example before `a.exec()`?
`QObject().thread()->usleep(1000*1000*3);`

Sorry I can't test myself.

**Comment by tstenner** [comment]
I think this is the same issue as https://github.com/sccn/liblsl/issues/24.

Could you print the output of `lsl_library_info()`?

**Comment by neurosamuel** [comment]
Solved!

@cboulay Yes, the issue is 100% reproducible. And a sleep before `a.exec()` doesn't help.

> I think this is the same issue as [sccn/liblsl#24](https://github.com/sccn/liblsl/issues/24).

@tstenner You're quite right. My situation is similar to what @sheinke reported in that issue. My XML-info contains a "," in both the _version_ and _created_at_ fields. The XML on the side of the outlets-scanner had almost all fileds empty or set to zero (except for IP addresses).

> Could you print the output of `lsl_library_info()`?

```
git:v1.13-b4-1-g58b51d9a/branch:HEAD/build:/compiler:GNU-7.4.0/boost:1_69
```

I updated my `labstreaminglayer/LSL/liblsl` repo to the tag `1.13.0-b6` and recompiled. That resolved my problem.

Thank you guys for actually solving this issue and for pointing me to the right direction here.

BTW: Is `1.13.0-b6` alright? Or do you recommend another commit?

**Comment by tstenner** [comment]
I hadn't gotten any notification that my change actually fixed the issue (since I couldn't reproduce it reliably), so I hadn't updated the reference to the submodule yet. I've pushed that so the fix is checked out automatically in the main repository.
