### ISSUE TITLE
Integrate Pupil Lab into LSL

### ISSUE THREAD

**Issue by leminina** [sccn/labstreaminglayer#263]
I recently have been trying to integrate Pupil Lab (a type of eye-tracking system into LSL), but I have some problems to realize it. Basically I followed the instructions, but it turns out there are many problems in those instructions. They are as below:

Step 1: Installation  
-  download lsl source code: https://github.com/sccn/labstreaminglayer/releases/tag/v1.12 (there is a .zip file there)

    Problem---- when I click this link, it turns out the labstreaminglayer-1.12 seems lose lots of files, compared to labstreaminglayer-1.0.31. Therefore, labstreaminglayer-1.12 dose not work, while labstreaminglayer-1.0.31 works well. However, I can not use version 1.0.31, because it can not integrate Pupil Lab plugin. That is why I need a complete labstreaminglayer-1.12.

![screenshot 5](https://user-images.githubusercontent.com/35584172/35201486-143222ac-ff70-11e7-89c2-c5c247d3aab4.png)
![screenshot 7](https://user-images.githubusercontent.com/35584172/35201484-0aadbda4-ff70-11e7-94e2-6a012a0f84ba.png)

-  follow steps in the https://github.com/sccn/labstreaminglayer/tree/master/Apps/PupilLabs readme to install

Pupil LSL Relay Plugin
-Build the LSL Python bindings. 
-Download liblsl-Python-1.11.zip
-Extract the zip file
-Execute python setup.py build in the extracted folder. This should generate a build folder.
-build should include another folder called lib that includes a folder called pylsl.
-Copy the pylsl with all its content to the user plugin directory*.
-Copy pupil_lsl_relay.py to the user plugin directory*.

Problem-----I download liblsl-Python-1.11.zip, and then follow the steps above, but it can not generate a build folder. I assume that the provided labstreaminglayer-1.12.zip is not complete.

Hope someone can have a look at the labstreaminglayer-1.12.zip in the provided link and assure if it is not complete.

**Comment by cboulay** [comment]
Which instructions did you follow for the first steps? BTW, I see you posted this 17 minutes ago so you might be at your computer now. You can hop on to labstreaminglayer.slack.com #users and I can try to talk you through the correct procedure, and I'll also try to update the old documentation.

**Comment by leminina** [comment]
Hi, I am at computer now. Sorry I have a problem to get to labstreaminglayer.slack.com #user. I have tried create a workplace account, but I do not know how to get access to you.

**Comment by cboulay** [comment]
https://join.slack.com/t/labstreaminglayer/shared_invite/enQtMzAyNDM3MTg5NDQ1LTE2MzVjYWExZDk5OTI0MDVlMWM1N2JjZWVhNzg1MWVmYzY0ZjkzODI5N2FlNGIwZDRlNzllMTNhZjUyODY1Nzk

**Comment by cboulay** [comment]
After some discussion and troubleshooting, @leminina is up and running.

I think the original source of the confusion is that they found several different versions of instructions that were conflicting. I think we can delay purging old instructions and unifying all our docs until after the auto-build-and-deploy system is complete. We're going to have to update the docs anyway so this issue does not need to stay open.

**Comment by dmedine** [comment]
Yes, this is badly needed (purging old docs) but there is no sense in 
doing it before the build process shift is complete.
