### ISSUE TITLE
StreamInlet, buffer length not possible to set to float?

### ISSUE THREAD

**Issue by sappelhoff** [sccn/labstreaminglayer#265]
Using the pylsl interface, I would like to set `max_buflen` to a value below 1 second. However, currently it does not seem possible to set the `max_buflen` parameter to a float value.

Example, given an arbitrary stream on the network:
``` python
from pylsl import StreamInlet, resolve_streams

streams = resolve_streams()
buflen = 0.1  # 100ms
inlet = StreamInlet(streams[0], max_buflen=buflen)
```

This yields the following error:
```
In [13]: inlet = StreamInlet(streams[0], max_buflen=buflen )
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-13-5295d56b0d11> in <module>()
----> 1 inlet = StreamInlet(streams[0], max_buflen=buflen )

C:\Users\mypath\my_env\lib\site-packages\pylsl\pylsl.pyc in
__init__(self, info, max_buflen, max_chunklen, recover)
    629                             "got a list.")
    630         self.obj = lib.lsl_create_inlet(info.obj, max_buflen, max_chunkl
en,
--> 631                                         recover)
    632         self.obj = c_void_p(self.obj)
    633         if not self.obj:

ArgumentError: argument 2: <type 'exceptions.TypeError'>: Don't know how to conv
ert parameter 2
```

Is that the expected behavior?

**Comment by cboulay** [comment]
Using any interface, the second argument to [lsl_create_inlet](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/include/lsl_c.h#L631) must be an integer. As far as I know, there is no practical benefit to reducing the buffer to less than 1 second, so I don't think we are going to break the API to add support for this.

If you feel there is a strong argument for making such a small buffer then we can reopen the issue.
