### ISSUE TITLE
Undefined function or variable 'lsl_loadlib'

### ISSUE THREAD

**Issue by faheemersh** [sccn/labstreaminglayer#267]
I'm having this issue when I try to use ReceiveData.m in matlab after starting the stream in python. I know there are a couple of other threads on this, but I have not been able to follow them as I am sort of a novice. I am not familiar with making .dll's and I know that I have placed the .dll for matlab (liblsl64.dll) in my bin directory under ~\labstreaminglayer-master\LSL\liblsl-Matlab\bin.

I have been able to get around this issue using the BCILAB developer version. After starting the stream from python, I run bcilab in matlab and then I can use either vis_stream (from Matlab viewer) or ReceiveData from the lsl examples. I shouldn't have to go through this just to run the other two functions. Any work around?

The second issue I have is that I am trying to stream via the networking widget using the OpenBCI GUI. However, for this to work, I need to know the IP, port, address to stream the data to. Since I figured this is like LSL, someone might be able to suggest what to input to those fields. 

Thank you in advance for your help!

**Comment by cboulay** [comment]
How about `addpath(genpath(~\labstreaminglayer-master\LSL\liblsl-Matlab))`?

About the OpenBCI networking widget, are you running all processes on the same PC? If everything's local then the ip/address should be [`127.0.0.1`](http://www.tech-faq.com/127-0-0-1.html). I have no idea what the ports should be. It probably doesn't matter as long as it's not blocked and not in use by anything else. I think anything above 1024 should be safe.

**Comment by faheemersh** [comment]
Unfortunately, this doesn't work. I've tried something similar before too and it isn't working unless I run the BCILAB developer version first. I don't even have to go to LSL option on BCILAB for vis_stream or ReceiveData to work, I just need to run BCILAB. Any other suggestions? Thank you again!

I am running all processes on the same PC. I am attaching a screenshot of the OpenBCI GUI Networking widget: [Link](https://drive.google.com/open?id=192j9xwLbU6H-zzfalq-NkHxANrU6i37J)

How are vis_stream and ReceiveData supposed to pick up the stream from the networking widget. Is it just automatic, like if I start the stream through python, or do I have to do some additional configuration in the respective scripts?

**Comment by cboulay** [comment]
I've never used OpenBCI. OSC is definitely not LSL. In the 'Protocol' dropdown box, is LSL there? I imagine you'll also have to select a data type before you start the stream.

Once the LSL streams are on the network, vis_stream and ReceiveData should see them.

When you run BCILAB it adds itself to the path. Your BCILAB has whatever is missing from your LSL/liblsl-Matlab... most likely the compiled mex files.

Are you sure it was `lsl_loadlib` that was missing or was it `lsl_loadlib_`?

**Comment by cboulay** [comment]
By the way, if you don't want to compile the Matlab mex files yourself, you can download the whole liblsl-Matlab package [from here](ftp://sccn.ucsd.edu/pub/software/LSL/SDK/liblsl-Matlab-1.11.zip). The compiled mex files are in the various mex/build* folders.

**Comment by cboulay** [comment]
What version of Matlab are you running (2017a?)? 64-bit, I presume?

**Comment by faheemersh** [comment]
Yes, that's correct. 2017a on 64-bit, Windows 10.

**Comment by cboulay** [comment]
I’m in the OR today and tomorrow but if I get out early then I will try on my system.

**Comment by cboulay** [comment]
Try [this](https://github.com/sccn/labstreaminglayer/releases/download/v1.12_Matlab_Win64/liblsl-Matlab.zip).

**Comment by faheemersh** [comment]
That worked! I did the addpath like you mentioned earlier and ran both ReceiveData and vis_stream without ever having to run BCILAB. What did you do this time that made it work you think?

**Comment by cboulay** [comment]
I made sure the liblsl64.dll was from the latest LSL version and I recompiled the mex files. I guess the mex files on the ftp are either somehow corrupt or incompatible versions are conflicting. I'm not terribly interested in investigating that any further.

**Comment by faheemersh** [comment]
Thank you sir! I did make sure that I had the latest dll file before I started this thread, it must have been the mex files. I will have to look into how to compile/recompile mex files.

**Comment by cboulay** [comment]
Use [build_mex.m](https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Matlab/build_mex.m). But you haven't to have [one your version of Matlab's supported compilers](https://www.mathworks.com/support/sysreq/previous_releases.html) installed. I think you also have to have previously configured Matlab to find that compiler, though I think this is more automatic than it used to be so maybe it's transparent now.

**Comment by dmedine** [comment]
Haha! I just said almost exactly this on another thread! In any case, 
consult Mathworks for preparing your machine for compiling mex files, 
then just run build_mex.m. It should be fine.
