### ISSUE TITLE
Compiled lsl for gtec nautilus for win64 64

### ISSUE THREAD

**Issue by shirareznik** [sccn/labstreaminglayer#27]
Hi,
The gtec nautilus app exists in the code, but there is no compiled version in the ftp archive.
Any chance you could upload a compiled version for gtec's Nautilus system?
Many thanks

**Comment by cboulay** [comment]
1. The ftp is no longer the official way to get compiled binaries. Please let us know where you saw instructions to use the ftp so we can update that.
2. I assume you mean the g.NEEDaccess app (as that is the only app that supports g.nautilus as far as I know). This application requires a non-free SDK therefore we cannot distribute a compiled version of the app. You will have to install the g.NEEDaccess SDK purchased from g.tec and build the application yourself.
3. For issues specific to an application, please use its issues page. e.g. [here](https://github.com/labstreaminglayer/App-g.Tec/issues) for g.tec apps.
