### ISSUE TITLE
Is it possible to connect LSL with Oculus Rift VR?

### ISSUE THREAD

**Issue by t-ajaj** [sccn/labstreaminglayer#281]
Is it possible to connect LSL with Oculus Rift VR position streaming?

Thanks

**Comment by cboulay** [comment]
It’s easy with openVR. 
Without OpenVR, a custom app would have to be made that used the Oculus API, and I don’t know if their service allows for simultaneous non-exclusive access from multiple clients.

**Comment by t-ajaj** [comment]
I am trying to look into the code of the LSL app for OpenVR and see if I can find a similar way to apply that to Oculus, I don't have enough experience with C++ as I am using the [pyovr ](https://github.com/cmbruns/pyovr)package to connect to Oculus using python.
I posted a [question ](https://forums.oculusvr.com/community/discussion/63539/simultaneous-non-exclusive-access-from-multiple-clients-to-oculus-vr/)at the Oculus discussion forums and I'm waiting to see if they have an answer.

**Comment by t-ajaj** [comment]
OpenVR and LSL are working with Oculus Rift now, I wasn't aware that OpenVR supports Oculus Rift.
But now I am having the problem that all the recorded position values are all zeros. I am recording by running "LSLOpenVR.exe" and starting the stream then running "LabRecorder.exe", pick the position stream then starting the recording. The position logging worked when I first tried it last week but suddenly it stopped.

**Comment by t-ajaj** [comment]
The issue was solved by manually running "**vrmonitor.exe**" in 

> C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64

  before running "**LSLOpenVR.exe**".
