### ISSUE TITLE
install ubuntu 16.04

### ISSUE THREAD

**Issue by pdeman** [sccn/labstreaminglayer#285]
Hi,

I tried to build labstreamingplayer.

but I get this error:

> labstreaminglayer/LSL/liblsl/external/lslboost/thread/once.hpp:38:18: error: no matching function for call to ‘call_once(lslboost::once_flag&, void (*&)())’
         call_once(flag,func);

> LSL/liblsl/CMakeFiles/lsl.dir/build.make:62 : la recette pour la cible « LSL/liblsl/CMakeFiles/lsl.dir/src/api_config.cpp.o » a échouée
make[2]: *** [LSL/liblsl/CMakeFiles/lsl.dir/src/api_config.cpp.o] Erreur 1
CMakeFiles/Makefile2:119 : la recette pour la cible « LSL/liblsl/CMakeFiles/lsl.dir/all » a échouée
make[1]: *** [LSL/liblsl/CMakeFiles/lsl.dir/all] Erreur 2

any idea ?

**Comment by tstenner** [comment]
Just for completeness, could you add which commands you ran (e.g. `cmake -DLSLAPPS_LabRecorder=1 -D...`)?

I could reproduce the problem on Ubuntu 16.04, but backporting 2e45f0b1518795f076a201cfe50950215f3183de from my testing branch fixes it.

**Comment by pdeman** [comment]
I just created the build folder.
ccmake ..
configure
generate 
and then make
as said in the INSTALL.md

**Comment by tstenner** [comment]
That looks fine, could you test my change (either `git pull origin master` if you cloned the repository or download the zip file again) and try it again?

**Comment by pdeman** [comment]
it seems to have worked.
but I don't have any software to run in "labstreaminglayer/Apps/BrainProducts/ActiChamp"
is that normal ?

and if I try to run pylsl:
cd labstreaminglayer/LSL/liblsl-Python/pylsl
 python pylsl.py
Traceback (most recent call last):
  File "pylsl.py", line 1189, in <module>
    raise RuntimeError("library " + libname + " was not found - make sure "
RuntimeError: library liblsl64.so was not found - make sure that it is on the search path (e.g., in the same folder as pylsl.py).

so it seems the install didn't work perfectly

**Comment by tstenner** [comment]
As far as I know the ActiChamp app doesn't run on Linux, because it requires a Windows-only driver (and it isn't ported to CMake yet).

For the `pylsl` package, you'll have to install it separately (`python setup.py install --user` from the `lsl-Python` directory).

**Comment by dmedine** [comment]
Yeah, unfortunately ActiChamp only runs on Windows.

**Comment by dmedine** [comment]
One thing you can try is to run a virtual machine (running Windows) on 
your Ubuntu device. There is also a virtualization tool that I have 
heard good things about called Docker 
(https://www.docker.com/what-container). I've never tried it, but maybe 
it could be used to run a Windows driver on a Linux machine.

**Comment by pdeman** [comment]
not sure to want to use windows even through docker or virtual machine. 
windows is a nightmare to use. I'll see if I can find another solution.
thanks for the pylsl installation help.

**Comment by dmedine** [comment]
You can always just run your ActiChamp via the LSL connector on a tablet 
then pipe the stream into your Linux box and do all the work with the 
data there... or use the RDAClient in Linux and stream directly from 
Recorder (though there is a higher latency penalty if you do it this way).

**Comment by pdeman** [comment]
yes I think I'll borrow a windows computer from someone and send everything to linux computers

**Comment by pdeman** [comment]
I tried as well using pip install.

and when I do python, import pylsl
I have the same error:
import pylsl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/neuropsynov/.local/lib/python2.7/site-packages/pylsl-1.10.4-py2.7.egg/pylsl/__init__.py", line 2, in <module>
    from .pylsl import IRREGULAR_RATE, DEDUCED_TIMESTAMP, FOREVER, cf_float32,\
  File "/home/neuropsynov/.local/lib/python2.7/site-packages/pylsl-1.10.4-py2.7.egg/pylsl/pylsl.py", line 1189, in <module>
    raise RuntimeError("library " + libname + " was not found - make sure "
RuntimeError: library liblsl64.so was not found - make sure that it is on the search path (e.g., in the same folder as pylsl.py).

and locate liblsl64
/usr/local/lib/python2.7/dist-packages/pylsl/liblsl64.so

import seems to look in site-packages and the .so is in dist-packages.
is that normal ?

**Comment by pdeman** [comment]
solved by uninstalling the one installed with pip. there was a conflict
