### ISSUE TITLE
Java-API

### ISSUE THREAD

**Issue by Abdulghany** [sccn/labstreaminglayer#291]
Hi! Does anyone has a working java-api would like to share or can help to setting the example provide into real streams from the device? The examples provided, if i understood, sends random numbers. But how to push the real streams?

**Comment by Abdulghany** [comment]
OpenBCI headset for EEG, it's API in Java. I have used the example codes, but how can i replace the random generated samples in (Sending example) to real EEG from headset?

**Comment by mgrivich** [comment]
I'm not that familiar with OpenBCI. But it appears that they have 
implemented LSL support (using python): 
http://docs.openbci.com/3rd%20Party%20Software/04-LSL

If you just want the data and are not too concerned with implementation 
details, I would try that first, and post to the OpenBCI forums if it 
doesn't work out.

If anyone is more aware of using OpenBCI with LSL, feel free to respond.

**Comment by Abdulghany** [comment]
Yeah i have seen this, but as you have said it's in python. But i'm interested with java, the SendData example appear as seen below. The sample are generated as random numbers instead as a real EEG data, how can i replace these random generations with real EEG signals?

        System.out.println("Creating an outlet...");
        LSL.StreamOutlet outlet = new LSL.StreamOutlet(info);
        
        System.out.println("Sending data...");
        float[] sample = new float[8];
        for (int t=0;t<100000;t++) {
            for (int k=0;k<8;k++)
                sample[k] = (float)Math.random()*100;
            outlet.push_sample(sample);
            Thread.sleep(10);
        }
        
        outlet.close();
        info.destroy();

**Comment by mgrivich** [comment]
If you wish to redo the work in the python tool in Java, I won't stop 
you, but it will involve significantly more work on your part.

Rough Steps:

1) Get the Java LSL examples functional on your computer, following the 
examples at 
https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Java

2) Learn how to access the data, using Java and the OpenBCI API

3) Build a Java project that accesses both the OpenBCI Java API and LSL 
library.

4) Pull the data, as instructed by the OpenBCI Java API, and push it to 
LSL as instructed by the LSL documentation.

**Comment by cboulay** [comment]
@Abdulghany , I'm pretty sure you're Ghoney on Slack, right?

We can't really write an OpenBCI app for you in Java. There's already a Python app. If you want to do it in Java (school project?), then you're on your own.

You should look [here](https://github.com/OpenBCI/OpenBCI_LSL/blob/master/lib/open_bci_v3.py#L155-L179) for how the data are fetched from the device. For each block data sample it then calls a callback which streams data over LSL. [Here](https://github.com/OpenBCI/OpenBCI_LSL/blob/master/lib/streamerlsl.py#L93-L103) is the callback.
