### ISSUE TITLE
Is g.USBamp app actually using reference and ground electrodes?

### ISSUE THREAD

**Issue by vicmarcag** [sccn/labstreaminglayer#292]
Hi!

We're a BCI research team from Spain, and we're currently working on a project aimed to develop a open software written in Python. We were using the g.USBamp LSL app that you provide here in order to create a LSL server to acquire the signal of the amplifier, but **we just realize that it seems that the reference channel (blue pliers provided by g.Tec) and the ground channel (yellow electrode) are not used...**

In fact, it seems that the app applies a common reference to all the channels, instead of substracting the reference and applying a common average reference (CAR) spatial filter from there onwards.

Is there a reason for this? Are we interpreting this wrong?

I would appreciate if you can clarify this issue for us ^^

**Comment by cboulay** [comment]
But maybe I can answer your question.

Unless you configure every channel to be bipolar (i.e., chan 1 = electrode 1 - electrode 2), there's no way to not use the reference input.
The "common reference" that you might see in the [g.USBamp app code here](https://github.com/labstreaminglayer/App-g.Tec/blob/master/g.USBamp/mainwindow.cpp#L200) refers to the individual reference pins available under each bank of 4 inputs. Banks A, B, C, and D can each have their own reference, or, in software, you can configure some of them to use a common reference. Typically you put the reference pin into the reference in Bank D and then tell A, B, C, and D to use the common reference. Same for ground. If  you're using more than 1 g.USBamp then you chain the references together from amp1-bankD to amp2-bankD, etc.

**Comment by vicmarcag** [comment]
Thank you for the quick response!

The problem with g.NEEDaccess API is that it is not free of charge... So, coming back to the g.USBamp issue, I think that I have understood your point.

If I have understood correctly, the 16 channels that provides g.USBamp are subdivided into 4 groups of 4 channels, that could be referenced inside the aforementioned groups (A,B,C,D) or among them, using a common reference via software. But, the pre-amplifier has two inputs for ground (yellow channel) and reference (blue peg). In previous studies, we have used the channel Fpz as a ground and the right earlobe as reference.

My question is the following, that ground and reference that provides the pre-amplifier are thus used by the g.USBamp via hardware? If so, do we need to make some processing with them?

Thanks!
