### ISSUE TITLE
Unknown compiler version

### ISSUE THREAD

**Issue by dynamite86** [sccn/labstreaminglayer#293]
Hello
Installed software versions:
- OS: Windows 10 x64 (10.0.16299.371)
- MS Visual Studio 2015: Update 3 (14.0.25431.01)
- CMake: 3.11
- Boost: 1.67.0 (now 1.65.1)
- Qt: 5.10.0 MSVC 2015 (x32 and x64)

When I try to build a project in MS VS 2015, I see messages like "Unknown compiler version - please run the configure tests and report the results":

> 2>------ Build started: Project: lslboost, Configuration: Release Win32 ------
> 2>  Building Custom Rule D:/Programming/MyProjects/labstreaminglayer/LSL/liblsl/external/CMakeLists.txt
> 2>  CMake does not need to re-run because D:/Programming/MyProjects/labstreaminglayer/build/LSL/liblsl/external/CMakeFiles/generate.stamp is up-to-date.
> 2>  chrono.cpp
> 2>  Unknown compiler version - please run the configure tests and report the results
> 2>  codecvt_error_category.cpp
> 2>  Unknown compiler version - please run the configure tests and report the results
> 2>  operations.cpp
> 2>  Unknown compiler version - please run the configure tests and report the results

The Boost library, the Qt framework are installed, the paths to the directories are specified in the environment variables, according to the instructions from "INSTALL.md" (`BOOST_ROOT=C:\boost_1_65_1` and `Qt5_DIR=C:\Qt\5.10.0\msvc2015\lib\cmake\Qt5`).
I tried to compile a project with the versions of the library Boost 1.67.0 and 1.65.1.
A similar problem was encountered on another PC running Windows 7 x64.

Can you help me solve this problem please?

**Comment by cboulay** [comment]
Not on Windows at the moment, but I'm pretty sure those `Unknown compiler version` messages are just warnings. They can be ignored. If your build is failing then I don't think that's the source of the problem.

**Comment by dmedine** [comment]
Yes, Chadwick is correct here. You can ignore these warnings. I forget 
the details, but this has to do with boost. There is a flag that will 
suppress this message and I got this right at some point but it got lost 
in the heat of the cmake development period. Now that this is cooled off 
I should revisit this.

**Comment by tstenner** [comment]
> I forget the details, but this has to do with boost.
To complete the trifecta: Boost has a list of compilers and features/workarounds/quirks they have. When the C++ compiler is newer than Boost, the list isn't complete so it emits a warning about it. This is mostly harmless, so unless you get additional errors you can safely ignore it.

**Comment by dynamite86** [comment]
Thanks for answers!
The project is assembled without errors.
I was not sure that these messages would not affect negatively the work in any way.
