### ISSUE TITLE
Add configuration parameter for consumer_queue::pop_sample sleep time

### ISSUE THREAD

**Issue by tstenner** [sccn/labstreaminglayer#294]
At the moment, `consumer_queue::pop_sample` tries to retrieve a sample from the buffer every millisecond, which is too much for apps that should not tax the system too much and don't need the samples as soon as they come in (especially LabRecorder).

Adding a configuration parameter (`queue_sleep_time`) that sets the desired sleep time wouldn't change anything about the current behaviour, be backwards compatible and cause no changes to ABI and API.

**Comment by tstenner** [comment]
I've had LabRecorder almost fully utilizing one core on a slightly older i5 with 4 streams (~5MB/s in total), with the acquisition servers using 5-10% each, but that's a different problem.
I'll try to collect some more data to illustrate the problem.

**Comment by dmedine** [comment]
Are you doing this in Linux?

**Comment by tstenner** [comment]
That was on Windows 7, back in August

**Comment by dmedine** [comment]
Hmmm. Like I said, I've never experienced anything like this before and 
we used to do massive data collection on Windows 7 back at SCCN. I look 
forward to seeing more!
