### ISSUE TITLE
Optitrack Prime 17w Camera Compatibility

### ISSUE THREAD

**Issue by rreyes114** [sccn/labstreaminglayer#307]
Hello,

I'm setting up LSL for my lab's Optitrack system. I've noticed that the "Camera Type" drop-down menu in the Optitrack connector app does not include our system's camera type. We are using Optitrack Prime 17w cameras.

Are these cameras incompatible with LSL? Is there anything I can do to make them compatible with the connector app?

**Comment by tstenner** [comment]
According to the [compatibility list](http://optitrack.com/support/software-compatibility.html) it's supported, it just isn't included in the dropdown list.

You could try just adding it to the `knowntypes` field in the `optitrack_config.cfg` and it should just work.

**Comment by rreyes114** [comment]
Thanks, I'll try this out.
