### ISSUE TITLE
LabRecorder crash using Optitrack stream

### ISSUE THREAD

**Issue by rreyes114** [sccn/labstreaminglayer#309]
Hello,

I'm in the process of setting up LSL for my lab's Optitrack system. The Optitrack connector app successfully links to LabRecorder; however, as soon as the start button is pressed, LabRecorder stops working. The error message is along the lines of "LabRecorder.exe has stopped working." 

I do not think there is anything wrong with LabRecorder itself, but rather it is the Optitrack connector app. For instance, we tried LabRecorder with the Biosemi app and it worked fine. The Optitrack software we are using is Motive 2.0.2. Has anyone else encountered this issue? Is there a fix?

Thanks,
Roehl

**Comment by tstenner** [comment]
I've uploaded a [debug build](http://trstan.stennr.de/labrecorder_1.12_debug.7z]. 

Could you install [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump), run it as `procdump -ma -i c:\dumps`, run LabRecorder and upload the resulting core dump (should appear in c:\dumps)?

**Comment by rreyes114** [comment]
Sure thing, I'll try it out. Unfortunately, I'm on break this week (I'm a student volunteer), so I won't be able to try anything until next week. Thanks for your help! I'll get back to you as soon as possible.

**Comment by rreyes114** [comment]
Here are the dump files created:
[https://files.fm/down.php?i=xyd8ha9w](url)

**Comment by rreyes114** [comment]
The previous link expired, here's a newer one: [https://files.fm/f/g3p8wqex](url)
The debug build you gave me doesn't crash, but it doesn't recognize that the Optitrack stream is online either. How can I fix this?

**Comment by rreyes114** [comment]
The previous link has expired, here's a newer one (try copy and pasting): [https://files.fm/u/nddbqe8q](url)
The debug build of LabRecorder that you uploaded doesn't crash; however, it also doesn't recognize that the Optitrack stream is online. I am also using an older version of LSL (labstreaminglayer-1.0.28 from [ftp://sccn.ucsd.edu/pub/LSL/](url)), which could be the cause of these problems.

**Comment by tstenner** [comment]
> Here are the dump files created:

The core dump contains references to Qt4, so it's likely the old version I can't say much about.

> The debug build of LabRecorder that you uploaded doesn't crash; however, it also doesn't recognize that the Optitrack stream is online.

That's strange. Is it found by the [example programs](https://dl.bintray.com/labstreaminglayer/LSL/App-Examples_1.12.0-Win64.zip)?

**Comment by rreyes114** [comment]
After some experimentation, I got the program to work when I specified the stream in the LabRecorder config file.
