### ISSUE TITLE
Fix for LabRecorder in OSX

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sccn/labstreaminglayer#31]
```
With recent changes, lsl now compiles in OSX. I've attached the new .dylib for 
those that would like to save the effort of compiling it themselves.

See issue #27 for modifications to pylsl.py for the necessary changes to 
pylsl.py
https://code.google.com/p/labstreaminglayer/issues/detail?id=27

I attached a makefile for RecorderLib in osx. To use it, change to the 
LabRecorder\src\RecorderLib\RecorderLib directory and run
`make --makefile=makefile.osx`

Or just use my RecorderLib64.dylib, attached.

I had to make a tiny change to LabRecorder.py to get it to work. The diff is 
attached.

Place RecorderLib64.dylib in the same directory as LabRecorder.py
`python LabRecorder.py`

It works!
```

Original issue reported on code.google.com by `chadwick...@gmail.com` on 3 Mar 2015 at 10:03

Attachments:
- [liblsl64.dylib](https://storage.googleapis.com/google-code-attachments/labstreaminglayer/issue-31/comment-0/liblsl64.dylib)
- [makefile.osx](https://storage.googleapis.com/google-code-attachments/labstreaminglayer/issue-31/comment-0/makefile.osx)
- [RecorderLib64.dylib](https://storage.googleapis.com/google-code-attachments/labstreaminglayer/issue-31/comment-0/RecorderLib64.dylib)
- [LabRecorder.diff](https://storage.googleapis.com/google-code-attachments/labstreaminglayer/issue-31/comment-0/LabRecorder.diff)

**Comment by cboulay** [comment]
This is outdated now.
