### ISSUE TITLE
LSL in MacOs

### ISSUE THREAD

**Issue by roberto9110** [sccn/labstreaminglayer#31]
Is there a version of LSL already compiled for Mac?

Thanks

**Comment by roberto9110** [comment]
What I meant, are there binaries for LSL apps for Mac? Thanks :)

**Comment by agricolab** [comment]
Which operating system an app supports depends heavily on the device in question. Not all manufacturers support drivers, SDKs or other services for Mac. For example, BrainProducts has only drivers for Windows, while pupillabs is based on python and supports Mac, Windows and Linux. Do you have a specific device in mind?

**Comment by roberto9110** [comment]
I had in mind EGI

Il giorno 19 lug 2019, alle ore 10:56, Robert Guggenberger <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Which operating system an app supports depends heavily on the device in question. Not all manufacturers support drivers, SDKs or other services for Mac. For example, BrainProducts has only drivers for Windows, while pupillabs is based on python and supports Mac, Windows and Linux. Do you have a specific device in mind?

**Comment by agricolab** [comment]
I have not much experience with the EGI, but it does not look like there is a binary for Mac: https://github.com/labstreaminglayer/App-EGIAmpServer/releases 

Considering how i read the description of the AmpServer, running an LSL-Client on Mac should be theoretically feasible though. https://mailman.ucsd.edu/pipermail/lsl-l/attachments/20160203/3fd6477c/attachment-0003.pdf
