### ISSUE TITLE
EGIAmpServer app connects to EGI but retrieves empty data (on MATLAB)

### ISSUE THREAD

**Issue by JmauLeonetti** [sccn/labstreaminglayer#314]
Hello,

I am working on an experiment on sleep and I need to record and analyse EEG data in realtime from the EGI. I have asked a somewhat similar question on Slack one month ago but I didn't have much time to progress on the experiment. I have now installed most of the code/software needed but EGIAmpServer can't seem to retrieve EEG data correctly. Here is my setup so far.

- The recording machine connected to the EGI is a Mac (under version Snow Leopard).
- I would like to retrieve EEG data on a Windows laptop (under Windows 10) connected to the former machine through ethernet, by using Matlab code, so I can process it in realtime

I downloaded the EGIAmpServer app for Windows and put it on the Windows laptop. The app seems to work appropriately. To illustrate this, if I put the wrong ip address (the ip address of the Mac machine), the app won't connect (see image below).

![error1](https://user-images.githubusercontent.com/15094313/42570401-0df983a6-8514-11e8-8c43-b28129cd7490.png)

By setting all parameters to their appropriate value, the application is able to link to the Mac (see image below).

![ampserver2](https://user-images.githubusercontent.com/15094313/42570437-2db5c3b2-8514-11e8-87c2-18009539e9b4.png)

I have tried to run the "RecieveData.m" example code in \LSL\liblsl-Matlab\examples. Here is the output.

>> ReceiveData
Loading the library...
Resolving an EEG stream...
Opening an inlet...
Now receiving data...

I have modified line 18 to "[vec,ts] = inlet.pull_sample(2)" so it would timeout after 2 seconds.
Every 2 seconds though the "pull_sample" set variables 'vec' and 'ts' to empty.  The "fprintf('%.2f\t',vec);" command from line 20 displays an empty line.

I have verified that the EGI is collecting EEG data with the EGI acquisition software NetStation on the Mac Machine (that only allows recording and not realtime processing).  If the EGI is on, I can see the eeg data. I also happen to possess the EGI Amp Server Pro SDK so the problem doesn't come from there.

Thank you very much.

Jean-maurice

**Comment by JmauLeonetti** [comment]
Here are the different values of the workspace that I get when running the "RecieveData.m" example code :

lib

![lib_value](https://user-images.githubusercontent.com/15094313/42571629-fedb8398-8517-11e8-961c-0f3f1c4b7c0e.png)

result

![result_value](https://user-images.githubusercontent.com/15094313/42571725-1d136f06-8518-11e8-9b9c-d42acb9acf88.png)

inlet

![inlet_value](https://user-images.githubusercontent.com/15094313/42571879-8ee178f8-8518-11e8-9e21-5bac34faace8.png)

ts = []
vec = []

Full workspace

![workspace](https://user-images.githubusercontent.com/15094313/42571889-97b7637a-8518-11e8-9de3-51e5ea76b3f3.png)

**Comment by tstenner** [comment]
Where did you get the app?

I've uploaded a [version with more debug output](https://dl.bintray.com/labstreaminglayer/LSL/App-EGIAmpServer_1.12.0-Win64.zip), could you start that from the command line and paste the output here?

**Comment by JmauLeonetti** [comment]
Hi,

I got the app from ftp://sccn.ucsd.edu/pub/software/LSL/ and downloaded the "EGI AmpServer-1.10.zip" zip file. I'll test your version and report what i got.

Jean-maurice

**Comment by JmauLeonetti** [comment]
I have uploaded and unzipped your version (EGI AmpServer App 1.12.0) on my Windows laptop. 
I ran "EGIAmpServer.exe" on the command line and it launched the EGI AmpServer Connector. Then in Matlab I ran the "RecieveData.m" code and got the same output as before with returned data being empty.

>> ReceiveData
Loading the library...
Resolving an EEG stream...
Opening an inlet...
Now receiving data...

There was no output in the command line either. I may have misunderstood your message...

I also tried to read in realtime EEG data with a Biosemi and the Biosemi application from LSL with the same procedure. This time I was able to read recorded data with the "RecieveData.m" code ("fprintf" command displayed vectors of numbers on the Matlab command window).

**Comment by cboulay** [comment]
ReceiveData.m is just an example and is not guaranteed to work with all streams. Before we can determine that the source of the problem is not in Matlab, we need to be sure that ReceiveData.m is doing everything it needs to. The fact that you are getting past the `Resolving an EEG stream...` line suggests that it is finding a stream with `type='EEG'`, but is that definitely the correct stream in this case? (I could look at the EGI AmpServer source code to determine this, but this is a good lesson/practice for you anyway...)

In Matlab, try `lib = lsl_loadlib(); streaminfos = lsl_resolve_all(lib);` Go through the resulting streaminfos to see if there are multiple streams, what their names are, what their types are, etc. Try fetching data from each stream to see what you get.

**Comment by tstenner** [comment]
> > ReceiveData
Loading the library...
Resolving an EEG stream...
Opening an inlet...
Now receiving data...

> There was no output in the command line either. I may have misunderstood your message...

When there's no output on the command line, something goes wrong very early. I've uploaded a new build that opens the command line window by default and prints messages before each of the 3 needed connections is established.

As far as I can see, the EGIAmp app was (for lack of an amplifier) never really tested and our amplifier is still somewhere between our lab and the EGI office in Oregon, so I can't test it either right now.

**Comment by JmauLeonetti** [comment]
Thnak you for your responses.
Where can I find your new build?

**Comment by tstenner** [comment]
Same link, since it was only two minor changes I didn't increment the version.

**Comment by JmauLeonetti** [comment]
I tried your new build. I got the following output in the command line (but still empty data in Matlab).

![outputcommandwindow](https://user-images.githubusercontent.com/15094313/42636308-bd34ae20-85e8-11e8-99e2-1c2eb69a38da.png)

I also ran "lib = lsl_loadlib(); streaminfos = lsl_resolve_all(lib);" in Matlab.
Only one stream was detected, but the informations contained in streaminfos{1} were not very relevant. It contained variables that looked like pointers.

![streaminfo](https://user-images.githubusercontent.com/15094313/42637454-8626fb60-85eb-11e8-9803-d575d006a9d4.png)

I couldn't see any particular field containing name or sampling frequency. I'll investigate more on that.

**Comment by tstenner** [comment]
It seems to me the amplifier / NetStation app doesn't send any data, otherwise you would see a lot of entries like `Waiting for XY bytes`. I'll take a look at it as soon as our amplifier is back.

**Comment by JmauLeonetti** [comment]
So I tried to pull EEG samples with Python and it didn't work either though I was able to create a StreamInlet.  I ran the following line to see if the detected stream had the correct properties.

streams = resolve_stream(wait_time=1.0)

The object streams[0] contained an instance of class StreamInfo (the streams list was of length 1). The properties were correct : 
streams[0].name() --> 'EGI NetAmp 0'
streams[0].type() --> 'EEG'
streams[0].channel_count() --> 64
and so on...

So maybe the problem comes the recieving Mac machine connected to the EGI not transmetting EEG data to the laptop...

**Comment by JmauLeonetti** [comment]
Hi,

We finally managed to make it stream data. The issue was coming from EGI acquisition machine. We had to unplug and plug again some dongles given by EGI and update EGI firmware (though the update alone was not sufficient). Thank very much for your help.
