### ISSUE TITLE
LSL and Tobii TX300 interactions

### ISSUE THREAD

**Issue by BSegula** [sccn/labstreaminglayer#32]
I've been trying to get my Tobii TX300 to sync with LSL using the Tobii app and have run into a problem with the app hanging after I attempt to initialise the link.

I've tried running the app in different configurations (with the Tobii disconnected, with the Tobii connected but incorrect server information provided etc.) and the app reports the error and then continues to function as expected. Adding a link to the calibration file provided by Tobii then seems to allow the linking process to start, but the connection is never made and I have to force quit the app.

I've been able to use all the other apps I've tried (Keyboard, Mouse, Sound recording, Matlab etc.) without issue with my current setup, and haven't had any difficult syncing data streams between different computers.

As I can't open and view the Tobii calibration files I suspect they're written in some proprietary format (the TX300 doesn't have any issues reading the calibration file I had output using the SDK), but I'm not sure of that. Tracing how the calibration file is passed through the app I've been stopped at the call from Tet to the dll and so can't check whether there might be some disconnect between what the calibration file is providing and what the LSL app expects, or if there is some other problem occurring.

Is this an issue that has arisen before? I haven't been able to find any mention of people using or having difficulty with Tobii products and LSL in the reported issues, but obviously it's difficult for me to tell if that's because the problem is unique to my setup or if the app is, as it says in the wiki, still untested with the hardware.

**Comment by cboulay** [comment]
For reference, [this is the app](https://github.com/labstreaminglayer/App-Tobii).

I've never tested it and without both hardware and the SDK there isn't much I can do.

**Comment by BSegula** [comment]
Would it be possible for me to have a look at the decompiled versions of the dll files for the Tobii app? I could hopefully put together a calibration file in the format the app requires and see if doing so fixes my issue, but I'm not able to do that without knowing what the app is expecting or trying to do.

**Comment by tstenner** [comment]
Most of us neither have the hardware nor the SDK sources and the Tobii support hasn't been very supportive towards SDK inquiries, so all the source code we have access to is already in the repositories.

**Comment by BSegula** [comment]
Apologies, I'm having a hard time following what in particular is being referred to; I'm happy to do the work of trying to sync the current version of the Tobii app with the SDK, at this point my hope is just that I can have a look at the decompiled versions of the dll files so that I can see what the app is trying to do, and then hopefully provide it with the information in the way it's expecting it.

Are you saying that the files I'm looking for are already accessible to me and I've just missed where I might find them?

**Comment by tstenner** [comment]
For Tobii devices, there's not just *the* SDK, there's at least 3 different SDKs. As far as I can tell, the Tobii app uses the very old Tobii eye tracker low level API I can't find any information on any more.

**Comment by BSegula** [comment]
So would my best bet be just trying to create my own LSL app for the version of the Tobii Pro SDK that I'm using?

**Comment by tstenner** [comment]
I've already done most of the work (https://github.com/tstenner/App-TobiiPro) but I've only tested it with a Spectrum Pro 600 (and I don't have access to it any more).

**Comment by BSegula** [comment]
Ok thanks, I'll give it a try and see if I can get it working with the TX300.

**Comment by BSegula** [comment]
Sorry for the delay and thanks for your help Tristan, the app you shared worked perfectly with the TX300 so I'm closing this issue.
