### ISSUE TITLE
Compiling in MSVC 2013 with provided boost has problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sccn/labstreaminglayer#33]
```
I'm getting the same problem as described here:

https://svn.boost.org/trac/boost/ticket/9332

I'm guessing something similar to their solution will work for you.
```

Original issue reported on code.google.com by `chadwick...@gmail.com` on 5 Mar 2015 at 9:29

**Comment by mgrivich** [comment]
This can also be fixed by taking has_member_function_callable_with.hpp from boost 1.56.0 and copying it over liblsl\external\lslboost\intrusive\detail\has_member_function_callable_with.hpp and then replacing boost with lslboost in most places in the file. This is a hack on top of a hack though.

**Comment by mgrivich** [comment]
I implemented the fix I described in the previous post. It is not particularly pleasing, but a significant change to the boost setup would require a significant amount of work. I put a new, functional vs2013.sln on github. There were numerous other small fixes required, but none of them were particularly significant.
