### ISSUE TITLE
LabStreamingLayer in MATLAB for BCILAB

### ISSUE THREAD

**Issue by digitalgreentea** [sccn/labstreaminglayer#342]
In reference to [https://github.com/sccn/labstreaminglayer/issues/341](https://github.com/sccn/labstreaminglayer/issues/341), I am working to get an LSL stream from my OpenBCI board into MATLAB so I can run BCILAB.

Specifications:
OSX High Sierra 10.13.6
Xcode 9.4.1 Build version 9F2000
Python 3.5.5 :: Anaconda, Inc.
MATLAB 2018a

I have the [OpenBCI_LSL](https://github.com/OpenBCI/OpenBCI_LSL) repository working at the moment and can start an LSL stream from there.

On the [OpenBCI_MATLAB](https://github.com/OpenBCI/OpenBCI_MATLAB) repository, it says it is currently deprecated, however I think it may still work. *Need some clarification here*

What would be the best way to go about this?

**Comment by dmedine** [comment]
Please don't reopen an identical issue after I've already closed the previous one (https://github.com/sccn/labstreaminglayer/issues/341). That is very bad manners. Also, I have already given you a perfectly reasonable solution to your problem. I reiterate it now:

If you copy or download the code in this file: https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl-Matlab/build_mex.m and run it from <path_to>/liblsl-Matlab it should build mex files for you and then liblsl-Matlab should work. If not, you may open an issue reporting that.
