### ISSUE TITLE
Default values  for lsl_api.cfg are hard-coded and confusing

### ISSUE THREAD

**Issue by agricolab** [sccn/labstreaminglayer#348]
After installation of pylsl 1.12.2 on Linux Mint 18.3 i run into the issue that  only the latest stream would be visible for resolve_stream. If either wlan or ethernet were connected the detection was possible.
I looked at https://github.com/sccn/labstreaminglayer/wiki/NetworkConnectivity.wiki. While very helpful,  i could not find a lsl_api.cfg in any of the three suggested locations. I therefore created one in ~/lsl_api, added 127.0.0.1 to KnownPeers. Subsequently all streams could be detected.

What feels like a complication of the debugging was the following error message popping up  when there was no ethernet or wlan connection:

```
Note (minor): could not create multicast responder for address 224.0.0.183 (failed with: set_option: No such device)
Note (minor): could not create multicast responder for address FF31:113D:6FDD:2C17:A643:FFE2:1BD1:3CD2 (failed with: set_option: No such device)
Note (minor): could not create multicast responder for address FF02:113D:6FDD:2C17:A643:FFE2:1BD1:3CD2 (failed with: set_option: No such device)
```

It seems that lsl defaults to these values, even if no lsl_api.cfg exists, and these values are hard-coded. This can cause potentially problems, and certainly was a red herring during debugging. Maybe enforcing the use of a lsl_api.cfg, or potentially creating one with default values during installation can reduce confusion.

**Comment by tstenner** [comment]
Moved to https://github.com/labstreaminglayer/liblsl/issues/9
