### ISSUE TITLE
Which pylsl?

### ISSUE THREAD

**Issue by klanderson** [sccn/labstreaminglayer#349]
The most recently modified version is at [labstreaminglayer/liblsl-Python](https://github.com/labstreaminglayer/liblsl-Python)

Other versions are: [labstreaminglayer/tree/master/LSL/liblsl-Python](https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Python) and [chkothe/pylsl](https://github.com/chkothe/pylsl)

It appears that pip installs the version from [labstreaminglayer/tree/master/LSL/liblsl-Python](https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl-Python), because `pylsl.library_info()` is not implemented.

I'd like to use `pylsl.library_info()`. Is it safe to rely on [labstreaminglayer/liblsl-Python](https://github.com/labstreaminglayer/liblsl-Python) as the official version?

**Comment by klanderson** [comment]
Oh, it looks like `library_info` is not in `__init__.py` in [labstreaminglayer/liblsl-Python](https://github.com/labstreaminglayer/liblsl-Python)

**Comment by cboulay** [comment]
Sorry for the confusion. We're close to getting rid of the duplicate repositories.

And thanks for identifying the problem. Please fix it locally. I'll modify __init__.py and upload the fixed version to pypi soon, but probably not before we eliminate the duplicate repo problem.

**Comment by cboulay** [comment]
This issue was moved to labstreaminglayer/liblsl-Python#1
