### ISSUE TITLE
C++ 2015 professional and matlab 2015b

### ISSUE THREAD

**Issue by AsmaRoshaan** [sccn/labstreaminglayer#359]
Hi 
I want to operate jaco robotic arm from windows 7 32bit and matlab 2015a or b . But the problem is matlab isn't supporting any compiler to run c++ code line. I have installed and tried almost everything. Can some one help me in this regard?

**Comment by dmedine** [comment]
If you are having problems with Matlab and a C++ compiler, why are you 
posting an issue to LSL's source code repository?
