### ISSUE TITLE
Is it possible to start recording LabRecorder from a shortcut?

### ISSUE THREAD

**Issue by BCIstorm** [sccn/labstreaminglayer#40]
I think the title says it all but here goes:
I have written a config file to pre-load all the required streams (with argument -c config_filename.cfg) but I would also like LabRecorder to start recording as soon as it is called (from batch file).
Is it possible? What is program argument?

**Comment by cboulay** [comment]
Can you please post this issue in the LabRecorder repository?
https://github.com/labstreaminglayer/App-LabRecorder/issues
