### ISSUE TITLE
Labstreaminglayer documentation for the InteraXon Muse incomplete

### ISSUE THREAD

**Issue by PeterGamma** [sccn/labstreaminglayer#44]
Issue # 30 was about the fact that Interaxon, the manufacturer of the Muse headbands did not offer the download of the  the Muse SDK anymore.

For the Labstreaminglayer  Example use with Matlab for InteraXon Muse:

https://labstreaminglayer.readthedocs.io/info/matlab_example_with_muse.html

the  InteraXon Muse SDK is necessary. The InteraXon Muse SDK is now available again, and the Issue # 30 was closed.

This issue is about the fact that the  Labstreaminglayer documentation for the  InteraXon Muse is incomplete:

https://labstreaminglayer.readthedocs.io/info/supported_devices.html

The reader of the  Labstreaminglayer documentation of the InteraXon Muse concludes that Labstreaminglayer support is there for all  InteraXon Muse headband models for everyone.

This is not true.

1. The  InteraXon Muse SDK is only available for the following persons:

“If you are hosting a hackathon, an academic or institutional research project, or working on an educational application for neuroscience or neurotech, we will continue to offer support for your projects to the best of our ability (including the legacy SDK for Muse 2016). Please reach out to our R&D team at research@choosemuse.com. “

https://choosemuse.com/development/

2. The Labstreaminglayer  Example use with Matlab for InteraXon only works with model 

Muse MU-01 - Muse - Released 2014 - Bluetooth.

In step 2 of the Labstreaminglayer  Example use with Matlab for InteraXon Muse it says:

2. Pair your computer with your Muse headset and connect to your Muse using muse-io (replace Muse-XXXX with the name of your Muse device as it shows in the Bluetooth settings) .

According to James Clutterbuck, the developer of the Mind Monitor android application, bluetooth pairing of a computer with the Muse headband only works with: 

MU-01 - Muse - Released 2014 - Bluetooth. (the first Muse headband releases in 2014)

James Clutterbuck, developer of the Mind Monitor:

«The Muse 2 is almost impossible to pair on PC. I've tried many different Bluetooth USB devices and none of them work. It was similar with the 2016 Muse. Only the 2014 Muse is easy to pair on PC. This is why I only made Muse Monitor for Android/iOS. «

https://musemonitor.com/forums/viewtopic.php?f=15&t=749 

Since the  Labstreaminglayer  Example use with Matlab for InteraXon Muse needs to pair the computer over bluetooth, the example only works with:

MU-01 - Muse - Released 2014 - Bluetooth.

The example does not work works with:

MU-02 - Muse - Released 2016 - Bluetooth LE.
MU-03 - Muse 2 - Released 2018 - Bluetooth LE.

**Comment by PeterGamma** [comment]
I found there is a Python package available form Alexandre Barachant for the two Muse Monitor models with missing LSL support:

Muse LSL:

https://github.com/alexandrebarachant/muse-lsl

for streaming, visualizing, and recording EEG data wich is compatible to: 

MU-02 - Muse - Released 2016 - Bluetooth LE.
MU-03 - Muse 2 - Released 2018 - Bluetooth LE.

**Comment by PeterGamma** [comment]
When I first looked at Alexandre Barachants GITHUB, and saw the picture of a cat on it, I was not sure about Alexandre Barachants Muse LSL Python package.

When I looked closer, I saw that Alexandre Barachant is a Research Scientist at the CTRL-Labs in New York, with a PhD in Signal Processing who published many papers with 1153 Citations :

https://scholar.google.com/citations?us ... AAAJ&hl=en

And it is possible to write issues at Alexandre Barachants Muse LSL Python package:

https://github.com/alexandrebarachant/muse-lsl/issues,

15 are open and 67 are closed.

Now, my doubts about Alexandre Barachants GITHUB with the picture from a cat are gone.

**Comment by PeterGamma** [comment]
The Model names for the three different Muse headband models:
 
* MU-01 - Muse - Released 2014 - Bluetooth.
* MU-02 - Muse - Released 2016 - Bluetooth LE.
* MU-03 - Muse 2 - Released 2018 - Bluetooth LE.

are from James Clutterbuck, the developer of the android application Mind Monitor:

https://mind-monitor.com/forums/viewtopic.php?f=15&t=840&start=10

**Comment by PeterGamma** [comment]
I discussed the subject with Alexandre Barachant.  Alexandre Barachant is currently fine with the picture from the cat. His Muse LSL is a personal project that he carries on in his free time and he does not have any official and financial support from any company. It is his personal github account and he does it for fun.

Thank you,  Alexandre Barachant for the  Muse LSL.

**Comment by PeterGamma** [comment]
The documentation looks good now, thank you. And thank you very much, Alexandre Barachant, for the Muse LSL. Don't forget, Alexandre does it for fun, and he is not a supporter which is paid for his job.

**Comment by PeterGamma** [comment]
Is it possible to add to the documentation, that Alexandre Barachant is not an official supporter from Interaxon, and that he does it for fun in his spare time? I don t know whether Alexandre would support a large order of devices from a research institute.

**Comment by cboulay** [comment]
@PeterGamma , no. Almost all of this software is unofficial and volunteer based. We would have to add that disclaimer to 90% of the repositories. Most people use their common sense and know that if someone's email address doesn't end in something like "@company_name.com" then it is not an official channel.

**Comment by PeterGamma** [comment]
O.k. So I publish here the full answer Alexandre Barachant gave to me. It contains information adressed to anybody who is interested in the LSL Interface of the Muse headband, and it s worth publishing. 

Hi Peter, 

Thanks for the feedback, this is always helpful and appreciated.

I agree that my profile picture can be off putting and don't look very professional. On the other hand, this is exactly what it looks like: a personal profile. All the project hosted on my GitHub are personal projects that I carry on my free time and don't have any official and financial support from any company.

Nowaday it's really easy to make a project looks very professional, with a nice logo and website, documentations, etc. The downside is that it confuse people about the level of support they can expect from a particular project. 99% of open sources projects are here because of a single dedicated maintainer working its night and week end to provide code and support, just for the beauty of it.
The muse-lsl package is based on a reverse engineering hack of the bluetooth protocol I did a few years ago. It solve a personal problem i had about accessing the raw data. I put it out there, and try to maintain it the best i can, with the help of my friend dano morrison. but we dont necessarily wish to become the official way to access muse raw data, this is a job for interaxon and apparently they don't want to do it.

So in essence, yes I thought about changing my profile picture for something less personal, but i'm currently fine with it because it carry the message i'm looking for, i.e. this is my personal github account and i do it for fun.

Best,
Alex

Thank you Alexandre Barachant and Dano Morrison for your comittement:

**Comment by PeterGamma** [comment]
Alexandre Barachant and Dano Morrison:

"we dont necessarily wish to become the official way to access muse raw data, this is a job for interaxon and apparently they don't want to do it."

James Clutterbuck, developer of the Mind Monitor:

https://play.google.com/store/apps/details?id=com.sonicPenguins.museMonitor&hl=de_CH

says: "Lsl is still on my list":

https://mind-monitor.com/forums/viewtopic.php?f=15&t=840

So the payed app "The Mind Monitor" could potentially become the the official way to access muse raw data.
