### ISSUE TITLE
How to properly stream band power values

### ISSUE THREAD

**Issue by gerardklee** [sccn/labstreaminglayer#47]
Hello,

I am working on implementation of neurofeedback system. I am specifically focusing on alpha waves to enhance participants' meditation and OpenBCI GUI provides band powers that has alpha, beta, theta, gamma, beta. I am thinking that I can simply connect to alpha band here and stream those values. 

Then, I face the problem. I gave it a try and output the values as csv and the values seem quite random. It seems to me that the columns represent channels (I use Cyton, so total of 8) and rows represent each band type. I don't understand what the values represent. I would appreciate any advice, please. I will also attach the screen shot of my code and the csv files. Thank you so much!

<img width="542" alt="Screen Shot 2020-01-31 at 9 51 44 AM" src="https://user-images.githubusercontent.com/47463934/73870156-6af71900-4800-11ea-9b19-0256b9adb6bb.png">
<img width="558" alt="Screen Shot 2020-01-31 at 9 56 18 AM" src="https://user-images.githubusercontent.com/47463934/73870158-6cc0dc80-4800-11ea-9b4c-57d93a2b99d9.png">
![Screen Shot 2020-02-05 at 12 44 22 AM](https://user-images.githubusercontent.com/47463934/73870164-6df20980-4800-11ea-921c-a9d302ed6ecf.png)

**Comment by gerardklee** [comment]
![Screen Shot 2020-02-05 at 12 44 22 AM](https://user-images.githubusercontent.com/47463934/73870188-7b0ef880-4800-11ea-8d79-53da87d08f76.png)

Sorry, the code is here.

**Comment by cboulay** [comment]
We can't tell you want's in the stream. It's up to the sender to tell you. Try browsing the `inlet.info().as_xml()` contents to see if there's any information there.

If not, then ask whoever wrote the code to send the stream to please add that information to their stream metadata.

**Comment by gerardklee** [comment]
Thank you @cboulay. I actually wrote the code. Would you explain more about "It's up to the sender to tell you what's in the stream"? 

Basically, I did this trial for three minutes and got the values from the power bands expecting some increase over time in alpha waves (I had my eyes closed the entire trial). I plotted the csv file and could not really find any pattern. Could it be the electrodes being worn out that could lead to very random values?

**Comment by agricolab** [comment]
Dear @gerardklee, regarding
> "It's up to the sender to tell you what's in the stream"?:

The outlet broadcasts information about itself. Besides the defaults (e.g. name, type), the creator can add additional fields. A suggestion list of additional infos for EEG is e.g. https://github.com/sccn/xdf/wiki/EEG-Meta-Data. By calling `inlet.info().as_xml()` you can inspect these fields.

Regarding
> got the values from the power bands

This means we are not sure what data openBCI is streaming. Looking at https://github.com/OpenBCI/OpenBCI_LSL/blob/master/lib/streamerlsl.py#L100 and https://github.com/OpenBCI/OpenBCI_LSL/blob/3134a1513c204834d66084491f104e6f236e440b/lib/open_bci_v3.py#L133, it seems to be raw samples of EEG data, and not power bands. This means, you would have to calculate the spectrum yourself. But you might get a definite answer if you ask there.

**Comment by gerardklee** [comment]
Thank you very much @agricolab. I will try your suggestions!
