### ISSUE TITLE
load_xdf() suddenly not properly working anymore

### ISSUE THREAD

**Issue by brainybrown2** [sccn/labstreaminglayer#48]
Dear colleagues,
we have been using LSL since a while and its a really awesome tool! Many thanks for that! Since a few days, however, we are encountering a really strange problem on all of our lab computers: When trying to load in some arbitrary .xdf-file into Matlab (we use Matlab R2018b) with load_xdf(), the following warning always pops up:

> Warning: Escaped character '\U' is not valid. See 'doc sprintf' for supported special characters. 
> In load_xdf (line 327) 
Warning: Invalid MEX-file 'C: 
> In load_xdf (line 327) 

And as a consequence, only the metadata of the .xdf-file become correctly read in, while no time_series and time_stamps is read in.

The strange thing is that we are not aware of any changes made to our MATLAB viewer folder.
Since we urgently need the load_xdf() function for any of our experiments, we would be very thankful for any advise on how to solve this problem.

**Comment by cll008** [comment]
Hi there,

Do you have multiple copies of load_xdf in your MATLAB scope? Seems like
the `load_xdf_innerloop` MEX file may be missing.

Good luck,
Clement Lee
Applications Programmer
Swartz Center for Computational Neuroscience
Institute for Neural Computation, UC San Diego
858-822-7535

**Comment by agricolab** [comment]
Dear @brainybrown2, thanks for this notice. This might be linked to https://github.com/sccn/xdf/issues/50

**Comment by brainybrown2** [comment]
Dear colleagues, 
many thanks for your quick replies. 

@cll008: Indeed the problems seemed to be related the load_xdf_innerloop.mex file, which was an completeley empty file (presumbably, because Matlab tried to download this file, but did not suceed with this?).

@agricolab: I could now resolve the problem by again downloading the whole xdf-Matlab module  (https://github.com/xdf-modules/xdf-Matlab.git), replacing this module by our old xdf-Matlab module, and immediateley commenting out the code lines L238-259 (https://github.com/xdf-modules/xdf-Matlab/blob/5b27b8cf9577dd903cbfb5386ffbf04c0441eddb/load_xdf.m#L238-L259) within the load_xdf() file, as discussed under https://github.com/sccn/xdf/issues/50.

It is important that one first comments out these lines, before one consults load_xdf(), because otherwise Matlab again tries to download this .MEX file, and thus again corrupts the function.

Many thanks for your help.

**Comment by tstenner** [comment]
> Warning: Escaped character '\U' is not valid. See 'doc sprintf' for supported special characters.

I guess there's something like `C:\Users\…` in there? The backslashes need to be either escaped (`\\`) or forward slashes (`/`)

**Comment by dmedine** [comment]
This is the same issue as this one: https://github.com/sccn/xdf/issues/50

I am going to close this as it pertains to load_xdf which is in another depository. Many people are going to get bitten by this. It needs to be attended to.
