### ISSUE TITLE
OverflowError when HD-EEG data streamed to SigVisualizer

### ISSUE THREAD

**Issue by iPsych** [sccn/labstreaminglayer#49]
LSL SigVisualizer repeatedly crashes when It receive streamed EEG Inlet from 256ch EGI Amplifier. The program starts properly and visualize very short part of initial eeg signals from 256chs, than crash.

```
Traceback (most recent call last):

  File "/Users/User/Downloads/App-SigVisualizer-64fe663e88246c14fbd60b14eff84c228f5a85a6/paintwidget.py", line 216, in paintEvent

    -self.dataBuffer[0][ch_idx] + chan_offset)

OverflowError: argument 4 overflowed: value must be in the range -2147483648 to 2147483647

Abort trap: 6
```

**Comment by cboulay** [comment]
Hi, can you please open the issue in the [SigVisualizer repository](https://github.com/labstreaminglayer/App-SigVisualizer).

It's known that the app has some bugs. I'm sure any contributions would be appreciated.

If you just need a quick visualization, you can also try one of the [examples that come with pylsl](https://github.com/labstreaminglayer/liblsl-Python/blob/master/pylsl/examples/ReceiveAndPlot.py).
