### ISSUE TITLE
Cannot download the whole folder

### ISSUE THREAD

**Issue by ihgumilar** [sccn/labstreaminglayer#52]
Hi,

I try to download the whole project here. But when I opened the Apps folder there is a bunch of folders but there are no contents in them. Could you help me in how to clone with subfolders as well ?

Does the program work too if I clone only a selected folder eg, Audio folder ?

Thanks

**Comment by agricolab** [comment]
This is because most subfolders are linked to submodules, and git does not download them by default.

Try `git clone --recursive` or another of the many options git offers: https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by cboulay** [comment]
> Does the program work too if I clone only a selected folder eg, Audio folder ?

Yes, but I doubt what I mean by "work" is the same as what you mean by "work". What I mean is that you can clone only an application repository and build the application, but you still need build tools, all of the application's dependencies, and to configure the build using CMake.

https://labstreaminglayer.readthedocs.io/dev/app_dev.html

I think you may simply want to download the release from the GitHub repository Releases page. If there are no releases for your platform then please create an issue in the corresponding repository.
