### ISSUE TITLE
Missing Docs Sections

### ISSUE THREAD

**Issue by kyucrane** [sccn/labstreaminglayer#53]
The liblsl include files at LSL/liblsl/include/lsl_c*.h reference the following documentation section names:
- "Configuration File"
- "Meta-Data Recommendations"
- "Table of Content Types"
- "code examples"
None of these seem to exist.

There are some code examples at https://github.com/sccn/labstreaminglayer/wiki/ExampleCode.wiki
There is an old "Table of Content Types" at https://code.google.com/p/labstreaminglayer/source/browse/LSL/liblsl/docs/Information.txt?r=6d4fc62daa7412bcf879f224f212e971ed57f468
There's configuration file information at https://github.com/sccn/labstreaminglayer/wiki/NetworkConnectivity.wiki

**Comment by dmedine** [comment]
To my mind, the most informative example code is here:
https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl/examples
but I believe these are pointed to by the ExampleCode.wiki file. 

Is there a specific aspect of the API that you feel is under-documented? Suggestions like this are very helpful to us.

**Comment by kyucrane** [comment]
Sorry, my interpretation of the use of "code examples" in the source was wrong.  But the other missing sections are really missing.  The official API documentation referenced from ExampleCode.wiki refers the user to documentation sections which do not exist.

For example, I do not know what type to pass when constructing a stream_info object.  The constructor documentation refers me to a "Table of Content Types" which does not exist anymore.

Additionally, I am unsure how to tell LSL the structure of my desired local network.  Code comments state "see Configuration File in the documentation" but there is no such documentation section.

Similarly stream_info::desc() directs me to "See Meta-Data Recommendations in the docs" to understand its use, but there is no such page.

**Comment by chkothe** [comment]
Hey, these refs are pointing to some really old .txt files that have been
superseded by the online docs. We'll fix them up. For content types, have a
look at code.Google.com/p/xdf

**Comment by chkothe** [comment]
Dangling documentation references have now been fixed in the repo.

Christian
