### ISSUE TITLE
Where can I find the binaries of LSL apps?

### ISSUE THREAD

**Issue by robertoguarnieri** [sccn/labstreaminglayer#54]
Where can I find the binaries of LSL apps?

**Comment by tstenner** [comment]
Just for everyone else having the same question: each app has its own repository and release page, e.g. [https://github.com/labstreaminglayer/App-LabRecorder](LabRecorder) / [LabRecorder releases](https://github.com/labstreaminglayer/App-LabRecorder/releases)

**Comment by robertoguarnieri** [comment]
Thank you.
Is there a realease for ActiCHamp_

Thank you

________________________________
Da: Tristan Stenner <notifications@github.com>
Inviato: giovedì 2 aprile 2020 12:34
A: sccn/labstreaminglayer <labstreaminglayer@noreply.github.com>
Cc: Roberto Guarnieri <roberto91_10@hotmail.it>; State change <state_change@noreply.github.com>
Oggetto: Re: [sccn/labstreaminglayer] Where can I find the binaries of LSL apps? (#54)


Just for everyone else having the same question: each app has its own repository and release page, e.g. https://github.com/labstreaminglayer/App-LabRecorder<LabRecorder> / LabRecorder releases<https://github.com/labstreaminglayer/App-LabRecorder/releases>

**Comment by dmedine** [comment]
I have been slowly migrating the Brain Products LSL apps over to the Brain Products github organization as I have been doing some updates at the same time. The new actiCHamp app is hot off the presses (it is still in Beta, but so far I haven't found any problems): https://github.com/brain-products/LSL-actiCHamp/releases
