### ISSUE TITLE
push_chunk_multiplexed drops first sample in its chunk if not provided with a timestamp array

### ISSUE THREAD

**Issue by kyucrane** [sccn/labstreaminglayer#54]
See https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/src/stream_outlet_impl.h#L132 -- the function is documented as accepting a buffer of zero or more samples.  Why does it drop the first sample?  It seems specifically coded to drop the first sample.

Compare to the variant which takes a timestamp buffer at https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/src/stream_outlet_impl.h#L104 and does not drop the first sample.

**Comment by chkothe** [comment]
Fixed now. The line should have been (num_samples > 0). By the way, it
didn't drop the first sample if multiple were provided, but it wouldn't
send if there was only one sample.

Christian

**Comment by kyucrane** [comment]
Thanks!

However, yes, it still does.  For this see line 138: https://github.com/sccn/labstreaminglayer/blob/master/LSL/liblsl/src/stream_outlet_impl.h#L138 .  'k' is initialized to 1 at the start of the loop.  Sample 0 is never pushed.

**Comment by chkothe** [comment]
No actually there's a push_sample in the line right before that pushes the
first sample.

**Comment by kyucrane** [comment]
Ha, I'm blind.
