### ISSUE TITLE
Output in LSL

### ISSUE THREAD

**Issue by robertoguarnieri** [sccn/labstreaminglayer#56]
Except Matlab, how is it possible to stream data in output to LSL?

**Comment by agricolab** [comment]
There are bindings for various languages/platforms implemented, e.g.:
- [Android](https://github.com/labstreaminglayer/liblsl-Android)
- [C/C++](https://github.com/sccn/liblsl/tree/master/include)
- [C#](https://github.com/labstreaminglayer/liblsl-Csharp)
- [Java](https://github.com/labstreaminglayer/liblsl-Java)
- [Matlab](https://github.com/labstreaminglayer/liblsl-Matlab)
- [Python](https://github.com/labstreaminglayer/liblsl-Python)
- [Unity](https://github.com/labstreaminglayer/LSL4Unity)
- [Julia](https://github.com/samuelpowell/LSL.jl)
