### ISSUE TITLE
Too many devices for the stream?

### ISSUE THREAD

**Issue by ThomasJIKim** [sccn/labstreaminglayer#61]
Hello,

Currently I am working on a project in which we are hooking up a lot of different devices to the lab streaming layer: respiratory belt, EKG, EEG (/w 64 channels), eye tracking, perhaps GSR. We were concerned given the number of inputs in the stream, it can potentially create a noticeable lag in the receiving machine getting all the signals within a time limit (in seconds). Is this something that we might expect given the number of inputs? Could the potential lag create issues with the accuracy of the timestamp?

**Comment by cboulay** [comment]
I'm sorry no one answered this one when it came in. It looks like there were several items in this repo that I missed.

The short answer to your question is that you should be fine and need not worry. If your sensors + EEG are sampling at crazy fast rates then you might run into some problems with network congestion, but you should be well within the safe range, provided your have a reasonably modern network setup.

As for the accuracy of the timestamp, it should remain < 1 msec accurate as long as you don't have very large non-stationary variability in network delays. It's unlikely that you'll ever encounter this problem, but I suppose that if the between-PC round-trip time is not (on average) double the 1-way time then there will be an error in the clock offset estimation. You shouldn't worry about this.

Really the best thing to do is test your timing. Setup all your streams and record to .xdf using LabRecorder. Send coordinated strobes or other physical/electrical disturbances to all your devices at the same time. Then load your xdf in python or Matlab and examine the different streams. Don't forget to do the clock offset adjustment when loading the xdf, and make sure to plot each stream according to its own timestamps.
