### ISSUE TITLE
Issues installing LSL

### ISSUE THREAD

**Issue by OliverMaxwell** [sccn/labstreaminglayer#64]
I am having some issues installing this. I followed the instructions on this page: https://ws-dl.blogspot.com/2019/07/2019-07-15-lab-streaming-layer-lsl.html

I followed all the instructions on the webpage and they all worked fine, however when I try to use the program there is no .exe files. in the LSL folders. In these instructions it says "You can find the LabRecorder program at C:\labstreaminglayer\install\LabRecorder\ LabRecorder.exe.". I have looked in all the folders and cannot find any .exe files. Does anyone know why this is?

**Comment by cboulay** [comment]
Those instructions weren't written by any of us and refer to an old set of build instructions. These days we don't advise anyone to build LSL themselves and instead they should use prebuilt binaries. Go to the "Releases" page on one of the LSL submodules (e.g. https://github.com/labstreaminglayer/App-LabRecorder/releases ) and you should be able to download the application for your platform.

If you encounter an application that doesn't have a precompiled binary for your platform then please let us know.
