### ISSUE TITLE
shared_ptr_helper.hpp not found

### ISSUE THREAD

**Issue by andresmanelli** [sccn/labstreaminglayer#66]
I'm not sure at which version of Boost it happened but it changed its location from `boost/archive/shared_ptr_helper.hpp` to `boost/serialization/shared_ptr_helper.hpp`.

I had same errors building with `-DUSE_SYSTEM_BOOST=ON` for Boost version 1.59.0

Changing the affected source files path from `archive` to `serialization` fixed this issue for me.
- liblsl/src/portable_archive/portable_iarchive.hpp
- liblsl/src/portable_archive/portable_oarchive.hpp

Hope this helps.
Andrés.

**Comment by dmedine** [comment]
Thanks for this.

Probably the correct thing to do is a preprocessor directive so that the path specified depends on which version of boost is being linked to. I'll add it to the list.

**Comment by chkothe** [comment]
There should already be a few lines in these two header files dealing with boost version inconsistencies, would be straightforward to add a few more. Sigh... I wish that everyone could just use the included boost version!

**Comment by dmedine** [comment]
It would also be nice if boost wasn't changing its directory structure all the time.

**Comment by andresmanelli** [comment]
You both are rigth, I'm just pointing to the build problem.. If your intention is to always build the library with the included boost version, then I think you should force that to happen. Otherwise, people will have this kind of issues. Cheers.

**Comment by chkothe** [comment]
Yeah, the reason is that this file is considered an implementation detail. The system boost option is in there because it's more in line with the Linux "share-everything" philosophy, and people from that community have requested it.

**Comment by cboulay** [comment]
Can you add a couple sentences to liblsl/external/readme.txt to explain what the provided boost is doing there and why you depend on an old version? I keep forgetting and, though it's implied in the readme, it's not explicit enough for me to not want to try using system boost. After all, I'm using system boost for two other projects, and I'm sharing system OpenCV across a couple as well. If I had independent libraries for each project then I'd have to remember different versions of interfaces and I'd have over 1GB in duplicate libraries. To me, trying to get lsl to use system boost is the saner option.

Another thing you can to do discourage system boost usage while still leaving it as an option is to have cmake default its BOOST_ROOT to the provided boost directory unless it sees the BOOST_ROOT environment variable. I expect that only the more adventurous developers will set the BOOST_ROOT environment variable before cmaking the project. IMO this is a bit more difficult than checking a box in the cmake GUI.

**Comment by tstenner** [comment]
Closed, as using system boost with liblsl isn't supported anymore.
