### ISSUE TITLE
Send multi-channel time series to LSL from a device that does not support LSL

### ISSUE THREAD

**Issue by FelixYan101** [sccn/labstreaminglayer#67]
Sorry for this question. I'm new to this comunity.

I'm currently thinking about sending a  multi-channel time series from an EEG device(polymate mini) that does not support LSL to LSL. 

It's possible to plot real-time multi-channel time series on python from this device. I wonder if it's possible to send this device's data to LSL by using this sample file's logic.(https://github.com/labstreaminglayer/liblsl-Python/blob/master/pylsl/examples/SendData.py)

Waiting for reply.
BTW: Here's the code that I use to plot EEGdata from this device.

import numpy as np

import pyqtgraph as pg
import pyqtgraph.examples
from pyqtgraph.Qt import QtGui, QtCore

import polymate.mini as pp

# 情報の表示
print('-------------------------------')
print(pp.__name__)
print(pp.__version__)
print(pp.__date__)
print(pp.__author__)
print('-------------------------------')

nRATE = 500
hPM = pp.create(nRATE, 10, nRATE * 10)

pp.setup_ele(hPM,  1, 'ELE', 1, 1000)			# nGain : 1000, 100
pp.setup_ele(hPM,  2, 'ELE', 2, 1000)			# nGain : 1000, 100
pp.setup_ele(hPM,  3, 'ELE', 3, 1000)			# nGain : 1000, 100
pp.setup_ele(hPM,  4, 'ELE', 4, 1000)			# nGain : 1000, 100
pp.setup_ele(hPM,  5, 'ELE', 5, 1000)			# nGain : 1000, 100
pp.setup_ele(hPM,  6, 'ELE', 6, 1000)			# nGain : 1000, 100
pp.setup_ele(hPM,  7, 'ELE', 7, 1000)			# nGain : 1000, 100
pp.setup_ele(hPM,  8, 'ELE', 8, 1000)			# nGain : 1000, 100
pp.setup_ele(hPM,  9, 'EXT', 1,    1, 'ON')		# nGain : 1              nPullUp : 'ON', 'OF'
pp.setup_ele(hPM, 10, 'EXT', 2,    1, 'ON')		# nGain : 1              nPullUp : 'ON', 'OF'

pp.setup_unit(hPM,  1, 'uV')
pp.setup_unit(hPM,  2, 'uV')
pp.setup_unit(hPM,  3, 'uV')
pp.setup_unit(hPM,  4, 'uV')
pp.setup_unit(hPM,  5, 'uV')
pp.setup_unit(hPM,  6, 'uV')
pp.setup_unit(hPM,  7, 'uV')
pp.setup_unit(hPM,  8, 'uV')
pp.setup_unit(hPM,  9, 'mV')
pp.setup_unit(hPM, 10, 'mV')

pp.setup_cal(hPM,  9, (0, -400),(2500, 400), 'mV')
pp.setup_cal(hPM, 10, (0, -400),(2500, 400), 'mV')

#
# 
#
nGrWin = pg.GraphicsWindow(title="sample_plot")
nGrWin.resize(1000,600)
nGrWin.autoPixelRange = False

nPlotOffset = 0
nPlotData01 = np.full(nRATE * 10, 9000, dtype = float)
nPlotData02 = np.full(nRATE * 10, 8000, dtype = float)
nPlotData03 = np.full(nRATE * 10, 7000, dtype = float)
nPlotData04 = np.full(nRATE * 10, 6000, dtype = float)
nPlotData05 = np.full(nRATE * 10, 5000, dtype = float)
nPlotData06 = np.full(nRATE * 10, 4000, dtype = float)
nPlotData07 = np.full(nRATE * 10, 3000, dtype = float)
nPlotData08 = np.full(nRATE * 10, 2000, dtype = float)
nPlotData09 = np.full(nRATE * 10, 1000, dtype = float)
nPlotData10 = np.full(nRATE * 10,    0, dtype = float)

nPlt = nGrWin.addPlot(title="AP108")
nPlt.setYRange( -1000, 10000)
nPlt.setMouseEnabled(x=False, y=False)

#nGrWin.enableMouse(false)

nCurve01 = nPlt.plot(pen='y')
nCurve02 = nPlt.plot(pen='y')
nCurve03 = nPlt.plot(pen='y')
nCurve04 = nPlt.plot(pen='y')
nCurve05 = nPlt.plot(pen='r')
nCurve06 = nPlt.plot(pen='r')
nCurve07 = nPlt.plot(pen='r')
nCurve08 = nPlt.plot(pen='r')
nCurve09 = nPlt.plot(pen='g')
nCurve10 = nPlt.plot(pen='g')

nComPort = 'COM11'		# 「デバイスとプリンター」でシリアルポートの番号を確認する

nRET = pp.open(hPM, nComPort, '19200')

if( nRET == False ):
	exit()

#-
# 抵抗測定
#-
pp.start_impd(hPM)

nIMPD, nResult = pp.data_impd(hPM)
print(nIMPD)

pp.stop_impd(hPM)

#-
# 波形測定
#-
print( '測定開始！' )

pp.start(hPM)

def update():
	global pp, hPM, nCurve01, nPlotData01, nPlotOffset

	nNums = pp.nums(hPM)

	if( nNums >= 10 ):
		nDATAs, nGetNums = pp.data( hPM, nNums )
		#print('データ取得', nNums)

		if(nGetNums != nNums):
			print( '読み出しデータと取得データが異なる！' )

		for nDATA in nDATAs:
			nPlotData01[nPlotOffset] = nDATA[ 0] +  9000
			nPlotData02[nPlotOffset] = nDATA[ 1] +  8000
			nPlotData03[nPlotOffset] = nDATA[ 2] +  7000
			nPlotData04[nPlotOffset] = nDATA[ 3] +  6000
			nPlotData05[nPlotOffset] = nDATA[ 4] +  5000
			nPlotData06[nPlotOffset] = nDATA[ 5] +  4000
			nPlotData07[nPlotOffset] = nDATA[ 6] +  3000
			nPlotData08[nPlotOffset] = nDATA[ 7] +  2000
			nPlotData09[nPlotOffset] = nDATA[ 8] +  1000
			nPlotData10[nPlotOffset] = nDATA[ 9] +     0

			nPlotOffset += 1
			if( nPlotOffset >= (nRATE * 10) ):
				nPlotOffset = 0

		nCurve01.setData(nPlotData01)
		nCurve02.setData(nPlotData02)
		nCurve03.setData(nPlotData03)
		nCurve04.setData(nPlotData04)
		nCurve05.setData(nPlotData05)
		nCurve06.setData(nPlotData06)
		nCurve07.setData(nPlotData07)
		nCurve08.setData(nPlotData08)
		nCurve09.setData(nPlotData09)
		nCurve10.setData(nPlotData10)

timer = QtCore.QTimer()
timer.timeout.connect(update)
timer.start(10)

### Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()

pp.stop(hPM)
print( '測定終了' )

pp.close(hPM)
pp.release(hPM)

**Comment by dmedine** [comment]
This is basically a 4 stage process.

Step 1: connect to the hardware using their API (looks like you know how to do this in Python already).
Step 2: setup an lsl stream_info object using the meta data from the device (i.e. sampling rate, channel labels, etc.)
Step 3: use the stream_info object to create an lsl stream_outlet object
Step 4: in an infinite loop, pole the device for data, reformat the data into a container that the stream_outlet needs, and use stream_outlet.push_sample/push_chunk to send the data

There are many examples in the Apps folder, but most of them are in C++. The Python examples are a good place to start. If you get it working, please share your work with us! We can add it to the repo and the list of supported devices.
