### ISSUE TITLE
Manually sync two streams' timestamps from different computers

### ISSUE THREAD

**Issue by Hororohoruru** [sccn/labstreaminglayer#70]
Hello! I am trying to do real time classification based on EEG data. For that I use two streams (markers and EEG, respectively). The problem is that the times of each stream are completely out of sync, and I would need them to be synced for what we intend to do. Let me explain out setup a little better.

We have two computers, A and B, which are locally conected by a router: 

- Computer A is conected to a LiveAmp EEG device and uses LabRecorder to store the data with the corresponding event markers
- Computer B is connected to the main screen, and presents the experimental stimuli. It sends the markers via LSL whenever a new stimuli is presented

Also in computer B there is a Python script that reads both the data stream from computer A and the marker stream from computer B, in order to capture EEG epochs corresponding to the first X seconds after a marker is received. The way we intended to do this is by storing EEG data in a buffer and, when a marker is received, look at its timestamp and calculate the data timestamp signaling the end of that epoch (i.e., the marker timestamp + desired epoch length). But we have found that both streams have completely different clocks.

So I would like to know how this should be handled, as we know that LabRecorder synchronizes the markers and the data, we would like to do a similar procedure to be precise in the real-time slicing of the data for classification. Thank you very much in advance

**Comment by cboulay** [comment]
Hello. The Python script in computer B has to configure the inlets to use postprocessing on the timestamps. The different options are described [here](https://github.com/labstreaminglayer/liblsl-Python/blob/master/pylsl/pylsl.py#L80-L86). You pass it as an argument to the `StreamInlet` initializer.

I'm pretty confident this answers your question so I'm going to go ahead and close this issue. Please re-open if you require further assistance on this matter.
