### ISSUE TITLE
Visualize XDF files

### ISSUE THREAD

**Issue by sandymacpherson** [sccn/labstreaminglayer#70]
I've produced some XDF files using the LabRecorder (using my own streams but also using the supplied sample programs), but I am struggling to view/verify the resulting files. I will try Matlab as the readme file suggests, but I'm hoping that there is a more direct way to do this?

In looking on the internet for viewers, I came across several cases where the name XDF is used but doesn't seem to be the same as the eXtensible Data Format. The primary example of this is a tool called Maximus which visualizes files in the Open eXchange Data Format which uses the XDF extension too, but can't open LabRecorder-made files. Is there any relationship between the two formats? For the record, something like Maximus is exactly what I'm looking for for the LabRecorder XDF files.

**Comment by cboulay** [comment]
Currently the only way to open XDF files is in Matlab. Christian once wrote a Python app for opening XDF files but that's not in the public domain.

See a relevant discussion [here](https://github.com/sccn/xdf/issues/3). (There, you can also find the Matlab tools for importing XDF including an EEGLAB plugin)

**Comment by dmedine** [comment]
streams=load_xdf(filename, options ) is what you want. That will deliver a cell array wherein each cell contains the stream info, time series and timestamps -- one for each stream. You can see all the available options by inspecting the file load_xdf.m (https://github.com/sccn/xdf). The comments at the top explain what each of the options does. 

There is also plugin for loading XDFs through EEGlab (as Chadwick points out). 

There is also the mobilab (http://sccn.ucsd.edu/wiki/MoBILAB) plugin for EEGlab which can also load XDF files and has a lot of tools for visualizing data of different types.

I have a ton of (extremely sloppy, but possibly helpful) analysis code using all three methods and would be happy to share if you are interested.

**Comment by sandymacpherson** [comment]
Thanks guys - we're going to try the Matlab plugin for this.

**Comment by cboulay** [comment]
In case anyone else comes across this issue, it's worth mentioning [SigViewer](https://github.com/cbrnr/sigviewer).
I hope after a year and 4 months you've found a solution.
