### ISSUE TITLE
load_xdf error

### ISSUE THREAD

**Issue by gkassis** [sccn/labstreaminglayer#72]
I am trying to load an xdd files but I keep getting the following error:

Insufficient number of outputs from right hand side of equal sign to satisfy assignment.

Error in getfield (line 57)
    f = s.(field);

Error in load_xdf (line 238)
filesize = getfield(dir(filename),'bytes');

appreciate the advice.

**Comment by dmedine** [comment]
Can you please move this issue to the XDF repository: https://github.com/xdf-modules/xdf-Matlab/issues?

**Comment by dmedine** [comment]
I think your file or possibly the path is wrong. You can try setting a breakpoint on that line and stepping into the getfield function. Check that the argument s actually is the file information expected by the function dir. It should have all the usual directory information. On my machine the structure looks like this (for example)
![load_xdf](https://user-images.githubusercontent.com/3613166/122713064-72f61280-d2a8-11eb-93ff-3998cca187cf.png)
:
