### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by kcsaba12** [sccn/labstreaminglayer#73]
Dear Developers,

In my research I am using the pylsl modul and I would like to cite-it in the proper way in an article, that I am currently writing. I have not found any information regarding to this topic in this git and the doc page. 

Could you please send me how can I cite your work?

Best regard,
Csaba Köllőd

**Comment by sappelhoff** [comment]
I'm not a dev, just stumbling over this by chance, but let me leave this old LSL email list thread here as it may answer your question partially (might be outdated): https://mailman.ucsd.edu/pipermail/lsl-l/2016/000257.html

**Comment by cboulay** [comment]
@sccn/team-labstreaminglayer 

We can add a DOI to a repo.
https://guides.github.com/activities/citable-code/

For that to work, there needs to be OAUTH access granted on the sccn org. I can't do that myself. I sent a request to the org "owners" that would grant me access to set it up, but really it doesn't have to be. Someone else can set it up following the above instructions.

**Comment by cll008** [comment]
Thanks @cboulay, I'll also mention this to @arnodelorme when I meet with him next Monday evening.

**Comment by cboulay** [comment]
@cll008 , thanks. Arno got to it and approved it. The liblsl repo now has a DOI:

[![DOI](https://zenodo.org/badge/123265865.svg)](https://zenodo.org/badge/latestdoi/123265865)

This badge has been added to the liblsl README.

I hope there will eventually be a liblsl paper, but until then people can use the link in the badge to find the citation.
