### ISSUE TITLE
LabRecorder missing DLLs for Windows 64 bit

### ISSUE THREAD

**Issue by sandymacpherson** [sccn/labstreaminglayer#73]
I noticed that the LabRecorder comes with 32-bit DLL and LIB libraries and 64-bit DYLIB and SO ones. This applies to both the RecorderLib and the liblsl ones when downloaded from here:
[ftp://sccn.ucsd.edu/pub/software/LSL/Apps/]

Two questions about this:

1. Why aren't there 64-bit libraries included for Windows?
2. On my 64-bit Windows 7 setup, the LabRecorder looks for the 32 bit DLLs and works fine. However, on a colleague's setup (also 64-bit Windows 7) it fails with messages about not finding the 64-bit DLLs. Is this a known issue at all?

Thanks!

**Comment by cboulay** [comment]
LabRecorder uses Python. I'm guessing that your machine has 32-bit Python and theirs has 64-bit Python.

I'm not at my Windows machine today so I can't help you with the DLL but I do use LabRecorder with 64-bit Python in Windows 10. If someone doesn't answer you before Monday then I can send it your way. I honestly can't remember if I built the DLLs myself or if they came with a previous version of LSL.

**Comment by dmedine** [comment]
Definitely a 32-bit vs 64-bit python issue. My guess is that Chadwick compiled those himself, I don't think I ever supplied those binaries -- for some historical/laziness reason, no doubt. I will compile RecorderLib for 64-bit today and drop that and the 64-bit lsl library in the ftp folder.

**Comment by sandymacpherson** [comment]
Thanks guys,

I really appreciate the quick replies. I've asked my (remote) colleague to
look into his python install and sent him the links to the 32 bit versions.
The 64-bit libraries will be useful too as I'm not certain whether they
need the 64-bit python for some other purpose.

**Comment by dmedine** [comment]
Hmmm. This is proving more difficult than anticipated. Christian originally set the solution up, but it appears that I can not coax Visual Studio 2008 into building it to target x64 for some reason.

**Comment by cboulay** [comment]
I just looked through my folder. I wrote a CMakeLists.txt file for myself. You're welcome to use it but you'll have to modify it for the new path structure. Also note that I use system Boost to build RecorderLib and rely on setting BOOST_ROOT. I also found the 64-bit RecorderLib DLL on this computer but i don't know how to attach files here. I'll e-mail it to you if you want.

```cmake
CMAKE_MINIMUM_REQUIRED(VERSION 3.1)
#SET(CMAKE_CXX_COMPILER /usr/local/bin/g++-4.9)

project(RecorderLib)

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -Wall -g")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

set(bitness 32)
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(bitness 64)  
endif()

if(WIN32)
    SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
endif()

OPTION (BUILD_SHARED_LIBS "Build Shared Libraries" ON)
SET (LIB_TYPE SHARED)
IF (NOT BUILD_SHARED_LIBS)
  SET (LIB_TYPE STATIC)
ENDIF (NOT BUILD_SHARED_LIBS)

OPTION (LINK_STATIC_LSL "Link to static lsl library" OFF)

# Create a target for the library
ADD_LIBRARY(RecorderLib ${LIB_TYPE} ${CMAKE_SOURCE_DIR}/RecorderLib.cpp)
include_directories(${CMAKE_SOURCE_DIR})

#LSL
set(LSL_DIR ${CMAKE_SOURCE_DIR}/../../../../../LSL/liblsl)
include_directories(${LSL_DIR}/include)
#FIND_LIBRARY(LSL_LIBRARY lsl${bitness} PATHS ${LSL_DIR}/bin)
#target_link_libraries(RecorderLib ${LSL_LIBRARY})
#LINK_DIRECTORIES(${LINK_DIRECTORIES} ${LSL_DIR}/bin)
if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    if (LINK_STATIC_LSL)
        target_link_libraries(RecorderLib ${LSL_DIR}/bin/liblsl.a)
    else (LINK_STATIC_LSL)
        target_link_libraries(RecorderLib ${LSL_DIR}/bin/liblsl${bitness}.dylib)
    endif (LINK_STATIC_LSL)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    if (LINK_STATIC_LSL)
        target_link_libraries(RecorderLib ${LSL_DIR}/bin/liblsl${bitness}-static.lib)
        set_property (TARGET RecorderLib PROPERTY COMPILE_DEFINITIONS lsl_STATIC) #BOOST_ALL_NO_LIB
    else (LINK_STATIC_LSL)
        target_link_libraries(RecorderLib ${LSL_DIR}/bin/liblsl${bitness}.dll)
    endif (LINK_STATIC_LSL)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
endif()

#Boost
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
set(Boost_USE_STATIC_RUNTIME OFF)
if(WIN32)
    #SET(CMAKE_INCLUDE_PATH ${CMAKE_INCLUDE_PATH} "C:/boost_1_57_0") #not necessary if BOOST_ROOT is set.
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        SET(BOOST_LIBRARYDIR "C:/boost_1_57_0/lib64-msvc-12.0")
    else()
        SET(BOOST_LIBRARYDIR "C:/boost_1_57_0/lib32-msvc-12.0")
    endif()
    FIND_PACKAGE(Boost COMPONENTS system iostreams thread date_time chrono zlib filesystem regex atomic serialization program_options REQUIRED)
else(WIN32)
    FIND_PACKAGE(Boost COMPONENTS system iostreams thread date_time chrono filesystem serialization REQUIRED)
endif()
include_directories(${Boost_INCLUDE_DIRS})
target_link_libraries(RecorderLib ${Boost_LIBRARIES})

# Other target settings

if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(CMAKE_OSX_ARCHITECTURES "x86_64")
    #set_target_properties(RecorderLib PROPERTIES MACOSX_RPATH off)
endif()

if(NOT WIN32)
    target_link_libraries(RecorderLib z)
endif()

set_target_properties(RecorderLib PROPERTIES
    PREFIX ""
    OUTPUT_NAME RecorderLib${bitness})

install(TARGETS RecorderLib
    DESTINATION ${CMAKE_SOURCE_DIR}/../../)
```

**Comment by cboulay** [comment]
If only I read the little message under the textbox, then I would have known how to attach files. Attached now.
[RecorderLib64_dll_CMakeLists.zip](https://github.com/sccn/labstreaminglayer/files/52406/RecorderLib64_dll_CMakeLists.zip)

**Comment by dmedine** [comment]
Awesome! Thank you, Chadwick. This saves me a ton of time. I will compile and post. I will also roll the cmakelists file into the repository so that people can have it.

**Comment by dmedine** [comment]
I think this issue is now moot due to the new version of LabRecorder so I'm going to close it.
