### ISSUE TITLE
liblsl32.so for ARM architecture

### ISSUE THREAD

**Issue by beaniwonder** [sccn/labstreaminglayer#74]
Hi! 
I am currently trying to run a simple server written in python on a raspberry pi (running raspbian linux). When i try to start the script is tells me that that it cannot find "liblsl32.so" and after some research I found out that it may be complied only for Intel architecture? 
(As 'ldd liblsl32.so' tells me 'not a dynamic executable' on an ARM system) 

Is it possible to get a library file compiled for ARM architecture or to compile one myself somehow?

**Comment by dmedine** [comment]
Actually, there is now an LSL version for Raspberry-Pi. I believe the code.blocks project will compile just fine, and you can download the binaries on our ftp:
ftp://sccn.ucsd.edu/pub/software/LSL/SDK/
You want 'liblsl-C-C++-1.11'. The binary is called liblsl-bcm2708.so (you can truncate the name, I just added the chip name to istinguish it from other linux builds). Also, I compiled this on a first generation Pi. I don't know if it will run on Version II.

**Comment by beaniwonder** [comment]
First off, thank you for the quick reply, even though it's not directly an 'issue'!
I tried using 'liblsl-bcm2708.so' ob both, my first generation (B-plus) as well as my second generation (2-B) Pi and it seems not to work. Even though 'readelf -h' tells me that the file was compiled for 'Advanced Micro Devices X86-64' (ARM), 'ldd' still says 'not a dynamic executable' and if I try to add it to my shared object cache (using 'ldconfig') it says 'liblsl-bcm2708.so is for unknown machine 62'. 
Do I miss something here? (I am relatively new to using shared objects) 

PS: I have managed to import the code::blocks project but as I have never worked with this particular IDE and never compiled a shared object file I am not able to do complie it myself.

**Comment by dmedine** [comment]
Yes, it does indeed appear to be invalid. I did cross-compile it on a virtual linux machine, so I suppose I shouldn't be that surprised that it doesn't work, but I seem to remember testing it before pushing it to the ftp. I am recompiling the binaries on an actual pi (which takes hours) and will replace the broken binaries when it's done.

**Comment by dmedine** [comment]
So the pi is still doing its thing. I will finish this up tomorrow.

One final note is that there were indeed incorrect project settings on the code.blocks project -- causing the library build to fail at link time. I made the correct changes and thought that I had saved them, but apparently not. It should all be correct on git etc. now.

**Comment by dmedine** [comment]
This is becoming increasingly difficult (and frustrating). I can compile LSL on the pi (it takes about 3 hours), but I get the symbol not found error on all the LSL functions when I try to link one of the C/C++ examples to it. 

I can cross compile it on my virtual linux box and send it to the pi. This time, the example programs compile without errors, but when I try to run them, they report a 'libls-bcm2708.so' file not found error. The file is most certainly there and the permissions are correct. 

I also get 'not a dynamic executable' from ldd. I have no idea what is going on here. I definitely had this working several months ago.

**Comment by dmedine** [comment]
Sorry, hit close by accident

**Comment by chkothe** [comment]
The file not found error on the .so file might be related to the file being
built for a different architecture (or perhaps with some other crucial
option set differently, but not sure if there's another option with that
effect besides target arch and bitness).

**Comment by dmedine** [comment]
Indeed so. But, presumably the cross compiler knows to build for the correct architecture and bitness.

**Comment by dmedine** [comment]
Yes. I verified that the cross compiler should be ok. I compiled a very simple test program and sent it over to the pi. Worked fine.

**Comment by chkothe** [comment]
Ok, time to call Mulder & Scully! ;)

**Comment by dmedine** [comment]
If only I could.

**Comment by dmedine** [comment]
OK, so I guess a fresh build of liblsl on the pi itself did the trick. Everything seems to be working correctly now. I am still compiling the debug library, but I will add the Pi release binaries to the ftp now.

**Comment by dmedine** [comment]
ftp://sccn.ucsd.edu/pub/software/LSL/SDK/liblsl-All-Languages-1.11.zip
and
ftp://sccn.ucsd.edu/pub/software/LSL/SDK/liblsl-C-C++-1.11.zip
have a liblsl-bcm2708.so that should work correctly now.

**Comment by beaniwonder** [comment]
Thanks a lot for all the effort! I got the file from the 'All-Languages' zip and it works fine now. Just a note: it seems that the new library is not in the 'C-C++-1.11' zip up to now.

**Comment by dmedine** [comment]
Should be there now. Debug version as well.

**Comment by kblomqvist** [comment]
@dmedine Could you provide instructions how you managed to build on Pi? I'm struggling with similar linking issues as you did.

**Comment by kblomqvist** [comment]
Workaround: add `-Wl,--allow-multiple-definition`
```bash
cmake .. -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--allow-multiple-definition"
```

At least the sources compiles and links. Don't know whether the library works or not (will test tomorrow).

**Comment by dmedine** [comment]
Glad to know you got the build to work!

I actually used code::blocks to do my compilation. I made it on a 
virtual machine with the arm toolchain for the Pi processor. I don't 
recall having to add any extra compiler flags. I may have removed the 
legacy_abi.cpp file from the build. That is only for making sure (as far 
as I know) that LSL is compatible with all the different flavors of 
Windows C++ compilers. It isn't necessary on OSX, Linux, etc.  and can 
generate some build and linking errors on those systems.

**Comment by kblomqvist** [comment]
Removing `legacy_abi.cpp` from the build did the trick too. No need for `-Wl,--allow-multiple-definition`. Thanks for the info.

**Comment by jona-sassenhagen** [comment]
I had the same problem, and removing the reference to legacy_abi.cpp fixed it. Would be nice to have this changed on master!

**Comment by micuat** [comment]
I'm trying this too and had to exclude `legacy_abi.cpp` from `src/CMakeLists.txt`. @dmedine, is the legacy api still being used (in other words can it be moved to an optional package) ?

**Comment by micuat** [comment]
also I found the binary for distribution (liblsl-bcm2708.so) is 64 bit so it won't run on pi.

**Comment by dmedine** [comment]
That's my bad. A mistake from using the cross-compiler and then not 
testing. Coincidentally, I have my pi out at home right now so in the 
coming days I will compile it natively and re-upload the binary. That 
way it will definitely work.

In the meantime, please exclude the legacy_abi.cpp from the project. I 
thought I had already done this in the commit of the code.blocks 
project, but maybe not. That code is only relevant for Windows and 
causes all sorts of issues with gcc.

**Comment by micuat** [comment]
@dmedine sorry I didn't use code blocks - I built straight from cmake so maybe that's the reason. In the meantime I built a library so that I can run on a Pi (https://github.com/chkothe/pylsl/pull/2). I had to omit `-DUSE_SYSTEM_BOOST=ON` so liblsl will work standalone and I renamed it to `liblsl32armv7l.so` (since python seems to have problems with filenames with hyphen)

**Comment by dxjones** [comment]
I downloaded @micuat's ARM library `liblsl32armv7l.so` onto my Raspberry Pi 3 B+ and when I try to run an example, it fails with an undefined symbol: `lsl_library_info`
```
/usr/local/lib/python2.7/dist-packages/pylsl/examples# python ReceiveData.py
AttributeError: /usr/local/lib/python2.7/dist-packages/pylsl/liblsl32.so: undefined symbol: lsl_library_info
```
I checked the symbols in the ".so" file using `nm -gC liblsl32.so` and it shows me all the `lsl_` symbols, but the undefined symbol is missing.

Could it be possible this function was excluded somehow when @micuat did the recompile for the ARM architecture??

I am hoping you will be able to figure out how to resolve this problem, because we are stuck and unable to proceed.  (We are trying to read raw EEG data from the Muse).

Any help or advice appreciated.

**Comment by cboulay** [comment]
@tstenner , how hard is it to add an ARM build to Travis?

**Comment by tstenner** [comment]
Very hard, as they have no ARM machines. I have a 3B (but no charger) and some changes to reduce the compile time, so it's on my radar but it might take some days

**Comment by tstenner** [comment]
On a second thought: VS2017 has an arm toolchain and the android toolchain compiles for ARM Linux, so that's something appveyor could have preinstalled

**Comment by swld** [comment]
@dxjones i have the same problem.
File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/python3.5/dist-packages/pylsl/liblsl32.so: undefined symbol: lsl_library_info

i'm really new with this and need help, how to compile in raspberry

**Comment by cboulay** [comment]
Please see https://github.com/labstreaminglayer/liblsl/pull/2 (and test the file attached to my comment there) and discussion in #336
