### ISSUE TITLE
Compilation with GCC 5.3.1 fails (boost related)

### ISSUE THREAD

**Issue by BorisMansencal** [sccn/labstreaminglayer#76]
I am trying to compile current master git version (9b90ac4) on Linux Fedora 23, with GCC 5.3.1 (and CMake 3.2.1), using the provided boost libraries.
I get the following errors: 

```                   
.../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp: In function 'lslboost::detail::thread_data_base* lslboost::detail::get_current_thread_data()':
.../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:140:91: error: no matching function for call to 'call_once(lslboost::once_flag&, void (&)())'
             lslboost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                           ^
In file included from .../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/once.hpp:20:0,
                 from .../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:17:
.../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/pthread/once_atomic.hpp:121:15: note: candidate: template<class Function, class ... ArgTypes> void lslboost::call_once(lslboost::once_flag&, lslboost::detail::thread_move_t<T>, lslboost::detail::thread_move_t<Args>...)
   inline void call_once(once_flag& flag, BOOST_THREAD_RV_REF(Function) f, BOOST_THREAD_RV_REF(ArgTypes)... args)
               ^
.../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/pthread/once_atomic.hpp:121:15: note:   template argument deduction/substitution failed:
.../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:140:91: note:   mismatched types 'lslboost::detail::thread_move_t<T>' and 'void (*)()'
             lslboost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                           ^
In file included from .../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:17:0:
.../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/once.hpp:35:13: note: candidate: template<class Function> void lslboost::call_once(Function, lslboost::once_flag&)
 inline void call_once(Function func,once_flag& flag)
             ^
.../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/once.hpp:35:13: note:   template argument deduction/substitution failed:
.../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:140:91: note:   cannot convert 'lslboost::detail::{anonymous}::create_current_thread_tls_key' (type 'void()') to type 'lslboost::once_flag&'
             lslboost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
^


.../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp: In function 'void lslboost::detail::set_current_thread_data(lslboost::detail::thread_data_base*)':
.../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:146:91: error: no matching function for call to 'call_once(lslboost::once_flag&, void (&)())'
             lslboost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                           ^
In file included from .../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/once.hpp:20:0,
                 from .../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:17:
.../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/pthread/once_atomic.hpp:121:15: note: candidate: template<class Function, class ... ArgTypes> void lslboost::call_once(lslboost::once_flag&, lslboost::detail::thread_move_t<T>, lslboost::detail::thread_move_t<Args>...)
   inline void call_once(once_flag& flag, BOOST_THREAD_RV_REF(Function) f, BOOST_THREAD_RV_REF(ArgTypes)... args)
               ^
.../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/pthread/once_atomic.hpp:121:15: note:   template argument deduction/substitution failed:
.../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:146:91: note:   mismatched types 'lslboost::detail::thread_move_t<T>' and 'void (*)()'
             lslboost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
                                                                                           ^
In file included from .../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:17:0:
.../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/once.hpp:35:13: note: candidate: template<class Function> void lslboost::call_once(Function, lslboost::once_flag&)
 inline void call_once(Function func,once_flag& flag)
             ^
.../labstreaminglayer_git/LSL/liblsl/external/lslboost/thread/once.hpp:35:13: note:   template argument deduction/substitution failed:
.../labstreaminglayer_git/LSL/liblsl/external/src/thread/src/pthread/thread.cpp:146:91: note:   cannot convert 'lslboost::detail::{anonymous}::create_current_thread_tls_key' (type 'void()') to type 'lslboost::once_flag&'
lslboost::call_once(current_thread_tls_init_flag,create_current_thread_tls_key);
```
I have not yet understood the template code enough to have a solution.
Do you have any idea ?

If I try to compile with the installed boost libraries (version 1.58.0), I get one error related to the location of shared_ptr_helper.hpp header file. 
 Changing:
```
#if BOOST_VERSION >= 103500
#include <boost/archive/shared_ptr_helper.hpp>
#endif
```
to 
```
#if BOOST_VERSION >= 105800
#include <boost/serialization/shared_ptr_helper.hpp>
#elif BOOST_VERSION >= 103500
#include <boost/archive/shared_ptr_helper.hpp>
#endif
```
in portable_iarchive.hpp & portable_oarchive.hpp allows to compile the library.

Boris.

**Comment by BorisMansencal** [comment]
FYI, I have the same problem if I compile with the LSL provided boost libraries on Ubuntu 15.10 with gcc 5.2.1.

**Comment by dmedine** [comment]
Thanks for these reports. There is definitely a problem with the cmake 
process on linux that I have to check out. If memory serves, it doesn't 
do the right thing on OSX either.

For the time being, the codeblocks project should work, though. That is 
how I compiled the binaries for linux  on our ftp 
(ftp://sccn.ucsd.edu/pub/software/LSL/SDK/). I did these on Ubuntu 
running in VMware. There were some missing files from that project once 
upon a time, but those changes should have made it into the repository.

**Comment by BorisMansencal** [comment]
I am not sure it is related to CMake...
On linux (Ubuntu 15.10), I am not able to compile with codeblocks (13.12) either. I have the same error relative to boost.
On OSX 10.11.3  but with clang compiler, liblsl compiles just fine with cmake (3.4.1).

**Comment by dmedine** [comment]
Looks like I'll have to set up an Ubuntu 15 machine. It will take some time for me to get around to doing this, but I will investigate.

**Comment by dmedine** [comment]
I just set up a virtual machine to run Wily Werewolf (Ubuntu 15.10). Indeed, the codeblocks project hit the error reported by Boris. Adding the flag `-std=c++0x` appears to do the trick. However, I am running out of memory as I compile and the compiler is failing. So, I need to delete and re-establish this virtual machine with more memory. But, I think that adding this flag will fix this problem. Probably on OSX as well.

To add the flag,  right click on the liblsl project in codeblocks and open the 'Properties' item. Click on the button on the lower right hand corner that says 'Project's build options...'. From there, there should be a tab called 'Compiler settings'. If it isn't chosen choose it. There should be a tab inside of that one that says 'Other options'. This is where you add `-std=c++0x`.

Once I redo the VM and test it, I will push the revised project onto the rep. I will take a look at the CMake stuff, too, since this undoubtedly is the same compiler error.

**Comment by BorisMansencal** [comment]
Indeed, adding the flag -std=c++0x seems to solve the issue.

I have made the following modifications to two provided CMakeLists.txt files: 
diff --git a/LSL/liblsl/external/CMakeLists.txt b/LSL/liblsl/external/CMakeLists.txt
index ba9ac49..2943411 100644
--- a/LSL/liblsl/external/CMakeLists.txt
+++ b/LSL/liblsl/external/CMakeLists.txt
@@ -48,7 +48,7 @@ if (UNIX)
     src/thread/src/pthread/once.cpp
     src/thread/src/pthread/thread.cpp
   )
-  set_property (TARGET boost PROPERTY COMPILE_FLAGS "-fPIC")
+  set_property (TARGET boost PROPERTY COMPILE_FLAGS "-fPIC -std=c++0x")
 else ()  # WIN32
   add_library (boost
     ${Boost_FILES}

diff --git a/LSL/liblsl/src/CMakeLists.txt b/LSL/liblsl/src/CMakeLists.txt
index 72ec0b1..9004659 100644
--- a/LSL/liblsl/src/CMakeLists.txt
+++ b/LSL/liblsl/src/CMakeLists.txt
@@ -41,7 +41,7 @@ if (BUILD_SHARED)
   elseif (APPLE)
     target_link_libraries (lsl ${Boost_LIBRARIES} pthread)
   elseif (UNIX)
-    set_property (TARGET lsl PROPERTY COMPILE_FLAGS "-fPIC -Wl,--exclude-libs,ALL")
+    set_property (TARGET lsl PROPERTY COMPILE_FLAGS "-fPIC -Wl,--exclude-libs,ALL -std=c++0x")
     target_link_libraries (lsl ${Boost_LIBRARIES} rt pthread)
   else ()
     target_link_libraries (lsl ${Boost_LIBRARIES})
@@ -54,7 +54,7 @@ if (BUILD_STATIC)
   # TODO: Need to check if all flags are necessary or if some flags are missing
   # TODO: Add support for other platforms
   if (UNIX)
-    set_property (TARGET lsl-static PROPERTY COMPILE_FLAGS "-fPIC")
+    set_property (TARGET lsl-static PROPERTY COMPILE_FLAGS "-fPIC -std=c++0x")
     set_target_properties (lsl-static PROPERTIES OUTPUT_NAME lsl)
     target_link_libraries (lsl-static ${Boost_LIBRARIES} rt pthread)
   endif ()

It now compiles correctly on the following distributions (configured with cmake): 
- Fedora 23 both with GCC 5.3.1 & clang 3.7
- Ubuntu 15.10 both with GCC 5.2 & clang 3.6
and it continues to compile correctly on OSX 10.11.3 with clang.

**Comment by dmedine** [comment]
Excellent. I will add these changes to my fork and submit a PR. Thanks for spotting this!
