### ISSUE TITLE
Time synchronization between multiple OS 

### ISSUE THREAD

**Issue by katerina-ds** [sccn/labstreaminglayer#78]
Hi,

Sorry if there was a question like this, I could not find any clear info. 
Have anyone had an experience of running LSL on a multiple devices with different OS?

Let's say we have a biofeedback system where:
1) EEG software runs on Windows (Acquisition machine), 
2) the processing of the stream is done on the other machine that operates on Linux / Mac (Server). 
3) The Server then controls what a person sees by sending commands to the third machine, also Linux / Mac (Display).

And surely, we wan't to minimize latency as much as possible.

How will the timing be managed in such system? Will Windows stream data with Windows-format timestamps? If so, can they be efficiently converted to unix timestamps (on which part?), so that the data streams from all machines are aligned?  

Please, share your experience and feeling about the setup. 
Many thanks!

**Comment by cboulay** [comment]
@katerina-dandelion , if your control signal or feedback modality follows dynamical rules then you can predict the state at X msec into the future and use that to drive your feedback. I attached a few slides that kind of outline the concept.
[BCI_design.pdf](https://github.com/sccn/labstreaminglayer/files/7070094/BCI_design.pdf)

**Comment by katerina-dandelion** [comment]
Thank you so much for your help @tstenner and @cboulay. 
I'll try to figure out the setup and report how it went :)

**Comment by cboulay** [comment]
Closing as stale. We'd still love to hear your feedback when you get the chance!
