### ISSUE TITLE
Wiki links for example code broken

### ISSUE THREAD

**Issue by agricolab** [sccn/labstreaminglayer#8]
I just noticed that most of the links in https://github.com/sccn/labstreaminglayer/wiki/ExampleCode are broken due to moving the repo. As they are now  submodules, the links within /sccn/labstreaminglayer use the commit hash. It is probably best to link to the respective repos in /labstreaminglayer. I started to update ExampleCode.md, but do not know how to fix the wiki without writing rights. Please note that i could not find the liblsl-C or liblsl-Cpp repos in /labstreaminglayer, so it skipped them.

**Comment by agricolab** [comment]
file:///media/rgugg/tools/python3/lslwiki/labstreaminglayer.wiki/ExampleCode.md

**Comment by agricolab** [comment]
Apparently, uploading .md is not possible, so please find it as a .txt
[ExampleCode.txt](https://github.com/sccn/labstreaminglayer/files/2616042/ExampleCode.txt)

**Comment by cboulay** [comment]
Over the weekend I cleaned up a lot of the Wiki but this is one that I missed. I've incorporated your changes and a few more. There is at least one link I can't resolve. In any case, it's now in much better shape than it was even before the move. Thanks Robert!
