### ISSUE TITLE
Is it possible to compile liblsl to .frameworks or other format which callable in labview?

### ISSUE THREAD

**Issue by iPsych** [sccn/labstreaminglayer#82]
In windows, @maltesen shown the possibility to call liblsl in Labview. (https://github.com/maltesen/liblsl-LabVIEW)
However, whenever call liblsl.dylib through 'call library function' (https://knowledge.ni.com/KnowledgeArticleDetails?id=kA03q000000YGggCAG&l=en-US) in Mac version of Labview, it crashes. 

A few successful MacOS implementation cases of 'call library function' seems only works with .frameworks, not .dylib.
Is there any variant of liblsl possibly callable in Labview in MacOS?

**Comment by cboulay** [comment]
For future visitors, there is some discussion of a Framework [here](https://github.com/sccn/liblsl/issues/186#issuecomment-1824833598).
