### ISSUE TITLE
Fixing LSL bloat wiped away all pending pull requests

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#83]
First of all, please re-clone/re-fork if you want to have the new leaner (by about 45Mb) version of the LSL repository. I removed a lot of superfluously tracked binaries and zip archives. But....

If anyone had an open pull request, can you please reopen it? The git magic I worked seems to have had the side effect of automatically closing all the open pull requests. I don't know why, but there it is. I think I contacted everyone directly or indirectly that I could think of, but spread the word.

**Comment by cboulay** [comment]
I think there's a little more cleaning to be done. See my recent comments in #80 

I know you've seen how bad/slow it can be to use git with a repo that has many tracked binary changes so you have an appreciation for why this is necessary and I don't need to convince you.

But I'd also like to mention that in the past few days I've attempted to clone this repo (or my fork) about 5 times and it's failed 3 times during the transfer. Reducing the repo size is beneficial for people like me even if it's not in a state where git has become unreasonably slow. Thank you for doing this.
