### ISSUE TITLE
Bluetooth version

### ISSUE THREAD

**Issue by HughWXY** [sccn/labstreaminglayer#88]
Dear all,
We're setting up an EEG recording system with a waveguard connect 19 channel eeg cap that connected to a PC laptop via bluetooth 2.0. I'm wondering if LSL has any requirement for the bluetooth version since 2.0 was a technique quite a long time ago, also I'm not sure using Bluetooth 2.0 has any impact on the data synchronization. Any suggestion is welcome!

Thanks,
Hugh

**Comment by cboulay** [comment]
It's up to the manufacturer to communicate between the EEG cap and the host PC, then the host PC streams the data over LSL. So Bluetooth is no longer part of the equation by the time LSL enters.

As for synchronization, that's really up to how the manufacturer implemented LSL. I hope they are timestamping the samples based on acquisition time, not receipt time. If they are doing it correctly, and your other LSL streams are timestamping correctly, then you shouldn't have to do anything extra to synchronize.

This isn't really an issue with LSL so I'm going to close this issue. Feel free to continue the conversation if you have extra questions.
