### ISSUE TITLE
Add support for varaible length typed data

### ISSUE THREAD

**Issue by olauq** [sccn/labstreaminglayer#9]
We are using LSL to send variable length data (in particular a point cloud). The current interface leaves as the only option (unless mistaken) to do this by copying the data into a std::string (or to use a fixed size and pad the data, which is very inflexible). This is not a very good interface as it violates the ordinary semantics of a std::string (and also it leads to issues when trying to receive the data in Python). 

Since the system can already handle sending variable size string buffers, it would appear to be a relatively small interface change to add support for variable size float, etc.

**Comment by mgrivich** [comment]
There is nothing particularly wrong with using a string to hold arbitrary
data. However, You may find it more aesthetically pleasing (and it may work
better with python) to use lsl_push_sample_buf (in lsl_h.c), which sends
arbitrary length byte data.

It would be up to you to flatten your data on the sender side and
unflatten  it on the receiver side. This may still be annoying in Python,
but perhaps our python experts can comment. In C it is not hard.

A design decision was made early on to keep the interface simple. To be
full featured, we would want to send variable length data, but
sophisticated structures as well. We could revisit the decision to keep
things simple, but I know I'm not motivated to do the work this would
require at this time (as per usual, things are harder than they appear to
the outsider).

**Comment by tstenner** [comment]
In the C API there's already `pull_sample_buf()` which allocates variable sized char* arrays for you.
Could you add some pseudocode for your use case?

**Comment by MatsumotoJ** [comment]
Hi. I am Jumpei, who is a collaborator of olauq. I am sending the code that gives the error.

C++ sender program:
```
#include <iostream>
#include <time.h>
#include <stdlib.h>
#include <LSL/lsl_cpp.h>
#include <vector>
#include <string>


int main()
{
	std::string testID = "id_0001";
	lsl::stream_info info("testDevice", "testType", 1, 30.0, lsl::cf_string, testID);

	lsl::stream_outlet outlet(info);

	long cnt = 0;
	while (true) {
		int sample_size = rand() % 1000 + 100;
		std::vector<float> sample(sample_size, 0.0);
		for (int i = 0; i < sample_size; i++) sample[i] = (float)rand() / (float)RAND_MAX;
		std::string sample_str(reinterpret_cast<const char*>(sample.data()), reinterpret_cast<const char*>(sample.data()) + sample.size() * sizeof(sample[0]));
		outlet.push_sample(&sample_str);

		while (clock() % 33 != 0);
	}

	return 0;
}
```

Python receiver program:
```
from pylsl import StreamInlet, resolve_stream

streams = resolve_stream('type', 'testType')
inlet = StreamInlet(streams[0])
info = inlet.info()

while 1:
    s, timestamp = inlet.pull_sample()
    print(s)
```

The C++ sender program works as we have checked by using a C++ receiver program (not shown). However the Python receiver gives following error:

```
receivePC.py", line 9, in <module>
    s, timestamp = inlet.pull_sample()
  File "\lib\site-packages\pylsl\pylsl.py", line 765, in pull_sample
    sample = [v.decode('utf-8') for v in sample]
  File "\lib\site-packages\pylsl\pylsl.py", line 765, in <listcomp>
    sample = [v.decode('utf-8') for v in sample]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 1: invalid continuation byte
```

Thank you very much for your help.

**Comment by tstenner** [comment]
You could call `inlet.do_pull_sample` to skip interpreting the data as UTF8 string.

**Comment by MatsumotoJ** [comment]
Thank you very much. Sorry for my late reply. `inlet.do_pull_sample` works without the error. I will make an example code including converting the array of char to the array of float and will share it here.

**Comment by cboulay** [comment]
It's been over a year since any updates. I will assume the issue is resolved. Please feel free to reopen if you have any additional details or concerns.
