### ISSUE TITLE
what happened to your forum, formerly at https://mailman.ucsd.edu/mailman/listinfo/lsl-l ?

### ISSUE THREAD

**Issue by wjcroft** [sccn/labstreaminglayer#90]
Do you have a new group URL?

I understand UCSD was responsible for killing all the mailman groups. But some of these transitioned to Google Groups. Could not find yours.

Regards, William Croft, OpenBCI

**Comment by wjcroft** [comment]
Your old group URL is at the bottom of this page:

https://github.com/sccn/labstreaminglayer

**Comment by cboulay** [comment]
Oh thanks for pointing that out.

Recently most user requests have been going through the Slack channel or GitHub issues on the associated repos.

The labstreaminglayer.org website went live recently. Probably more of a soft launch than a full launch. There is a forum there:
https://forum.labstreaminglayer.org/login

I'll get rid of the mailman link and add the forum link. Closing the issue, but feel free to continue discussion.

P.S. I always thought there should be a neurotech stack exchange. I would much prefer that over any forum, and I'd limit Slack to things that actually required a conversation. Unfortunately, I think with increasing commercial interests in the space this is less likely now than ever.

**Comment by wjcroft** [comment]
Chadwick, thanks. Posted your new info on our thread:

https://openbci.com/forum/index.php?p=/discussion/3242/labstreaminglayer-question-anyone-get-it-working-in-a-uwp-universal-windows-app

I expect the original author of that post, will reach out to you via your forum or Slack.

**Comment by cboulay** [comment]
I don't think I have an account on your forum so maybe you can relay this message.
The user working in C# should probably try posting an issue in this repo:
https://github.com/labstreaminglayer/liblsl-csharp

That will probably get most visibility among C# users.

**Comment by dmedine** [comment]
I think that LSL itself warrants its own stack exchange forum.
