### ISSUE TITLE
Warning when compiling with GCC 4.9

### ISSUE THREAD

**Issue by mgrivich** [sccn/labstreaminglayer#92]
When compiling with GCC 4.9, I get the warning:

`1>C:\nbs\external\lsl\trunk\LSL\liblsl\include\lsl_cpp.h(116,11): warning : 'lsl::stream_info' has a field 'lsl::stream_info::obj' whose type uses the anonymous namespace
1>       class stream_info {
`
I can remove this warning by changing
`
    namespace {
        #include "lsl_c.h"
    }
`
to 
`#include "lsl_c.h"`
Are there any objections to me committing this?

**Comment by chkothe** [comment]
Hi Matthew, can you please rename the namespace to detail?
This way the lsl_ functions don't leak into the C++ interface.

Thanks,
Christian

**Comment by chkothe** [comment]
(though it'll require searching & replacing all a lot of lsl_*** by
detail::lsl_***)

**Comment by chkothe** [comment]
Actually, on second thought, it might be good to do what you suggested.
This way C++ LSL users can use either the object-oriented or the procedural
functions...

**Comment by mgrivich** [comment]
Either solution is fine with me.

**Comment by chkothe** [comment]
Let's go with yours. I also would like to keep the C++ header as simple &
uncluttered as possible.
