### ISSUE TITLE
Record data by SCAN4.5 and labrecorder is different?

### ISSUE THREAD

**Issue by wangxinzhi0** [sccn/labstreaminglayer#94]
I'm going to save EEG data produced by Neuroscan Synamp II, but got some problems.

    First, data channels got one more. For example, sample*64channels got samples*65channels and the last channel number are all 65535. Is that a event channel?

    Second, record data by SCAN4.5 (.cnt) is different record data by labrecorder, likely difference by a multiple?

    Please give me a favor, thanks!

**Comment by cboulay** [comment]
Please post your issue in the appropriate repo:
https://github.com/labstreaminglayer/App-Neuroscan/issues

**Comment by cboulay** [comment]
Actually, I guess it's possible that Neuroscan Synamp II has LSL support built-in to their own software.
Were you using `App-Neuroscan` or were you using LSL integrated into Neuroscan software?

**Comment by wangxinzhi0** [comment]
I used App-NeuroscanAcquire beacause it had a release version. Neuroscan Synamp II don't have LSL support built-in to their own software.
















At 2022-03-07 23:37:27, "Chadwick Boulay" ***@***.***> wrote:

Actually, I guess it's possible that Neuroscan Synamp II has LSL support built-in to their own software.
Were you using App-Neuroscan or were you using LSL integrated into Neuroscan software?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cboulay** [comment]
Ah I see. And you did post a message there and no one answered.
I will answer your question there.
