### ISSUE TITLE
LSL connection between Windows and Ubuntu

### ISSUE THREAD

**Issue by Lychfindel** [sccn/labstreaminglayer#95]
Hi,
I'm having problem on creating a LSL connection between a Windows 10 computer (that is supposed to stream BrainVision data) to an Ubuntu 18.04 laptop (that is suppose to acquire and analyze the data).
I have followed all the recommendations from the readthedocs, all the firewall are off, but still I cannot see the stream.
I have tried connecting the two laptop directly with a LAN cable, or through a router, but in both cases:
- I can ping the laptops in both ways
- I can send LSL from Ubuntu and read from windows
- If I send LSL from windows I don't see anything in Ubuntu.

Do you have any hints how this could happen?

EDIT:
If I send LSL from windows I can read it from another windows laptop.
LSL works between windows and ubuntu if both laptops are connected via wifi… But for the experiment that I'm running a lan connection would be much better…

**Comment by cboulay** [comment]
Did you try
https://labstreaminglayer.readthedocs.io/info/lslapicfg.html#defining-the-local-laboratory
?

Also, we have a new 1.16 version of liblsl that we hope to release soon that fixes a couple networking issues. Based on your description and your edit, I'm doubtful they would help in your case but they are worth trying. I've attached the binaries.

[pkg-windows-x64.zip](https://github.com/sccn/labstreaminglayer/files/8218362/pkg-windows-x64.zip)
[build-ubuntu-18.04.zip](https://github.com/sccn/labstreaminglayer/files/8218366/build-ubuntu-18.04.zip)

**Comment by dmedine** [comment]
The cause may be unrelated, but I know of a lab that has having almost an identical issue at the moment. I tried replacing lsl.dll with the 1.16 version and it still didn't work. I am convinced it was a network configuration issue, though. In their case, the had 2 Windows machines and 1 OSX. Only one of the Windows machines was having this issue (pings are fine, but LSL streams can be received but not sent). 

In their case the faulty Windows machine was connected to the internet via wifi, but had no Local Area Network. I believe this was the problem, but I am not yet sure. I would check Network and Sharing Center. Your laptops should be connected to a LAN. Consult here for more ideas how to troubleshoot: https://labstreaminglayer.readthedocs.io/info/network-connectivity.html

**Comment by Lychfindel** [comment]
Hi, thank you both!
I’m happy to say that it was not necessary to update lsl but the solution proposed by @cboulay  worked perfectly!
For anyone that will have the same problem the stream is correctly read by putting a configuration file in the receiving laptop with the ip address of the streaming laptop in the KnownPeers field (just putting the sessionID for me didn’t work).
Thank you again!
