### ISSUE TITLE
failure to connect to AMTI force plate 

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#97]
I am trying to connect to the AMTI force plate using the LSL app. It tosses me the error saying:
`Could not initialize the AMTI interface. Did not receive a response from the device (after baud rate choice). Please make sure that your device is set up properly and that your COM port supports a baud rate of 57600.`
As far as I can tell, the device is set up properly and the COM port supports that baud rate.

**Comment by chkothe** [comment]
I would probably go back to machines/OSes that are confirmed to work for
the CES lab setup, and then change one thing at a time until you have the
setup that you're trying to get to work right now.

**Comment by dmedine** [comment]
The CES lab has been dismantled. I am currently trying to re-connect the forceplate to one of the computers that has a shortcut to the app (supposedly one that was gathering that data) but so far no luck. It doesn't appear as if the drivers for the serial-usb device are installed anywhere...

**Comment by chkothe** [comment]
Right, I remember that device. They need to be installed, indeed (and since
it's not exactly a high-quality product, you can expect quirks with various
OSes) -- maybe best to first test the liveness of the serial port and once
that works, move on to the force plate.

**Comment by dmedine** [comment]
Turns out the plate wasn't connected to the receiver. I didn't think this would matter (so I didn't think to check until now), but apparently it does. Anyways, it works. As a note, the way we connect ours is through a serial port to usb connector (keyspan usa-19hs). I did have to install the dirver (http://www.tripplite.com/support/downloads/tab/1/mid/USA19HS) in order for this to work properly.
