### ISSUE TITLE
data format issue? with nidaq 

### ISSUE THREAD

**Issue by dmedine** [sccn/labstreaminglayer#99]
I am using an NIDAQ to run some synchronization tests with LSL. I am modifying old code by Matthew Grivich to use the NIDAQ. The program is written in C and is very simple. The main loop sends a 30ms pulse of 100 millivolts out of the AO_0 pin on the device. This gets looped back (through a wire) to AI_0 and read off. All this works correctly (the scope shows the correct signal on the wire).

What doesn't work correctly is that I also record this data (both the in and the out) via an LSL stream. The data container for the output and input are type `float64 *` and I have tried punning these as `float *` and shoving them into outlets of type `cft_float32` and not converting the data and sending them through `cft_double64` outlets. Nevertheless, looking at the data in the xdf recording, I get what looks like the right signal (for the output stream) but with a mangled format:
![sig_out](https://cloud.githubusercontent.com/assets/3613166/13684088/fbb31fae-e6be-11e5-8325-1a074d0c2d68.png)

As for the looped back data (which looks perfectly good when I printf it to the console) I get further badness:
![sig_in](https://cloud.githubusercontent.com/assets/3613166/13684109/154bbc00-e6bf-11e5-979a-62e167e490e5.png)

The inconsistency of the pulse is most likely unrelated to LSL, but the apparent incorrectness of the data values is troublesome.

What we should see is pulses lasting about 30ms that are 100 millvolts tall: .1, not huge +/- numbers.

**Comment by mgrivich** [comment]
I suspect you are making a mistake with number conversion and pointer 
arithmetic, unrelated to LSL to NIDAQ. Perhaps you are taking the 
address of a 64 bit number and then telling LSL that it is a 32 bit 
number? You have to do the cast from double to single before taking the 
address. If you can't figure it out, you can send me your code and I can 
look at it.

Matthew

**Comment by dmedine** [comment]
Yeah I figured it was something like this. I didn't realize you couldn't do `(float *) double_ptr`, although that makes perfect sense now that I think about... 'Duh', as they say.

So, converting to float and then pushing that pointer through cft_float32 outlets works as expected. The wiggle in the input signal was an artifact of noise. But, what I don't understand is why I can't push a value pointed to by `float64` (which is just NIDAQ's definition of `double`) through an lsl outlet of type `cft_double64`.
